### ISSUE TITLE
while in synchronized does not compile for nativelib

### ISSUE THREAD

**Issue by valdisxp1** [scala-native/scala-native#1018]
Adding the `doesNotCompile` or `doesNotCompile2` method to nativeLib causes the compiler to crash with a `NoSuchElementException`. The exception goes away if `synchronized` returns a non-Unit (`doesCompile`) or it is the only statement in the function (`doesCompile2`)
```scala
object BreaksWhileInSynchronized {
  def doesNotCompile = {
    42
    synchronized {
      while(false) {
        //can be also non-empty
      }
    }
  }
  def doesNotCompile2 = {
    synchronized {
      while(false) {
        //can be also non-empty
      }
    }
    false
  }

  def doesCompile = {
    synchronized {
      while(false) {
        //can be also non-empty
      }
      4
    }
    false
  }

  def doesCompile2 = {
    synchronized {
      while(false) {
        //can be also non-empty
      }
    }
  }
}
```

<details>
<summary>Stack trace</summary>
<p>

```
	java.util.NoSuchElementException: key not found: method while$1
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at scala.scalanative.nscplugin.NirGenStat$MethodEnv.resolve(NirGenStat.scala:31)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApplyLabel(NirGenExpr.scala:687)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApply(NirGenExpr.scala:670)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:93)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genSynchronized(NirGenExpr.scala:1335)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApplyPrimitive(NirGenExpr.scala:734)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApply(NirGenExpr.scala:672)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:93)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer$$anonfun$genBlock$1.apply(NirGenExpr.scala:121)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer$$anonfun$genBlock$1.apply(NirGenExpr.scala:121)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genBlock(NirGenExpr.scala:121)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:59)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genBlock(NirGenExpr.scala:122)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:59)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genBody$1$1.apply(NirGenStat.scala:374)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genBody$1$1.apply(NirGenStat.scala:374)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genBody$1(NirGenStat.scala:373)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genNormalMethodBody(NirGenStat.scala:379)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genMethod$1.apply(NirGenStat.scala:207)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethod(NirGenStat.scala:183)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genMethods$1.apply(NirGenStat.scala:168)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genMethods$1.apply(NirGenStat.scala:166)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethods(NirGenStat.scala:166)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genNormalClass(NirGenStat.scala:96)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genClass$1.apply$mcV$sp(NirGenStat.scala:71)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genClass$1.apply(NirGenStat.scala:70)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genClass$1.apply(NirGenStat.scala:70)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genClass(NirGenStat.scala:69)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$scala$scalanative$nscplugin$NirGenPhase$NirCodePhase$$genClass$1$1.apply(NirGenPhase.scala:96)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$scala$scalanative$nscplugin$NirGenPhase$NirCodePhase$$genClass$1$1.apply(NirGenPhase.scala:95)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.scala$scalanative$nscplugin$NirGenPhase$NirCodePhase$$genClass$1(NirGenPhase.scala:95)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(NirGenPhase.scala:105)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(NirGenPhase.scala:105)
	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:239)
	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:145)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1.apply$mcV$sp(NirGenPhase.scala:105)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1.apply(NirGenPhase.scala:103)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1.apply(NirGenPhase.scala:103)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.apply(NirGenPhase.scala:103)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.run(NirGenPhase.scala:65)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:913)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
</p>
</details>

<details>
<summary>Stack trace2</summary>
<p>

```
java.util.NoSuchElementException: key not found: method while$1
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at scala.scalanative.nscplugin.NirGenStat$MethodEnv.resolve(NirGenStat.scala:31)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApplyLabel(NirGenExpr.scala:687)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApply(NirGenExpr.scala:670)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:93)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genSynchronized(NirGenExpr.scala:1335)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApplyPrimitive(NirGenExpr.scala:734)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApply(NirGenExpr.scala:672)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:93)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer$$anonfun$genBlock$1.apply(NirGenExpr.scala:121)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer$$anonfun$genBlock$1.apply(NirGenExpr.scala:121)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genBlock(NirGenExpr.scala:121)
	at scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:59)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genBody$1$1.apply(NirGenStat.scala:374)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genBody$1$1.apply(NirGenStat.scala:374)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genBody$1(NirGenStat.scala:373)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genNormalMethodBody(NirGenStat.scala:379)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genMethod$1.apply(NirGenStat.scala:207)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethod(NirGenStat.scala:183)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genMethods$1.apply(NirGenStat.scala:168)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genMethods$1.apply(NirGenStat.scala:166)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethods(NirGenStat.scala:166)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genNormalClass(NirGenStat.scala:96)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genClass$1.apply$mcV$sp(NirGenStat.scala:71)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genClass$1.apply(NirGenStat.scala:70)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer$$anonfun$genClass$1.apply(NirGenStat.scala:70)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenStat$StatBuffer.genClass(NirGenStat.scala:69)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$scala$scalanative$nscplugin$NirGenPhase$NirCodePhase$$genClass$1$1.apply(NirGenPhase.scala:96)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$scala$scalanative$nscplugin$NirGenPhase$NirCodePhase$$genClass$1$1.apply(NirGenPhase.scala:95)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.scala$scalanative$nscplugin$NirGenPhase$NirCodePhase$$genClass$1(NirGenPhase.scala:95)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(NirGenPhase.scala:105)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(NirGenPhase.scala:105)
	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:239)
	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:145)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1.apply$mcV$sp(NirGenPhase.scala:105)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1.apply(NirGenPhase.scala:103)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$1.apply(NirGenPhase.scala:103)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.apply(NirGenPhase.scala:103)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.run(NirGenPhase.scala:65)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:913)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
</p>
</details>

**Comment by densh** [comment]
Fixed by #1020
