### ISSUE TITLE
Array(-2147483648).map(_ % -1) crash

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#1078]
- https://travis-ci.org/xuwei-k/scala-native-1078/builds/300520927
- https://github.com/xuwei-k/scala-native-1078/commit/272c45821646289a2eabacfcfffae2788c6847d3

### build.sbt

```scala
scalaVersion := "2.11.11"

enablePlugins(ScalaNativePlugin)
```

### project/plugin.sbt

```scala
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.3")
```

### Main.scala

```scala
package example

object Main {
  def main(args: Array[String]): Unit = {
    println(Array(-2147483648).map(_ % -1))
  }
}
```

### project/build.properties

```
sbt.version = 0.13.16
```

### result

```
[info] Compiling 1 Scala source to /home/travis/build/xuwei-k/scala-native-1078/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.11. Compiling...
[info]   Compilation completed in 15.097 s
[info] Linking (2377 ms)
[info] Discovered 1268 classes and 9348 methods
[info] Optimizing (6315 ms)
[info] Generating intermediate code (1788 ms)
[info] Produced 40 files
[info] Compiling to native code (3906 ms)
[info] Linking native code (120 ms)
java.lang.RuntimeException: Nonzero exit code: 136
	at scala.sys.package$.error(package.scala:27)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$14$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(ScalaNativePluginInternal.scala:430)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$14$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(ScalaNativePluginInternal.scala:430)
	at scala.Option.foreach(Option.scala:236)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$14$$anonfun$apply$16$$anonfun$apply$17.apply(ScalaNativePluginInternal.scala:430)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$14$$anonfun$apply$16$$anonfun$apply$17.apply(ScalaNativePluginInternal.scala:415)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 136
```

**Comment by xuwei-k** [comment]
also `Array(Long.MinValue).map(_ % -1)`

**Comment by densh** [comment]
Thanks for the bug report, @xuwei-k ! 👍

**Comment by pbatko** [comment]
Minimal
```
def foo(value: Long): Long = {
    value % -1L
  }
```
gives LLVM IR
```
define i64 @"Test$::foo_i64_i64"(i8* %_1, i64 %_2) personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
_3.0:
  %_4 = srem i64 %_2, -1
  ret i64 %_4
}
```
and in gdb
```
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x000000000048de96 in Test$::foo_i64_i64 ()
[Current thread is 1 (Thread 0x7f6c5e828780 (LWP 19733))]
(gdb) bt
#0  0x000000000048de96 in Test$::foo_i64_i64 ()
#1  0x000000000048df5b in Test$::main_scala.scalanative.runtime.ObjectArray_unit ()
#2  0x000000000044b0cd in main ()
```

Looking at LLVM spec  for `srem` instruction, it's actually undefined when the corresponding division could overflow:

https://llvm.org/docs/LangRef.html#srem-instruction

> Overflow also leads to undefined behavior; this is a rare case, but can occur, for example, by taking the remainder of a 32-bit division of -2147483648 by -1. (The remainder doesn’t actually overflow, but this rule lets srem be implemented using instructions that return both the result of the division and the remainder.)
