### ISSUE TITLE
AssertionError on tuple deconstruction

### ISSUE THREAD

**Issue by cornerman** [scala-native/scala-native#111]
Deconstruction of tuples seems to be broken.

```
object Main {
  def main(args: Array[String]): Unit = {
    val (a,b) = (1,2)
  }
}
```

Leads to the following error when running:
```
java.lang.AssertionError: assertion failed: failed to find vslot for Member(Type(scala.Tuple2),_1_class.java.lang.Object) in Type(scala.Tuple2) (all vslots: List(Member(Type(java.lang.Object),equals_class.java.lang.Object_bool)), all methods: List(Member(Type(java.lang.Object),equals_class.java.lang.Object_bool), Member(Type(java.lang.Object),init), Member(Type(scala.Tuple2),_1$mcI$sp_i32), Member(Type(scala.Tuple2),_1_class.java.lang.Object), Member(Type(scala.Tuple2),_2$mcI$sp_i32), Member(Type(scala.Tuple2),_2_class.java.lang.Object), Member(Type(scala.Tuple2),canEqual_class.java.lang.Object_bool), Member(Type(scala.Tuple2),equals_class.java.lang.Object_bool), Member(Type(scala.Tuple2),init_class.java.lang.Object_class.java.lang.Object)))
	at scala.Predef$.assert(Predef.scala:179)
	at scala.scalanative.compiler.analysis.ClassHierarchy$Method.vindex(ClassHierarchy.scala:138)
	at scala.scalanative.compiler.pass.ClassLowering$$anonfun$preInst$1.applyOrElse(ClassLowering.scala:121)
	at scala.scalanative.compiler.pass.ClassLowering$$anonfun$preInst$1.applyOrElse(ClassLowering.scala:92)
	at scala.scalanative.nir.Pass$class.scala$scalanative$nir$Pass$$hook(Pass.scala:35)
	at scala.scalanative.nir.Pass$class.scala$scalanative$nir$Pass$$txInst(Pass.scala:90)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txBlock$1$$anonfun$5.apply(Pass.scala:81)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txBlock$1$$anonfun$5.apply(Pass.scala:81)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txBlock$1.apply(Pass.scala:81)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txBlock$1.apply(Pass.scala:77)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.nir.Pass$class.scala$scalanative$nir$Pass$$txBlock(Pass.scala:77)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txDefn$1$$anonfun$2.apply(Pass.scala:59)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txDefn$1$$anonfun$2.apply(Pass.scala:59)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txDefn$1.apply(Pass.scala:59)
	at scala.scalanative.nir.Pass$$anonfun$scala$scalanative$nir$Pass$$txDefn$1.apply(Pass.scala:50)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.nir.Pass$class.scala$scalanative$nir$Pass$$txDefn(Pass.scala:50)
	at scala.scalanative.nir.Pass$$anonfun$1.apply(Pass.scala:41)
	at scala.scalanative.nir.Pass$$anonfun$1.apply(Pass.scala:40)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.nir.Pass$class.txAssembly(Pass.scala:40)
	at scala.scalanative.nir.Pass$class.apply(Pass.scala:195)
	at scala.scalanative.compiler.pass.ClassLowering.apply(ClassLowering.scala:45)
	at scala.scalanative.compiler.Compiler.loop$1(Compiler.scala:61)
	at scala.scalanative.compiler.Compiler.apply(Compiler.scala:67)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$compileNir(ScalaNativePluginInternal.scala:24)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$6$$anonfun$apply$3$$anonfun$apply$4.apply(ScalaNativePluginInternal.scala:95)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$6$$anonfun$apply$3$$anonfun$apply$4.apply(ScalaNativePluginInternal.scala:77)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47
```

Interestingly, using pattern matching (`(1,2) match { case (a,b) => ...}`) or a Tuple3 (`val (a,b,c) = (1,2,3))` does not throw an AssertionError, but says: `terminate called after throwing an instance of 'scalanative::ExceptionWrapper*'`

**Comment by densh** [comment]
Thanks for the bug report.
