### ISSUE TITLE
clang builtins do not link

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#1144]
When I try to link code with extern objects that should link to clang builtins, I get the error:

```
java.util.NoSuchElementException: key not found: Member(Top(__extern),__builtin_abs)
```

For example, I can reproduce this running the following code, either in the sandbox on the current `master` branch, or in a standalone project.  

```scala
import scalanative.native._

object main {
  def main(args:Array[String]):Unit = {
    val ret = MemUtils.__builtin_abs(-5)
  }
}

@extern
object MemUtils {
  def __builtin_abs(x:Int):Int = extern
}

```
It's definitely not just `__builtin_abs` -- I've tested this with `__builtin_frame_address` and `__builtin__return_address` too.  I'm not super knowledgable about clang internals, but it does look like all of these should be defined in the Builtins.h file: https://github.com/llvm-mirror/clang/blob/master/include/clang/Basic/Builtins.def

I'm running SBT 0.13.13 still, scala-native 0.3.6, scala 2.11.8

Full stack trace, in case that helps:
```[info] Compiling 1 Scala source to /Users/rwhaling/Documents/dev/scala-native/sandbox/target/scala-2.11/classes...
[info] Linking (3132 ms)
[info] Discovered 752 classes and 4502 methods
[info] Optimizing (2343 ms)
java.util.NoSuchElementException: key not found: Member(Top(__extern),__builtin_abs)
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genDeps$1.apply(CodeGen.scala:94)
	at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genDeps$1.apply(CodeGen.scala:89)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.scalanative.codegen.CodeGen$Impl.genDeps(CodeGen.scala:89)
	at scala.scalanative.codegen.CodeGen$Impl.gen(CodeGen.scala:82)
	at scala.scalanative.codegen.CodeGen$$anonfun$apply$1$$anonfun$debug$1$2.apply(CodeGen.scala:43)
	at scala.scalanative.codegen.CodeGen$$anonfun$apply$1$$anonfun$debug$1$2.apply(CodeGen.scala:38)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.parallel.mutable.ParHashTable$EntryIterator.foreach(ParHashTable.scala:31)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runSubtask(ForkJoinPool.java:1357)
	at scala.concurrent.forkjoin.ForkJoinPool.tryHelpStealer(ForkJoinPool.java:2253)
	at scala.concurrent.forkjoin.ForkJoinPool.awaitJoin(ForkJoinPool.java:2377)
	at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
	at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:444)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:514)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:187)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (sandbox/compile:nativeGenerateLL) java.util.NoSuchElementException: key not found: Member(Top(__extern),__builtin_abs)
```

**Comment by rwhaling** [comment]
I've made a little more progress.  Some of the clang builtins that I'm interested are just wrappers around LLVM intrinsics: for example, `__builtin_return_address` translates to a call to `llvm.returnaddress`.  Others, like `__builtin_abs`, seem to just get inlined by clang.

If I'm understanding Scala Native's architecture correctly, this makes sense, sense we never touch the clang frontend.  As long as that's intentional, I think we can close this issue.

That said, these are things that some C-oriented programmers might want, so we could think about adding bindings for some/all of the llvm intrinsics.  They're listed here: http://llvm.org/docs/LangRef.html#intrinsic-functions

**Comment by densh** [comment]
Using the LLVM's equivalent is indeed the correct solution for this.
