### ISSUE TITLE
java.util.NoSuchElementException: key not found: Local

### ISSUE THREAD

**Issue by fsaab** [scala-native/scala-native#1154]
---------------------------------- Code -----------------------------
scala native:

// this is working:

val store_lcia_ptr:Ptr[Ptr[CDouble]]=TwoDimStore.initStore(settings.montecarlo_iterations,length) 

// this will trigger the Error
 TwoDimStore.putDataAtIteration(store_lcia_ptr,iter,lcia_ptr,LCAIndexes.ImpactCategoryIndexLength.toInt)

@extern
@link("TwoDimStore")
// Aribtary object name
object TwoDimStore {
 
    //double ** initStore( int iterations,int datasize);

    def initStore(iterations:CInt, datasize:CInt):Ptr[Ptr[CDouble]] = extern
    
    //void putDataAtIteration (double ** store,int iteration,double * data,int datasize);

    def putDataAtIteration(store:Ptr[Ptr[CDouble]], iteration:CInt,data:Ptr[CDouble], datasize:CInt) = extern
    
    

}

c++: 

header:

#ifdef __cplusplus
extern "C" {
#endif
    
    double ** initStore( int iterations,int datasize);
    void putDataAtIteration (double ** store,int iteration,double * data,int datasize);
   
    
#ifdef __cplusplus
}
#endif

implementation:

#include "TwoDimStore.h"
#include <iostream>

double ** initStore( int iterations,int datasize){
    
    double** store=new double*[iterations];
    
    int i=0;
    
    while(i<iterations){
        
        store[i]=new double[datasize];
        i++;
    }
    
    return store;
    
}

void putDataAtIteration (double ** store,int iteration,double * data,int datasize){
    
    int i=0;
    
    while(i<datasize){
        
        store[iteration][i]=data[i];
        
        i++;
    }
    

}

-------------------------------------stack trace----------------------------------

[info] Linking (4451 ms)
[info] Discovered 1473 classes and 10847 methods
java.util.NoSuchElementException: key not found: Local(597)
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:64)
	at scala.scalanative.optimizer.analysis.UseDef$$anonfun$scala$scalanative$optimizer$analysis$UseDef$$deps$1$1.apply(UseDef.scala:90)
	at scala.scalanative.optimizer.analysis.UseDef$$anonfun$scala$scalanative$optimizer$analysis$UseDef$$deps$1$1.apply(UseDef.scala:89)
	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:224)
	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:130)
	at scala.scalanative.optimizer.analysis.UseDef$.scala$scalanative$optimizer$analysis$UseDef$$deps$1(UseDef.scala:89)
	at scala.scalanative.optimizer.analysis.UseDef$$anonfun$apply$4$$anonfun$apply$5.apply(UseDef.scala:114)
	at scala.scalanative.optimizer.analysis.UseDef$$anonfun$apply$4$$anonfun$apply$5.apply(UseDef.scala:112)
	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:224)
	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:130)
	at scala.scalanative.optimizer.analysis.UseDef$$anonfun$apply$4.apply(UseDef.scala:112)
	at scala.scalanative.optimizer.analysis.UseDef$$anonfun$apply$4.apply(UseDef.scala:111)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.scalanative.optimizer.analysis.UseDef$.apply(UseDef.scala:111)
	at scala.scalanative.optimizer.pass.DeadCodeElimination.onInsts(DeadCodeElimination.scala:17)
	at scala.scalanative.optimizer.Pass$class.onDefn(Pass.scala:33)
	at scala.scalanative.optimizer.pass.DeadCodeElimination.onDefn(DeadCodeElimination.scala:12)
	at scala.scalanative.optimizer.Pass$$anonfun$onDefns$1.apply(Pass.scala:22)
	at scala.scalanative.optimizer.Pass$$anonfun$onDefns$1.apply(Pass.scala:22)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scala.scalanative.optimizer.Pass$class.onDefns(Pass.scala:22)
	at scala.scalanative.optimizer.pass.DeadCodeElimination.onDefns(DeadCodeElimination.scala:12)
	at scala.scalanative.optimizer.Optimizer$.scala$scalanative$optimizer$Optimizer$$loop$1(Optimizer.scala:64)
	at scala.scalanative.optimizer.Optimizer$$anonfun$apply$1.apply(Optimizer.scala:74)
	at scala.scalanative.optimizer.Optimizer$$anonfun$apply$1.apply(Optimizer.scala:70)
	at scala.collection.parallel.AugmentedIterableIterator$class.map2combiner(RemainsIterator.scala:120)
	at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.map2combiner(ParHashMap.scala:79)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1057)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1054)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runSubtask(ForkJoinPool.java:1357)
	at scala.concurrent.forkjoin.ForkJoinPool.tryHelpStealer(ForkJoinPool.java:2253)
	at scala.concurrent.forkjoin.ForkJoinPool.awaitJoin(ForkJoinPool.java:2377)
	at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
	at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:444)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:514)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:187)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (compile:nativeOptimizeNIR) java.util.NoSuchElementException: key not found: Local(597)
[error] Total time: 41 s, completed Jan 29, 2018 12:12:20 PM

**Comment by fsaab** [comment]
build.sb:

lazy val make = taskKey[Unit]("Building native components")

make := {
  "make" !
}

enablePlugins(ScalaNativePlugin)

scalaVersion := "2.11.11"

nativeLinkingOptions ++= Seq("-L" ++ baseDirectory.value.getAbsolutePath() ++ "/target")

nativeLinkStubs := true

nativeMode := "release"

nativeGC := "immix"

compile in Compile := (compile in Compile dependsOn make).value

**Comment by fsaab** [comment]
fixed , i upgraded to latest version:

plugin.sb:
addSbtPlugin("org.scala-native" % "sbt-scala-native"  % "0.3.6")
build.sbt:

scalaVersion := "2.11.12"
