### ISSUE TITLE
exception scala.scalanative.runtime.UndefinedBehaviorError

### ISSUE THREAD

**Issue by mc-srivas** [scala-native/scala-native#1165]
I am using the scalanative.posix.errno object, and when I refer to errno.ENODATA, its blowing up with this exception.

Exception in thread "main" scala.scalanative.runtime.UndefinedBehaviorError
	at scala.scalanative.runtime.package$.undefined(package.scala:34)
	at scala.scalanative.native.package$.extern(package.scala:112)
	at scala.scalanative.posix.errno$.ENODATA(errno.scala:91)

Any reason why?

**Comment by ekrich** [comment]
I checked on the MacOS in Xcode and `ENODATA` is available without any special options. I would check the `errno.h` file on you platform.
`#define	ENODATA		96		/* No message available on STREAM */`
On MacOS it is in `../usr/include/sys`

**Comment by densh** [comment]
Hi @mc-srivas, I can't reproduce this on either linux or mac on current master. Please refile with more detailed reproduction notes if the issue still bothers you.
