### ISSUE TITLE
Unit Test: java.util.NoSuchElementException: next on empty iterator

### ISSUE THREAD

**Issue by sadhen** [scala-native/scala-native#1447]
```
sadhen:cmark-scala/ (unit) $ sbt                                                                                                                                 [23:58:30]
[info] Loading global plugins from /home/sadhen/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/home/sadhen/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading settings for project cmark-scala-build from plugins.sbt ...
[info] Loading project definition from /home/sadhen/native/cmark-scala/project
[info] Updating ProjectRef(uri("file:/home/sadhen/native/cmark-scala/project/"), "cmark-scala-build")...
[info] Done updating.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to root (in build file:/home/sadhen/native/cmark-scala/)
[info] sbt server started at local:///home/sadhen/.sbt/1.0/server/29f7b9ee7424053d42f5/sock
sbt:root> projects
[info] In file:/home/sadhen/native/cmark-scala/
[info]     cmark
[info]   * root
[info]     tests
sbt:root> tests/
Display all 278 possibilities? (y or n) 
sbt:root> tests/test
/                    ::                   test:                testForkedParallel   testFrameworks       testGrouping         testListeners        testLoader           
testOnly             testOptions          testQuick            
sbt:root> tests/test
[info] Linking (855 ms)
[info] Discovered 1294 classes and 9270 methods
[info] Optimizing (debug mode) (1264 ms)
[info] Generating intermediate code (423 ms)
[info] Produced 48 files
[info] Compiling to native code (583 ms)
[info] Linking native code (immix gc) (87 ms)
[info] Starting process '/home/sadhen/native/cmark-scala/unit-tests/target/scala-2.11/tests-out' on port '36691'.
[success] Total time: 4 s, completed 2019-3-3 23:58:59
sbt:root> [info] shutting down server
sadhen:cmark-scala/ (unit) $ unit-tests/target/scala-2.11/tests-out                                                                                               [0:00:54]
java.util.NoSuchElementException: next on empty iterator
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at java.lang.Throwable.init(Unknown Source)
        at java.lang.Exception.init(Unknown Source)
        at java.lang.RuntimeException.init(Unknown Source)
        at java.lang.RuntimeException.init(Unknown Source)
        at java.util.NoSuchElementException.init(Unknown Source)
        at scala.collection.Iterator$$anon$2.next(Unknown Source)
        at scala.collection.Iterator$$anon$2.next(Unknown Source)
        at scala.collection.IndexedSeqLike$Elements.next(Unknown Source)
        at scala.collection.IterableLike$class.head(Unknown Source)
        at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(Unknown Source)
        at scala.collection.IndexedSeqOptimized$class.head(Unknown Source)
        at scala.collection.mutable.ArrayOps$ofRef.head(Unknown Source)
        at scala.scalanative.testinterface.TestMainBase.testMain(Unknown Source)
        at scala.scalanative.testinterface.TestMain$.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

Environment:
```
sadhen:cmark-scala/ (unit) $ java -version                                                                                                                        [0:01:26]
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-20181024121959.buildslave.jdk8u-src-tar--b12)
GraalVM 1.0.0-rc12 (build 25.192-b12-jvmci-0.54, mixed mode)

sadhen:cmark-scala/ (unit) $ cat /etc/issue                                                                                                                       [0:04:20]
Debian GNU/Linux buster/sid \n \l
```

**Comment by sadhen** [comment]
see https://github.com/sadhen/cmark-scala/tree/unit

**Comment by densh** [comment]
Hi @sadhen,

> sbt:root> tests/test

The project you linked clearly doesn't have "tests" subproject. You should just run "test" and it works as expected (i.e. does nothing because there are no tests).

> sadhen:cmark-scala/ (unit) $ unit-tests/target/scala-2.11/tests-out    

Why are you trying to run tests binary directly? It expects additional arguments and is only meant to be run by the sbt plugin with corresponding unit test integration layer. The layer passes extra arguments to establish a connection to pass test results back to sbt.

I couldn't reproduce any issue with the ticket you filed, please reopen with more clear reproduction steps and what exactly you thought was wrong here.
