### ISSUE TITLE
java.lang.IntegerSuite failure

### ISSUE THREAD

**Issue by sadhen** [scala-native/scala-native#1463]
```
sbt (scala-native)> tests/testOnly java.lang.IntegerSuite
[info] Linking (3299 ms)
[warn]
[warn] Found 3 errors on @"M35java.util.regex.cre2h$RE2RegExpOps$D18hashCode$extensionR_iE" :
[warn]
[warn]   0000  def @"M35java.util.regex.cre2h$RE2RegExpOps$D18hashCode$extensionR_iE" : (@"T35java.util.regex.cre2h$RE2RegExpOps$", ptr) => int {
[warn]   0001  %3(%1 : @"T35java.util.regex.cre2h$RE2RegExpOps$", %2 : ptr):
[warn]   0002    %4 = method %2 : ptr, "D8hashCodeiE"
[warn]   0003    %5 = call[(@"T16java.lang.Object") => int] %4 : ptr(%2 : ptr)
[warn]   0004    ret %5 : int
[warn]   0005  }
[warn]
[warn]   in inst #2 :
[warn]     expected @"T16java.lang.Object", but got ptr
[warn]   in inst #2 :
[warn]     can't resolve method on ptr
[warn]   in inst #3 / arg #1 :
[warn]     expected @"T16java.lang.Object", but got ptr
[warn]
[warn] 3 errors found
[info] Discovered 5063 classes and 28420 methods
[info] Optimizing (debug mode) (21271 ms)
[warn]
[warn] Found 3 errors on @"M35java.util.regex.cre2h$RE2RegExpOps$D18hashCode$extensionR_iE" :
[warn]
[warn]   0000  def @"M35java.util.regex.cre2h$RE2RegExpOps$D18hashCode$extensionR_iE" : (@"T35java.util.regex.cre2h$RE2RegExpOps$", ptr) => int {
[warn]   0001  %3(%1 : @"T35java.util.regex.cre2h$RE2RegExpOps$", %2 : ptr):
[warn]   0002    %4 = method %2 : ptr, "D8hashCodeiE"
[warn]   0003    %5 = call[(@"T16java.lang.Object") => int] %4 : ptr(%2 : ptr)
[warn]   0004    ret %5 : int
[warn]   0005  }
[warn]
[warn]   in inst #2 :
[warn]     expected @"T16java.lang.Object", but got ptr
[warn]   in inst #2 :
[warn]     can't resolve method on ptr
[warn]   in inst #3 / arg #1 :
[warn]     expected @"T16java.lang.Object", but got ptr
[warn]
[warn] 3 errors found
[info] Generating intermediate code (30036 ms)
[info] Produced 4 files
[info] Compiling to native code (13051 ms)
[info] Linking native code (immix gc, none lto) (974 ms)
[info] Total (77727 ms)
[info] Starting process '/Users/rendong/native/scala-native/unit-tests/target/scala-2.11/tests-out' on port '54740'.
[info] * java.lang.IntegerSuite$
[trace] Stack trace suppressed: run last tests/nativetest:testOnly for the full output.
[error] Could not run test java.lang.IntegerSuite: java.net.SocketException: Socket is closed
[trace] Stack trace suppressed: run last tests/nativetest:testOnly for the full output.
[error] java.lang.NullPointerException
[trace] Stack trace suppressed: run last tests/nativetest:testOnly for the full output.
[error] (tests/nativetest:testOnly) java.net.SocketException: Socket closed
[error] Total time: 79 s, completed 2019-3-17 18:48:04
sbt (scala-native)> last tests/nativetest:testOnly
[debug] Running TaskDef(java.lang.IntegerSuite, DeserializedSubclassFingerprint(true,tests.Suite,false), false, [SuiteSelector])
java.net.SocketException: Socket is closed
	at java.net.Socket.setSoTimeout(Socket.java:1137)
	at scala.scalanative.testinterface.ComRunner.receive(ComRunner.scala:101)
	at scala.scalanative.testinterface.ScalaNativeRunner.receive(ScalaNativeRunner.scala:36)
	at scala.scalanative.testinterface.ScalaNativeTask.receive$1(ScalaNativeTask.scala:31)
	at scala.scalanative.testinterface.ScalaNativeTask.execute(ScalaNativeTask.scala:42)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test java.lang.IntegerSuite: java.net.SocketException: Socket is closed
java.lang.NullPointerException
	at sbt.JUnitXmlTestsListener$TestSuite$$anonfun$2.apply(JUnitXmlTestsListener.scala:78)
	at sbt.JUnitXmlTestsListener$TestSuite$$anonfun$2.apply(JUnitXmlTestsListener.scala:71)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.JUnitXmlTestsListener$TestSuite.stop(JUnitXmlTestsListener.scala:71)
	at sbt.JUnitXmlTestsListener.writeSuite(JUnitXmlTestsListener.scala:180)
	at sbt.JUnitXmlTestsListener.endGroup(JUnitXmlTestsListener.scala:161)
	at sbt.TestRunner$$anonfun$run$4.apply(TestFramework.scala:90)
	at sbt.TestRunner$$anonfun$run$4.apply(TestFramework.scala:90)
	at sbt.TestFramework$$anonfun$safeForeach$1.apply(TestFramework.scala:107)
	at sbt.TestFramework$$anonfun$safeForeach$1.apply(TestFramework.scala:107)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at sbt.TestFramework$.safeForeach(TestFramework.scala:107)
	at sbt.TestRunner.safeListenersCall(TestFramework.scala:96)
	at sbt.TestRunner.run(TestFramework.scala:90)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NullPointerException
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at scala.scalanative.testinterface.ComRunner.close(ComRunner.scala:107)
	at scala.scalanative.testinterface.ComRunner.send(ComRunner.scala:63)
	at scala.scalanative.testinterface.ScalaNativeRunner.send(ScalaNativeRunner.scala:33)
	at scala.scalanative.testinterface.ScalaNativeRunner.done(ScalaNativeRunner.scala:51)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:625)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:623)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:623)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:621)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (tests/nativetest:testOnly) java.net.SocketException: Socket closed
```

**Comment by sadhen** [comment]
```
➜  ~ brew info re2
re2: stable 20190101 (bottled), HEAD
Alternative to backtracking PCRE-style regular expression engines
https://github.com/google/re2
/usr/local/Cellar/re2/20190101 (14 files, 1.1MB) *
  Poured from bottle on 2019-03-17 at 14:07:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/re2.rb
==> Options
--HEAD
	Install HEAD version
```

**Comment by LeeTibbert** [comment]
@sadhen Whatever your machine has please keep it away from mine ;-).
Seriously, sorry you are experiencing a problem.

A bit of lore is helpful.  

1. the re2 errors are a known glitch of currently incomplete work. Your RE2 is almost
    certainly OK and unused by IntegerSuite.

2. Almost all the noise about sockets is because unit-tests does not handle an interior test
    failing. 

That said, a couple of questions, if you please.

1,  Does this happen every time you run IntegerSuite?  What happens if you run, say, LongSuite?
    It does not do you much good, but both those suites run in both debug & release mode
    for sbt 0.13.7 & 1.2.6.  I run test-all in each of the four configurations before I submit a PR.

2. It looks like you are running a snapshot version of 0.4.0 (which is good). Is your snapshot
    within a week or so of being current.  I find that the testing framework in more robust
    with reasonably current 0.4.0-Snapshot. At the least, you might get a message about
     what is failing and that would give us a clue about why.

     Are you running in a Latin-1 environment or are you using Chinese characters?
     We have been working to make Unicode support more robust, but I can imagine
     IntegerSuite falling over dead with Chinese characters.

**Comment by densh** [comment]
@sadhen I can't seem to reproduce this on current master neither on macos nor linux. Feel free to reopen with extra reproduction steps if you are still having this issue on current master.
