### ISSUE TITLE
Java 11 compiles but fails to link

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1681]
The following code in the sandbox using Java 11 and sbt 1.2.8 and a fresh rebuild. As reported by @muxanick in https://github.com/scala-native/scala-native/issues/1680
```
import scala.collection.JavaConverters._
object Test {
  def strange(s: String): List[String] = {
    s.lines.iterator.asScala.toList
  }

  def main(args: Array[String]): Unit = {
    println(strange("line1\nline2\nline3"))
  }
}
```
`s.lines` is a Java Stream.
Result:
```
> sandbox/run
[info] Updating {file:/Users/eric/workspace/scala-native/}sandbox...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/eric/workspace/scala-native/sandbox/target/scala-2.11/classes...
[info] Linking (506 ms)
[warn] 
[warn] Found 1 errors on @"M5Test$D7strangeL16java.lang.StringL31scala.collection.immutable.ListE" :
[warn] 
[warn]   0000  def @"M5Test$D7strangeL16java.lang.StringL31scala.collection.immutable.ListE" : (@"T5Test$", @"T16java.lang.String") => @"T31scala.collection.immutable.List" {
[warn]   0001  %3(%1 : @"T5Test$", %2 : @"T16java.lang.String"):
[warn]   0002    %4 = module @"T32scala.collection.JavaConverters$"
[warn]   0003    %5 = method %2 : @"T16java.lang.String", "D5linesL23java.util.stream.StreamE"
[warn]   0004    %6 = call[(@"T16java.lang.String") => @"T23java.util.stream.Stream"] %5 : ptr(%2 : @"T16java.lang.String")
[warn]   0005    %7 = method %6 : @"T23java.util.stream.Stream", "D8iteratorL18java.util.IteratorE"
[warn]   0006    %8 = call[(@"T27java.util.stream.BaseStream") => @"T18java.util.Iterator"] %7 : ptr(%6 : @"T23java.util.stream.Stream")
[warn]   0007    %9 = method %4 : !?@"T32scala.collection.JavaConverters$", "D24asScalaIteratorConverterL18java.util.IteratorL43scala.collection.convert.Decorators$AsScalaE"
[warn]   0008    %10 = call[(@"T40scala.collection.convert.DecorateAsScala", @"T18java.util.Iterator") => @"T43scala.collection.convert.Decorators$AsScala"] %9 : ptr(%4 : !?@"T32scala.collection.JavaConverters$", %8 : @"T18java.util.Iterator")
[warn]   0009    %11 = method %10 : @"T43scala.collection.convert.Decorators$AsScala", "D7asScalaL16java.lang.ObjectE"
[warn]   0010    %12 = call[(@"T43scala.collection.convert.Decorators$AsScala") => @"T16java.lang.Object"] %11 : ptr(%10 : @"T43scala.collection.convert.Decorators$AsScala")
[warn]   0011    %13 = as[@"T32scala.collection.TraversableOnce"] %12 : @"T16java.lang.Object"
[warn]   0012    %14 = method %13 : @"T32scala.collection.TraversableOnce", "D6toListL31scala.collection.immutable.ListE"
[warn]   0013    %15 = call[(@"T32scala.collection.TraversableOnce") => @"T31scala.collection.immutable.List"] %14 : ptr(%13 : @"T32scala.collection.TraversableOnce")
[warn]   0014    ret %15 : @"T31scala.collection.immutable.List"
[warn]   0015  }
[warn] 
[warn]   in inst #3 : 
[warn]     can't call D5linesL23java.util.stream.StreamE on @"T16java.lang.String"
[warn] 
[warn] 1 errors found
[info] Checking intermediate code (50 ms)
[info] Dumping intermediate code (83 ms)
[info] Discovered 586 classes and 3518 methods
[info] Optimizing (debug mode) (921 ms)
[warn] 
[warn] Found 1 errors on @"M5Test$D7strangeL16java.lang.StringL31scala.collection.immutable.ListE" :
[warn] 
[warn]   0000  didopt def @"M5Test$D7strangeL16java.lang.StringL31scala.collection.immutable.ListE" : (@"T5Test$", @"T16java.lang.String") => nothing {
[warn]   0001  %30000(%1 : @"T5Test$", %2 : @"T16java.lang.String"):
[warn]   0002    %30001 = module @"T32scala.collection.JavaConverters$"
[warn]   0003    %30002 = method %2 : @"T16java.lang.String", "D5linesL23java.util.stream.StreamE"
[warn]   0004    unreachable
[warn]   0005  }
[warn] 
[warn]   in inst #3 : 
[warn]     can't call D5linesL23java.util.stream.StreamE on @"T16java.lang.String"
[warn] 
[warn] 1 errors found
[info] Checking intermediate code (51 ms)
[info] Dumping intermediate code (82 ms)
[info] Generating intermediate code (564 ms)
[info] Produced 8 files
[info] Compiling to native code (2892 ms)
[info] Linking native code (immix gc, none lto) (88 ms)
[info] Total (5716 ms)
scala.scalanative.runtime.UndefinedBehaviorError
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwUndefined(Unknown Source)
	at Test$.strange(Unknown Source)
	at Test$.main(Unknown Source)
	at <none>.main(Unknown Source)
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10.apply(ScalaNativePluginInternal.scala:164)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10.apply(ScalaNativePluginInternal.scala:164)
	at scala.Option.foreach(Option.scala:236)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9.apply(ScalaNativePluginInternal.scala:164)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9.apply(ScalaNativePluginInternal.scala:149)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last sandbox/compile:run for the full output.
[error] (sandbox/compile:run) Nonzero exit code: 1
[error] Total time: 8 s, completed Aug 5, 2019, 4:08:08 PM
```

**Comment by ekrich** [comment]
The above is a workaround for this issue - https://github.com/scala-native/scala-native/issues/1680

**Comment by errikos** [comment]
This requires us to implement the missing `java.lang.String` API introduced in Java 11.

Adding something as simple as:
```scala
  def lines(): Stream[String] = {
    Stream.of(this.split("\n").map(_.asInstanceOf[AnyRef]))
  }
```
in the `String` class resolves the above issue, but there are a few other methods to implement.

**Comment by ekrich** [comment]
I tried this in JDK 11 on 2.11 and 2.12 and get the following which seems ok.
```scala
sbt:scala-native> sandbox/run
[info] compiling 1 Scala source to /Users/eric/workspace/scala-native/sandbox/target/scala-2.12/classes ...
[error] /Users/eric/workspace/scala-native/sandbox/Test.scala:5:13: value iterator is not a member of Iterator[String]
[error]     s.lines.iterator.asScala.toList
[error]             ^
[error] one error found
[error] (sandbox / Compile / compileIncremental) Compilation failed
```

But on 2.13.5 I get the following:

```scala
sbt:scala-native> sandbox/run
[info] Unpacking Scala library sources to /Users/eric/workspace/scala-native/scalalib/target/scalaSources/2.13.5...
[info] compiling 58 Scala sources to /Users/eric/workspace/scala-native/nscplugin/target/scala-2.13/classes ...
[error] /Users/eric/workspace/scala-native/nscplugin/src/main/scala/scala/scalanative/nscplugin/PrepNativeInterop.scala:103:21: value checkClassType is not a member of object PrepNativeInterop.this.global.typer
[error]           if (typer.checkClassType(tpeArg)) {
[error]                     ^
[error] one error found
[error] (nscplugin / Compile / compileIncremental) Compilation failed
[error] Total time: 17 s, completed Mar 4, 2021 5:19:45 PM
```
Maybe this can be closed?
