### ISSUE TITLE
[0.4.0] Problem throwing exception

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1708]
On 0.4.0-M2, trying to throw an exception seems to go into a loop and eventually run out of memory. Works fine on 0.3.9. 

Here is where it should throw the exception. https://github.com/ekrich/sconfig/blob/master/sconfig/shared/src/main/scala/org/ekrich/config/impl/SimpleConfig.scala#L76-L82

## Build
```Scala
scalaVersion := "2.11.12"
//nativeLTO := "thin"
nativeLinkStubs := true
libraryDependencies += "org.ekrich" %%% "sconfig" % "1.0.0"
enablePlugins(ScalaNativePlugin)
```
## Code
```Scala
package example

import org.ekrich.config.ConfigFactory

object Native {
  def main(args: Array[String]): Unit = {
    println("Testing sconfig native ...")
    val configStr =
      """
        |maxColumn = 100
        |project.git=true
        |align = none
        |danglingParentheses = true
        |newlines.neverBeforeJsNative = true
        |newlines.sometimesBeforeColonInMethodReturnType = false
        |assumeStandardLibraryStripMargin = true
        """.stripMargin

    val conf = ConfigFactory.parseString(configStr)
    println(s"Parsed config: $conf")
    val i = conf.getInt("aaa") // throws ConfigException$Missing
  }
}
```

## Expected
Testing on 0.3.9
```Scala
Testing sconfig native ...
Parsed config: Config(SimpleConfigObject({"simple-app":{"answer":42},"simple-lib":{"foo":"This value comes from simple-app's application.conf","whatever":"This value comes from simple-app's application.conf"}}))
org.ekrich.config.ConfigException$Missing: String: 1: No configuration setting found for key 'aaa'
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at java.lang.Throwable.init(Unknown Source)
	at java.lang.Exception.init(Unknown Source)
	at java.lang.RuntimeException.init(Unknown Source)
	at org.ekrich.config.ConfigException.init(Unknown Source)
	at org.ekrich.config.ConfigException.init(Unknown Source)
	at org.ekrich.config.ConfigException$Missing.init(Unknown Source)
	at org.ekrich.config.ConfigException$Missing.init(Unknown Source)
	at org.ekrich.config.impl.SimpleConfig$.findKeyOrNull(Unknown Source)
	at org.ekrich.config.impl.SimpleConfig$.org$ekrich$config$impl$SimpleConfig$$findOrNull(Unknown Source)
	at org.ekrich.config.impl.SimpleConfig.find(Unknown Source)
	at org.ekrich.config.impl.SimpleConfig.find(Unknown Source)
	at org.ekrich.config.impl.SimpleConfig.getConfigNumber(Unknown Source)
	at org.ekrich.config.impl.SimpleConfig.getInt(Unknown Source)
	at simplelib.Native$.main(Unknown Source)
	at <none>.main(Unknown Source)
```
## Actual
```Scala
[info] Linking (816 ms)
[info] Discovered 1612 classes and 12078 methods
[info] Optimizing (debug mode) (2327 ms)
[info] Generating intermediate code (1862 ms)
[info] Produced 8 files
[info] Compiling to native code (1669 ms)
[info] Linking native code (immix gc, none lto) (198 ms)
[info] Total (6932 ms)
Testing sconfig native ...
Out of heap space
	at Heap_exitWithOutOfMemory
	at Heap_AllocLarge
	at scalanative_alloc_atomic
	at _SM36scala.scalanative.runtime.CharArray$D5allociL35scala.scalanative.runtime.CharArrayE
	at _SM16java.lang.StringD6concatL16java.lang.StringL16java.lang.StringE
	at _SM42org.ekrich.config.ConfigException$Missing$D54org$ekrich$config$ConfigException$Missing$$makeMessageL16java.lang.StringL16java.lang.StringE
	at _SM41org.ekrich.config.ConfigException$MissingRL16java.lang.StringL19java.lang.ThrowableE
	at _SM33org.ekrich.config.ConfigExceptionRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
	at _SM41org.ekrich.config.ConfigException$MissingRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
	at _SM41org.ekrich.config.ConfigException$MissingRL16java.lang.StringL19java.lang.ThrowableE
	at _SM33org.ekrich.config.ConfigExceptionRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
	at _SM41org.ekrich.config.ConfigException$MissingRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
	at _SM41org.ekrich.config.ConfigException$MissingRL16java.lang.StringL19java.lang.ThrowableE
	at _SM33org.ekrich.config.ConfigExceptionRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
... pages and pages
	at _SM33org.ekrich.config.ConfigExceptionRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
	at _SM41org.ekrich.config.ConfigException$MissingRL30org.ekrich.config.ConfigOriginL16java.lang.StringL19java.lang.ThrowableE
	at _SM36org.ekrich.config.impl.SimpleConfig$D13findKeyOrNullL43org.ekrich.config.impl.AbstractConfigObjectL16java.lang.StringL33org.ekrich.config.ConfigValueTypeL27org.ekrich.config.impl.PathL42org.ekrich.config.impl.AbstractConfigValueE
	at _SM36org.ekrich.config.impl.SimpleConfig$D47org$ekrich$config$impl$SimpleConfig$$findOrNullL43org.ekrich.config.impl.AbstractConfigObjectL27org.ekrich.config.impl.PathL33org.ekrich.config.ConfigValueTypeL27org.ekrich.config.impl.PathL42org.ekrich.config.i
	at _SM35org.ekrich.config.impl.SimpleConfigD4findL27org.ekrich.config.impl.PathL33org.ekrich.config.ConfigValueTypeL27org.ekrich.config.impl.PathL42org.ekrich.config.impl.AbstractConfigValueE
	at _SM35org.ekrich.config.impl.SimpleConfigD4findL16java.lang.StringL33org.ekrich.config.ConfigValueTypeL42org.ekrich.config.impl.AbstractConfigValueE
	at _SM35org.ekrich.config.impl.SimpleConfigD15getConfigNumberL16java.lang.StringL35org.ekrich.config.impl.ConfigNumberE
	at _SM35org.ekrich.config.impl.SimpleConfigD6getIntL16java.lang.StringiE
	at _SM17simplelib.Native$D4mainLAL16java.lang.String_uE
	at main
[error] java.lang.RuntimeException: Nonzero exit code: 1

```

**Comment by ekrich** [comment]
Just throwing this exception from main will work as well.
```Scala
throw new ConfigException.Missing("path")
```

**Comment by ekrich** [comment]
I tried to minimize this without the `sconfig` library and it did not work.

```Scala
abstract class ConfigException(message: String, cause: Throwable)
    extends RuntimeException(message, cause)
    with Serializable

object ConfigException {
  class Missing(message: String, cause: Throwable)
      extends ConfigException(message, cause)
}

object FutureTest {
  def main(args: Array[String]): Unit = {
    val t = new Throwable()
    throw new ConfigException.Missing("Missing", t)
  }
}
```

**Comment by WojciechMazur** [comment]
In current 4.0.3-Snapshot version works as expected, log below. 
@sjrd I think it may be closed

```
> run
[info] Compiling 1 Scala source to /home/wojciechmazur/projects/scala-native/scala-native-example/target/scala-2.11/classes...
[info] Linking (1594 ms)
[info] Discovered 1742 classes and 12515 methods
[info] Optimizing (debug mode) (2536 ms)
[info] Generating intermediate code (734 ms)
[info] Produced 51 files
[info] Compiling to native code (1387 ms)
[info] Linking native code (immix gc) (161 ms)
Testing sconfig native ...
Parsed config: Config(SimpleConfigObject({"align":"none","assumeStandardLibraryStripMargin":true,"danglingParentheses":true,"maxColumn":100,"newlines":{"neverBeforeJsNative":true,"sometimesBeforeColonInMethodReturnType":false},"project":{"git":true}}))
org.ekrich.config.ConfigException$Missing: String: 1: No configuration setting found for key 'aaa'
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at java.lang.Throwable.init(Unknown Source)
        at java.lang.Exception.init(Unknown Source)
        at java.lang.RuntimeException.init(Unknown Source)
        at org.ekrich.config.ConfigException.init(Unknown Source)
        at org.ekrich.config.ConfigException.init(Unknown Source)
        at org.ekrich.config.ConfigException$Missing.init(Unknown Source)
        at org.ekrich.config.ConfigException$Missing.init(Unknown Source)
        at org.ekrich.config.impl.SimpleConfig$.findKeyOrNull(Unknown Source)
        at org.ekrich.config.impl.SimpleConfig$.org$ekrich$config$impl$SimpleConfig$$findOrNull(Unknown Source)
        at org.ekrich.config.impl.SimpleConfig.find(Unknown Source)
        at org.ekrich.config.impl.SimpleConfig.find(Unknown Source)
        at org.ekrich.config.impl.SimpleConfig.getConfigNumber(Unknown Source)
        at org.ekrich.config.impl.SimpleConfig.getInt(Unknown Source)
        at example.Native$.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.(Unknown Source)
        at <none>._start(Unknown Source)
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10.apply(ScalaNativePluginInternal.scala:154)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10.apply(ScalaNativePluginInternal.scala:154)
        at scala.Option.foreach(Option.scala:236)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9.apply(ScalaNativePluginInternal.scala:154)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$6$$anonfun$apply$8$$anonfun$apply$9.apply(ScalaNativePluginInternal.scala:139)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
```
