### ISSUE TITLE
Anonymous functions not working

### ISSUE THREAD

**Issue by siriux** [scala-native/scala-native#176]
I've tried this simple example on linux:

```
import scalanative.native._
import scalanative.libc.stdlib._

object Main {

  def main(args: Array[String]): Unit = {
    val p = (n: CString) => {
      fprintf(stderr, c"Hello %s!\n", n)
    }

    p(c"World")
  }
}
```

And I get this error:

```
scala.scalanative.util.package$UnsupportedException: Inst(Local(src,4),As(Ptr,Local(Local(src,1),Class(Top(java.lang.Object))))) (class scala.scalanative.nir.Inst)
	at scala.scalanative.util.package$.unsupported(package.scala:19)
	at scala.scalanative.compiler.pass.AsLowering$$anonfun$preInst$1.applyOrElse(AsLowering.scala:29)
	at scala.scalanative.compiler.pass.AsLowering$$anonfun$preInst$1.applyOrElse(AsLowering.scala:11)
	at scala.scalanative.compiler.Pass$class.scala$scalanative$compiler$Pass$$hook(Pass.scala:36)
	at scala.scalanative.compiler.Pass$class.scala$scalanative$compiler$Pass$$txInst(Pass.scala:91)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txBlock$1$$anonfun$5.apply(Pass.scala:82)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txBlock$1$$anonfun$5.apply(Pass.scala:82)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txBlock$1.apply(Pass.scala:82)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txBlock$1.apply(Pass.scala:78)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.compiler.Pass$class.scala$scalanative$compiler$Pass$$txBlock(Pass.scala:78)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txDefn$1$$anonfun$2.apply(Pass.scala:60)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txDefn$1$$anonfun$2.apply(Pass.scala:60)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txDefn$1.apply(Pass.scala:60)
	at scala.scalanative.compiler.Pass$$anonfun$scala$scalanative$compiler$Pass$$txDefn$1.apply(Pass.scala:51)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.compiler.Pass$class.scala$scalanative$compiler$Pass$$txDefn(Pass.scala:51)
	at scala.scalanative.compiler.Pass$$anonfun$1.apply(Pass.scala:42)
	at scala.scalanative.compiler.Pass$$anonfun$1.apply(Pass.scala:41)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at scala.scalanative.compiler.Pass$class.txAssembly(Pass.scala:41)
	at scala.scalanative.compiler.Pass$class.apply(Pass.scala:194)
	at scala.scalanative.compiler.pass.AsLowering.apply(AsLowering.scala:10)
	at scala.scalanative.compiler.Compiler.loop$1(Compiler.scala:71)
	at scala.scalanative.compiler.Compiler.apply(Compiler.scala:80)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$compileNir(ScalaNativePluginInternal.scala:24)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$7$$anonfun$apply$3$$anonfun$apply$4.apply(ScalaNativePluginInternal.scala:110)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$7$$anonfun$apply$3$$anonfun$apply$4.apply(ScalaNativePluginInternal.scala:89)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last *:run for the full output.
[error] (*:run) scala.scalanative.util.package$UnsupportedException: Inst(Local(src,4),As(Ptr,Local(Local(src,1),Class(Top(java.lang.Object))))) (class scala.scalanative.nir.Inst)
[error] Total time: 3 s, completed Jun 14, 2016 3:00:02 PM
```

I get a similar error when using foreach on a List.

**Comment by siriux** [comment]
Thanks, that works for me on the example provided, as well as on the foreach method of a List.
