### ISSUE TITLE
Java11 compilation issue. Java8 EOL

### ISSUE THREAD

**Issue by drocsid** [scala-native/scala-native#1769]
[info] Loading global plugins from /home/colin/.sbt/0.13/plugins
[info] Loading project definition from /tmp/code/InputAndOutput/cstring_experiment_1/project
[info] Set current project to cstring_experiment_1 (in build file:/tmp/code/InputAndOutput/cstring_experiment_1/)
[info] Compiling 2 Scala sources to /tmp/code/InputAndOutput/cstring_experiment_1/target/scala-2.11/classes...
[info] Linking (1560 ms)
[info] Discovered 786 classes and 5397 methods
java.lang.ExceptionInInitializerError
	at scala.collection.parallel.Combiner$class.$init$(Combiner.scala:39)
	at scala.collection.parallel.mutable.ResizableParArrayCombiner$$anon$1.<init>(ResizableParArrayCombiner.scala:90)
	at scala.collection.parallel.mutable.ResizableParArrayCombiner$.apply(ResizableParArrayCombiner.scala:90)
	at scala.collection.parallel.mutable.ResizableParArrayCombiner$.apply(ResizableParArrayCombiner.scala:92)
	at scala.collection.parallel.mutable.ParSeq$.newCombiner(ParSeq.scala:58)
	at scala.collection.mutable.SeqLike$class.parCombiner(SeqLike.scala:27)
	at scala.collection.mutable.AbstractSeq.parCombiner(Seq.scala:47)
	at scala.collection.Parallelizable$class.par(Parallelizable.scala:40)
	at scala.collection.AbstractTraversable.par(Traversable.scala:105)
	at scala.scalanative.interflow.Visit$class.visitLoop(Visit.scala:111)
	at scala.scalanative.interflow.Interflow.visitLoop(Interflow.scala:10)
	at scala.scalanative.interflow.Interflow$.apply(Interflow.scala:152)
	at scala.scalanative.build.ScalaNative$$anonfun$optimize$1.apply(ScalaNative.scala:77)
	at scala.scalanative.build.ScalaNative$$anonfun$optimize$1.apply(ScalaNative.scala:75)
	at scala.scalanative.build.Logger$class.time(Logger.scala:32)
	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
	at scala.scalanative.build.ScalaNative$.optimize(ScalaNative.scala:75)
	at scala.scalanative.build.Build$$anonfun$build$1.apply(Build.scala:57)
	at scala.scalanative.build.Build$$anonfun$build$1.apply(Build.scala:53)
	at scala.scalanative.build.Logger$class.time(Logger.scala:32)
	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
	at scala.scalanative.build.Build$.build(Build.scala:53)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5$$anonfun$apply$7.apply(ScalaNativePluginInternal.scala:145)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5$$anonfun$apply$7.apply(ScalaNativePluginInternal.scala:145)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$interceptBuildException(ScalaNativePluginInternal.scala:220)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5.apply(ScalaNativePluginInternal.scala:145)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5.apply(ScalaNativePluginInternal.scala:140)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: Not a version: 11
	at scala.util.PropertiesTrait$class.parts$1(Properties.scala:176)
	at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:180)
	at scala.util.Properties$.isJavaAtLeast(Properties.scala:16)
	at scala.collection.parallel.package$.getTaskSupport(package.scala:45)
	at scala.collection.parallel.package$.<init>(package.scala:48)
	at scala.collection.parallel.package$.<clinit>(package.scala)
	at scala.collection.parallel.Combiner$class.$init$(Combiner.scala:39)
	at scala.collection.parallel.mutable.ResizableParArrayCombiner$$anon$1.<init>(ResizableParArrayCombiner.scala:90)
	at scala.collection.parallel.mutable.ResizableParArrayCombiner$.apply(ResizableParArrayCombiner.scala:90)
	at scala.collection.parallel.mutable.ResizableParArrayCombiner$.apply(ResizableParArrayCombiner.scala:92)
	at scala.collection.parallel.mutable.ParSeq$.newCombiner(ParSeq.scala:58)
	at scala.collection.mutable.SeqLike$class.parCombiner(SeqLike.scala:27)
	at scala.collection.mutable.AbstractSeq.parCombiner(Seq.scala:47)
	at scala.collection.Parallelizable$class.par(Parallelizable.scala:40)
	at scala.collection.AbstractTraversable.par(Traversable.scala:105)
	at scala.scalanative.interflow.Visit$class.visitLoop(Visit.scala:111)
	at scala.scalanative.interflow.Interflow.visitLoop(Interflow.scala:10)
	at scala.scalanative.interflow.Interflow$.apply(Interflow.scala:152)
	at scala.scalanative.build.ScalaNative$$anonfun$optimize$1.apply(ScalaNative.scala:77)
	at scala.scalanative.build.ScalaNative$$anonfun$optimize$1.apply(ScalaNative.scala:75)
	at scala.scalanative.build.Logger$class.time(Logger.scala:32)
	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
	at scala.scalanative.build.ScalaNative$.optimize(ScalaNative.scala:75)
	at scala.scalanative.build.Build$$anonfun$build$1.apply(Build.scala:57)
	at scala.scalanative.build.Build$$anonfun$build$1.apply(Build.scala:53)
	at scala.scalanative.build.Logger$class.time(Logger.scala:32)
	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
	at scala.scalanative.build.Build$.build(Build.scala:53)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5$$anonfun$apply$7.apply(ScalaNativePluginInternal.scala:145)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5$$anonfun$apply$7.apply(ScalaNativePluginInternal.scala:145)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$interceptBuildException(ScalaNativePluginInternal.scala:220)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5.apply(ScalaNativePluginInternal.scala:145)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$scalaNativeConfigSettings$5.apply(ScalaNativePluginInternal.scala:140)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (compile:nativeLink) java.lang.ExceptionInInitializerError
[error] Total time: 9 s, completed May 3, 2020, 9:13:31 AM

When building code/InputAndOutput/cstring_experiment_1 from http://media.pragprog.com/titles/rwscala/code/rwscala-code.tgz .

**Comment by errikos** [comment]
Please upgrade your project's SBT to a more recent version (e.g. 1.3.10), for it to work with Java 11.

**Comment by drocsid** [comment]
Thanks, that works. I will close...
