### ISSUE TITLE
Can't compile when call a function that used an identifier that starts from a digit

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1830]
I'm trying to use scala-native to build a software that contains a bit greek symbols inside scala code. Why? Because it is a math and to stay with original article I've used it :)

Unfortunately when I've tried compile it, everything was fine on stage of producing NIR and publishing an artifacts.

But when I've tired to compile a native binary, compiling is crashed with stack trace bellow.

To achieve that I need to call a function that is using (inside) something with unicode identifier.

At my case it was easy to fix, but if some 3rd party library would like to do so, it will be painful.

I'm using scala-native 0.4.0-M2.

BTW scalac and scala-js, both, supports it without any error.

```
[error] java.lang.StringIndexOutOfBoundsException: begin 3, end 45, length 35
[error] 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3720)
[error] 	at java.base/java.lang.String.substring(String.java:1909)
[error] 	at scala.scalanative.nir.Unmangle$Impl.readIdent(Unmangle.scala:145)
[error] 	at scala.scalanative.nir.Unmangle$Impl.readUnmangledSig(Unmangle.scala:28)
[error] 	at scala.scalanative.nir.Unmangle$.unmangleSig(Unmangle.scala:7)
[error] 	at scala.scalanative.nir.Sig.unmangled(Sig.scala:26)
[error] 	at scala.scalanative.nir.Sig.toProxy(Sig.scala:9)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachAllocation$8(Reach.scala:266)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] 	at scala.scalanative.linker.Reach.reachAllocation(Reach.scala:264)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachOp$3(Reach.scala:532)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachOp$3$adapted(Reach.scala:532)
[error] 	at scala.Option.foreach(Option.scala:407)
[error] 	at scala.scalanative.linker.Reach.reachOp(Reach.scala:532)
[error] 	at scala.scalanative.linker.Reach.reachInst(Reach.scala:474)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachInsts$1(Reach.scala:468)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachInsts$1$adapted(Reach.scala:468)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.scalanative.linker.Reach.reachInsts(Reach.scala:468)
[error] 	at scala.scalanative.linker.Reach.reachDefine(Reach.scala:397)
[error] 	at scala.scalanative.linker.Reach.reachDefn(Reach.scala:113)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachDefn$2(Reach.scala:94)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachDefn$2$adapted(Reach.scala:90)
[error] 	at scala.Option.fold(Option.scala:251)
[error] 	at scala.scalanative.linker.Reach.reachDefn(Reach.scala:90)
[error] 	at scala.scalanative.linker.Reach.process(Reach.scala:82)
[error] 	at scala.scalanative.linker.Reach$.apply(Reach.scala:673)
[error] 	at scala.scalanative.linker.Link$.$anonfun$apply$1(Link.scala:12)
[error] 	at scala.scalanative.util.Scope$.apply(Scope.scala:30)
[error] 	at scala.scalanative.linker.Link$.apply(Link.scala:11)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error] 	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error] 	at scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:55)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error] 	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:53)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$11(ScalaNativePluginInternal.scala:145)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:220)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:145)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (cliNative / Compile / nativeLink) java.lang.StringIndexOutOfBoundsException: begin 3, end 45, length 35
```

**Comment by LeeTibbert** [comment]
@catap  Thank you for reporting this & sorry that the defect took your time.

From a quick look at the stack trace you kindly provided, I can believe that it would
have problems with Unicode. 

To make it somewhat easier to reproduce, would  you be willing to post one or a few of the method names
with Greek symbols?  Name mangling, in general, tends to be sensitive to actual content of the name.
It is always useful to have actual code from the wild which does/may exhibit the reported problem.

This is meant to be a request for 5 minutes effort,  which will save hours and add confidence to a fix,
not to suck up additional hours of your time.  If it is hard to tell which method name is actually causing
the problem, just some candidates or suspicions will do, as long as I/we can tell which are hard breakers
and which suspicions.  

Again, thank you for helping improve Scala Native.

**Comment by LeeTibbert** [comment]
sjrd almost certainly does not need this info, but for those of us in the cheap seats....

Scala [documentation](https://www.scala-lang.org/files/archive/spec/2.11/01-lexical-syntax.html)
description of identifiers allows (partial specification quoted)
```
Letters, which include lower case letters (Ll), upper case letters (Lu), titlecase letters (Lt), other letters (Lo), letter numerals (Nl) and the two characters \u0024 ‘$’ and \u005F ‘_’, which both count as upper case letters.
```
Unicode Greek characters certainly qualify as Ll, Lu, etc.

**Comment by catap** [comment]
@LeeTibbert I don't promise anything but I'll try to create some example or at least determine that trigger this.

I've renamed everything and it fixed issue :)

Anyway, this code also discovered some time ago some bugs in IDEA/scalac: https://youtrack.jetbrains.com/issue/SCL-17345

**Comment by LeeTibbert** [comment]
@catap Thank you.  If it takes 5 minutes to find some old code, great. Other that than that, the base note provides a 
good description. After all, how many Greek Unicode characters are there :grin:.
I am basically looking for "Oh! I would never have thought of writing that!" (that is holes in my
imagination).

**Comment by catap** [comment]
@LeeTibbert anyway, it had a good motivation to find a cause to make renaming smaller :)

So, I did it. The crash happened on:
```
`2Δ`
```

When I'm using `Δ` or `ΔΔ` or `Δ2` everything is fine. I don't believe that unicode related to this case because the crash happened also on:
```
`2d`
```

**Comment by sjrd** [comment]
Yes, seems more like related to starting the identifier with a digit. There was a related issue in Scala.js a long time ago (https://github.com/scala-js/scala-js/issues/29).

**Comment by LeeTibbert** [comment]
@catap Given what you have discovered and reported in this Issue, would you mind 
refining the title of the issue to indicate 'initial digit' rather than Unicode?  That would
help track this issue in the proper category.
