### ISSUE TITLE
Unable to apply CFuncPtrN assigned to CStruct field

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#1850]
Reproducible test case: 
```
object Test{
  type FnCtx = CStruct1[CFuncPtr0[CInt]]
  val fn1: CFuncPtr0[CInt] = new CFuncPtr0[CInt] {
    override def apply(): CInt = 1
  }
  val x = stackalloc[FnCtx]
  x._1 = fn1
  
 fn1.apply() // This works 
 x._1.apply() //This results in scala.scalanative.runtime.UndefinedBehaviorError
 val fn = x._1 
 fn() //This also would result in UndefinedBehaviorError
```

Stacktrace for my test case
```
[info]          scala.scalanative.runtime.UndefinedBehaviorError
[info]                  at java.lang.Throwable.fillInStackTrace(Unknown Source)
[info]                  at scala.scalanative.runtime.package$.throwUndefined(Unknown Source)
[info]                  at scala.scalanative.runtime.CFuncRawPtr.apply(Unknown Source)
[info]                  at scala.scalanative.unsafe.PtrOpsSuite$$anonfun$2.apply$mcV$sp(Unknown Source)
```

Mentioned error (and stacktrace) where also observed when trying to cast `Ptr[Byte]` to `CFuncPtrN`.

**Comment by WojciechMazur** [comment]
After checking closer this issue I've found out it's not directly related to CStruct, but rather boxing `Ptr[CFuncPtr]` to `CFuncRawPtr` with current implementation of`CFuncPtrN.load` methods using `Boxes.boxToCFuncRawPtr(loadRawPtr(toRawPtr(ptr)))`   

Current implementation seems to be single-directional: it is possible to pass and execute `CFuncPtrN` defined in SN inside linked native library, however there is no possible way of executing function via provided ptr as`RawPtr` is boxed within `CFuncRawPtr` which defines `throwUndefined` for each `apply` method

New minimal reproducible example:
```
object Test {
  val fn = new CFuncPtr0[Unit] {
    override def apply(): Unit = println("hello SN!!!")
  }

  def main(args: Array[String]): Unit = {
    val ptr: RawPtr = Boxes.unboxToCFuncRawPtr(fn)
    val rawPtr: CFuncRawPtr = Boxes.boxToCFuncRawPtr(ptr)
    fn.apply() //works fine
    stdlib.atexit(fn) // if next line is commented it would corectlly execute fn upon exit
    rawPtr.apply()    //throws UndefinedBehaviourError
  }
}
```
