### ISSUE TITLE
error: typedef redefinition with different types

### ISSUE THREAD

**Issue by civilizeddev** [scala-native/scala-native#1856]
## Description

It succeeded to compile, but failed to link on Raspberry Pi.

```
error: typedef redefinition with different types
```

```
java.lang.RuntimeException: Failed to compile native library runtime code.
```

Who can point out where to fix it?

Thank you.

## Environment

- Arch: ARMv7l
- HW: Raspberry Pi 3 B+
- OS: Raspbian Buster (Debian 10)
- Scala Version: 2.11.12
- SBT Version: 1.3.13
- Java Version: Raspbian Java 11.0.7
- LLVM/Clang Version: 8

## How to reproduce

https://github.com/civilizeddev/scala-native-demo

```
$ sbt nativeLink

[info] welcome to sbt 1.3.13 (Raspbian Java 11.0.7)
[info] loading settings for project scala-pi-build from plugins.sbt ...
[info] loading project definition from /home/pi/GitHub/scala-pi/project
[info] loading settings for project scala-pi from build.sbt ...
[info] set current project to scala-pi (in build file:/home/pi/GitHub/scala-pi/)
[info] Linking (14493 ms)
[info] Discovered 585 classes and 3503 methods
[info] Optimizing (debug mode) (32091 ms)
[info] Generating intermediate code (53045 ms)
[info] Produced 4 files
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:87:3: error: redefinition of enumerator '_URC_NO_REASON'
[error]   _URC_NO_REASON = 0,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:29:3: note: previous definition is here
[error]   _URC_NO_REASON = 0,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:90:3: error: redefinition of enumerator '_URC_OK'
[error]   _URC_OK = 0, /* used by ARM EHABI */
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:30:3: note: previous definition is here
[error]   _URC_OK = 0,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:92:3: error: redefinition of enumerator '_URC_FOREIGN_EXCEPTION_CAUGHT'
[error]   _URC_FOREIGN_EXCEPTION_CAUGHT = 1,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:31:3: note: previous definition is here
[error]   _URC_FOREIGN_EXCEPTION_CAUGHT = 1,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:94:3: error: redefinition of enumerator '_URC_FATAL_PHASE2_ERROR'
[error]   _URC_FATAL_PHASE2_ERROR = 2,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:32:3: note: previous definition is here
[error]   _URC_FATAL_PHASE2_ERROR = 2,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:95:3: error: redefinition of enumerator '_URC_FATAL_PHASE1_ERROR'
[error]   _URC_FATAL_PHASE1_ERROR = 3,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:33:3: note: previous definition is here
[error]   _URC_FATAL_PHASE1_ERROR = 3,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:96:3: error: redefinition of enumerator '_URC_NORMAL_STOP'
[error]   _URC_NORMAL_STOP = 4,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:34:3: note: previous definition is here
[error]   _URC_NORMAL_STOP = 4,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:98:3: error: redefinition of enumerator '_URC_END_OF_STACK'
[error]   _URC_END_OF_STACK = 5,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:35:3: note: previous definition is here
[error]   _URC_END_OF_STACK = 5,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:99:3: error: redefinition of enumerator '_URC_HANDLER_FOUND'
[error]   _URC_HANDLER_FOUND = 6,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:36:3: note: previous definition is here
[error]   _URC_HANDLER_FOUND = 6,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:100:3: error: redefinition of enumerator '_URC_INSTALL_CONTEXT'
[error]   _URC_INSTALL_CONTEXT = 7,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:37:3: note: previous definition is here
[error]   _URC_INSTALL_CONTEXT = 7,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:101:3: error: redefinition of enumerator '_URC_CONTINUE_UNWIND'
[error]   _URC_CONTINUE_UNWIND = 8,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:38:3: note: previous definition is here
[error]   _URC_CONTINUE_UNWIND = 8,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:104:3: error: redefinition of enumerator '_URC_FAILURE'
[error]   _URC_FAILURE = 9 /* used by ARM EHABI */
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:40:3: note: previous definition is here
[error]   _URC_FAILURE = 9
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:106:3: error: typedef redefinition with different types ('enum _Unwind_Reason_Code' vs 'enum _Unwind_Reason_Code')
[error] } _Unwind_Reason_Code;
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:42:3: note: previous definition is here
[error] } _Unwind_Reason_Code;
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:109:3: error: redefinition of enumerator '_UA_SEARCH_PHASE'
[error]   _UA_SEARCH_PHASE = 1,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:45:3: note: previous definition is here
[error]   _UA_SEARCH_PHASE = 1,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:110:3: error: redefinition of enumerator '_UA_CLEANUP_PHASE'
[error]   _UA_CLEANUP_PHASE = 2,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:46:3: note: previous definition is here
[error]   _UA_CLEANUP_PHASE = 2,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:112:3: error: redefinition of enumerator '_UA_HANDLER_FRAME'
[error]   _UA_HANDLER_FRAME = 4,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:47:3: note: previous definition is here
[error]   _UA_HANDLER_FRAME = 4,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:113:3: error: redefinition of enumerator '_UA_FORCE_UNWIND'
[error]   _UA_FORCE_UNWIND = 8,
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:48:3: note: previous definition is here
[error]   _UA_FORCE_UNWIND = 8,
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:114:3: error: redefinition of enumerator '_UA_END_OF_STACK'
[error]   _UA_END_OF_STACK = 16 /* gcc extension to C++ ABI */
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:49:3: note: previous definition is here
[error]   _UA_END_OF_STACK = 16 // gcc extension to C++ ABI
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:115:3: error: typedef redefinition with different types ('enum _Unwind_Action' vs 'enum _Unwind_Action')
[error] } _Unwind_Action;
[error]   ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:50:3: note: previous definition is here
[error] } _Unwind_Action;
[error]   ^
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/UnwindLevel1-gcc-ext.c:23:
[error] In file included from /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind-EHABI.h:19:
[error] /usr/lib/llvm-8/lib/clang/8.0.0/include/unwind.h:124:8: error: redefinition of '_Unwind_Control_Block'
[error] struct _Unwind_Control_Block {
[error]        ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/include-libunwind/unwind.h:70:8: note: previous definition is here
[error] struct _Unwind_Control_Block {
[error]        ^
[error] fatal error: too many errors emitted, stopping now [-ferror-limit=]
[error] 20 errors generated.
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind_AppleExtras.cpp:85:1: error: unknown type name 'NOT_HERE_BEFORE_10_6'
[error] NOT_HERE_BEFORE_10_6(_Unwind_DeleteException)
[error] ^
[error] /home/pi/GitHub/scala-pi/target/scala-2.11/native/lib/libunwind/Unwind_AppleExtras.cpp:85:46: error: expected ';' after top level declarator
[error] NOT_HERE_BEFORE_10_6(_Unwind_DeleteException)
[error]                                              ^
[error]                                              ;
[error] 2 errors generated.
[error] java.lang.RuntimeException: Failed to compile native library runtime code.
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at scala.scalanative.build.LLVM$.$anonfun$compileNativelib$6(LLVM.scala:108)
[error] 	at scala.scalanative.build.LLVM$.$anonfun$compileNativelib$6$adapted(LLVM.scala:92)
[error] 	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:145)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] (Compile / nativeLink) Failed to compile native library runtime code.
[error] Total time: 115 s (01:55), completed Jul 16, 2020, 1:45:48 AM
```

**Comment by civilizeddev** [comment]
How to avoid definition conflicts?

### clang/lib/Headers/unwind.h

https://github.com/llvm/llvm-project/blob/294be6b5d32e1fe44d0b36cd46b2931c5f0634c4/clang/lib/Headers/unwind.h#L12-L13

```
#ifndef __CLANG_UNWIND_H
#define __CLANG_UNWIND_H
```

### nativelib/libunwind/include-libunwind/unwind.h

https://github.com/scala-native/scala-native/blob/e9cc828bc052a36d9a1d0d3481badd124753843b/nativelib/src/main/resources/libunwind/include-libunwind/unwind.h#L14-L15

**Comment by civilizeddev** [comment]
My workaround is:

### build.sbt

```
nativeCompileOptions ++= Seq("-D __CLANG_UNWIND_H")
```

But I'm not sure it's correct.

**Comment by ekrich** [comment]
This looks correct but we need to find out the underlying cause.

**Comment by ekrich** [comment]
@civilizeddev Your repo is now gone. On Raspberry Pi 4 I was able to install 64bit Ubuntu and things worked ok. If you are interested, you can run `sbt -d` for debug and all the compilation commands will be printed. Potentially, something is wrong in the link or compile commands. Can you confirm you are using `0.4.0-M2` version of Scala Native?

**Comment by civilizeddev** [comment]
My repo was private. Now I have turned it back to public.

https://github.com/civilizeddev/scala-native-demo/blob/master/project/plugins.sbt
