### ISSUE TITLE
sbt assembly crashed on mixed project

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1890]
I not sure that it is a bug, but let me report it.

When I try to run `sbt assembly` on project that is using [sbt-crossproject](https://github.com/portable-scala/sbt-crossproject) it crashed like this:
```
[error] 24 errors were encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/math/ScalaNumber.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.4.0-M2_2.11/0.4.0-M2/nativelib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/math/ScalaNumber.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ArrayRuntime.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ArrayRuntime.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/BooleanRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/BooleanRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/BoxedUnit.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/BoxedUnit.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/BoxesRunTime.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.4.0-M2_2.11/0.4.0-M2/nativelib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/BoxesRunTime.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ByteRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ByteRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/CharRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/CharRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/DoubleRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/DoubleRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/FloatRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/FloatRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/IntRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/IntRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/LongRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/LongRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ObjectRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ObjectRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ShortRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ShortRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/Statics.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/Statics.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/TraitSetter.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.4.0-M2_2.11/0.4.0-M2/nativelib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/TraitSetter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileBooleanRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileBooleanRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileByteRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileByteRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileCharRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileCharRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileDoubleRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileDoubleRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileFloatRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileFloatRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileIntRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileIntRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileLongRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileLongRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileObjectRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileObjectRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileShortRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileShortRef.class
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:143)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:68)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:58)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:244)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (bigintegerNative / assembly) deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/math/ScalaNumber.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.4.0-M2_2.11/0.4.0-M2/nativelib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/math/ScalaNumber.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ArrayRuntime.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ArrayRuntime.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/BooleanRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/BooleanRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/BoxedUnit.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/BoxedUnit.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/BoxesRunTime.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.4.0-M2_2.11/0.4.0-M2/nativelib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/BoxesRunTime.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ByteRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ByteRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/CharRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/CharRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/DoubleRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/DoubleRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/FloatRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/FloatRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/IntRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/IntRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/LongRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/LongRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ObjectRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ObjectRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/ShortRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/ShortRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/Statics.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/Statics.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/TraitSetter.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.4.0-M2_2.11/0.4.0-M2/nativelib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/TraitSetter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileBooleanRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileBooleanRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileByteRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileByteRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileCharRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileCharRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileDoubleRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileDoubleRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileFloatRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileFloatRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileIntRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileIntRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileLongRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileLongRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileObjectRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileObjectRef.class
[error] deduplicate: different file contents found in the following:
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:scala/runtime/VolatileShortRef.class
[error] /Users/catap/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.4.0-M2_2.11/0.4.0-M2/auxlib_native0.4.0-M2_2.11-0.4.0-M2.jar:scala/runtime/VolatileShortRef.class
```

I can update deduplicate filter, but it might be something deeper.

**Comment by sjrd** [comment]
You shouldn't use `assembly` on the Native part of a project. It's bound to fail in unpredictably miserable ways, because making an assembly jar makes no sense for a Native codebase (and likewise for a Scala.js codebase). Please use `theProjectJVM/assembly` instead.
