### ISSUE TITLE
Can't build scalatest's unit test via scala-2.12

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1925]
I've used 8b4e4090 to try testing support scala-2.12 on real life. I've published it locally via
```
sbt ++2.11.12 publishLocal 
sbt ++2.12.12 publishLocal 
```

After that I've switched scalatests to using `0.4.0-SNAPSHOT`. You can find code here: https://github.com/catap/scalatest/tree/scala-native-2.12

The next step is try to pass scalatest's unit test. It fails on `test:compile` with trace:
```
[error] java.nio.BufferOverflowException
[error] 	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
[error] 	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putBytes(BinarySerializer.scala:61)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putUTF8tring(BinarySerializer.scala:57)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putSig(BinarySerializer.scala:260)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putOp(BinarySerializer.scala:353)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putInst(BinarySerializer.scala:119)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$putInsts$1(BinarySerializer.scala:109)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$putInsts$1$adapted(BinarySerializer.scala:109)
[error] 	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error] 	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putSeq(BinarySerializer.scala:46)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putInsts(BinarySerializer.scala:109)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putDefn(BinarySerializer.scala:218)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$serialize$3(BinarySerializer.scala:31)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$serialize$3$adapted(BinarySerializer.scala:29)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
[error] 	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error] 	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.serialize(BinarySerializer.scala:29)
[error] 	at scala.scalanative.nir.serialization.package$.serializeBinary(package.scala:16)
[error] 	at scala.scalanative.nscplugin.NirGenFile.$anonfun$genIRFile$1(NirGenFile.scala:34)
[error] 	at scala.scalanative.nscplugin.NirGenFile.$anonfun$genIRFile$1$adapted(NirGenFile.scala:33)
[error] 	at scala.scalanative.io.package$.withScratchBuffer(package.scala:16)
[error] 	at scala.scalanative.nscplugin.NirGenFile.genIRFile(NirGenFile.scala:33)
[error] 	at scala.scalanative.nscplugin.NirGenFile.genIRFile$(NirGenFile.scala:32)
[error] 	at scala.scalanative.nscplugin.NirGenPhase.genIRFile(NirGenPhase.scala:12)
[error] 	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$7(NirGenPhase.scala:99)
[error] 	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$7$adapted(NirGenPhase.scala:97)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.foreach(ParHashMap.scala:80)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

You can reproduce it by:
```
sbt ++2.12.12 clean
sbt ++2.12.12 scalatestTestNative/test:compile
sbt ++2.12.12 scalatestTestNative/test
```

I also had modified `.jvmopts` to use `-Xmx16G` because it requires a lot of memory to build unit tests.

When I try to do it on `2.11.12` it works fine.

**Comment by WojciechMazur** [comment]
I've had similar problem before, it originated from size of allocated buffer in `ByteBufferPool` which is currently set to 5MB AFAIK, for some large files (eg. in my case #1845 files with macros could have size up to 12MB) it may not be enough. 
Most of `*.nir` files do not exceed this standard size

**Comment by sjrd** [comment]
It's a significant issue that the buffers are limited. We should make them adapt somehow.

**Comment by catap** [comment]
@WojciechMazur I also saw https://github.com/scala-native/scala-native/pull/1641

I'd love to confirm that increasing this buffer from `8` to `32` mb allows to compile scalatests.

Anyway, I don't like an idea add some magic option to tune.
