### ISSUE TITLE
Read NIR from wrong scala version

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1931]
Let assume that you have an environment that I've described at https://github.com/scala-native/scala-native/issues/1930

When you have one just run
```
env SCALANATIVE_VERSION=0.4.0-M2 sbt ++2.11.12 test
env SCALANATIVE_VERSION=0.4.0-SNAPSHOT sbt ++2.11.12 test
```
and it crashes at the second command with error:
```
[error] java.lang.AssertionError: assertion failed: Can't read binary-incompatible version of NIR.
[error] 	at scala.Predef$.assert(Predef.scala:223)
[error] 	at scala.scalanative.nir.Prelude$.readFrom(Prelude.scala:21)
[error] 	at scala.scalanative.nir.serialization.BinaryDeserializer.<init>(BinaryDeserializer.scala:17)
[error] 	at scala.scalanative.nir.serialization.package$.deserializeBinary(package.scala:19)
[error] 	at scala.scalanative.linker.ClassPath$Impl.$anonfun$load$2(ClassPath.scala:52)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at scala.scalanative.linker.ClassPath$Impl.$anonfun$load$1(ClassPath.scala:51)
[error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[error] 	at scala.scalanative.linker.ClassPath$Impl.load(ClassPath.scala:51)
[error] 	at scala.scalanative.linker.ClassLoader$FromDisk$$anonfun$load$1.applyOrElse(ClassLoader.scala:35)
[error] 	at scala.scalanative.linker.ClassLoader$FromDisk$$anonfun$load$1.applyOrElse(ClassLoader.scala:33)
[error] 	at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:148)
[error] 	at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:135)
[error] 	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
[error] 	at scala.scalanative.linker.ClassLoader$FromDisk.load(ClassLoader.scala:33)
[error] 	at scala.scalanative.linker.Reach.lookup(Reach.scala:76)
[error] 	at scala.scalanative.linker.Reach.reachDefn(Reach.scala:99)
[error] 	at scala.scalanative.linker.Reach.reachGlobalNow(Reach.scala:179)
[error] 	at scala.scalanative.linker.Reach.reachEntry(Reach.scala:140)
[error] 	at scala.scalanative.linker.Reach.reachEntry(Reach.scala:137)
[error] 	at scala.scalanative.linker.Reach.$anonfun$new$1(Reach.scala:22)
[error] 	at scala.scalanative.linker.Reach.$anonfun$new$1$adapted(Reach.scala:22)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.scalanative.linker.Reach.<init>(Reach.scala:22)
[error] 	at scala.scalanative.linker.Reach$.apply(Reach.scala:722)
[error] 	at scala.scalanative.linker.Link$.$anonfun$apply$1(Link.scala:12)
[error] 	at scala.scalanative.util.Scope$.apply(Scope.scala:30)
[error] 	at scala.scalanative.linker.Link$.apply(Link.scala:11)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error] 	at scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:57)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:54)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:136)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:213)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$6(ScalaNativePluginInternal.scala:136)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (blake3Native / Test / nativeLink) java.lang.AssertionError: assertion failed: Can't read binary-incompatible version of NIR.
``` 

As easy fix you should remove `lowered.hnir` from root project.

**Comment by sjrd** [comment]
In general you need to `clean` a project if you change the version of sbt-scalanative. There isn't really any alternative.

**Comment by catap** [comment]
@sjrd I agree but I was surprised that it tries to read this file

**Comment by ekrich** [comment]
I moved where it was generated - I'll look into the reading aspect. If it was generated in the root then that has to be left over from an older commit since M2.

**Comment by catap** [comment]
@ekrich but why removing this file help?

**Comment by ekrich** [comment]
I have no idea sorry. They are only dumped for inspection as far as I can tell.

**Comment by catap** [comment]
@eatkins I've created a branch https://github.com/catap/scala-native/tree/frankenstein that contains https://github.com/scala-native/scala-native/pull/1929 and https://github.com/scala-native/scala-native/pull/1927

On this code I had this error:
```
➜  blake3 git:(master) env SCALANATIVE_VERSION=0.4.0-M2 sbt ++2.11.12 blake3Native/test
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_192)
[info] loading global plugins from /Users/catap/.sbt/1.0/plugins
[info] loading settings for project blake3-build from plugins.sbt ...
[info] loading project definition from /Users/catap/Documents/OpenSource/blake3/project
[info] loading settings for project blake3 from build.sbt ...
[info] set current project to blake3 (in build file:/Users/catap/Documents/OpenSource/blake3/)
[info] Setting Scala version to 2.11.12 on 5 projects.
[info] Reapplying settings...
[info] set current project to blake3 (in build file:/Users/catap/Documents/OpenSource/blake3/)
[info] Compiling 8 Scala sources to /Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/classes ...
[info] Compiling 3 Scala sources to /Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/test-classes ...
[info] Compiling 1 Scala source to /Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/test-classes ...
[info] Linking (1529 ms)
[info] Discovered 2159 classes and 14978 methods
[info] Optimizing (debug mode) (2718 ms)
[info] Generating intermediate code (3053 ms)
[info] Produced 12 files
[info] Compiling to native code (2605 ms)
[info] Linking native code (immix gc, none lto) (301 ms)
[info] Total (10607 ms)
[info] Starting process '/Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/blake3-out' on port '57132'.
[info] Blake3TestVectors:
[info] - Test vectors work as expected
[info] Blake3Test:
[info] - Very naive test
[info] - A bit more complicated test
[info] - Update from specified position
[info] - Done to specified position
[info] - High level string works as low level bytes
[info] - Output encoding works
[info] - Zero done
[info] Incorrect input reported
[info] - when wrong key length on Blake3.newKeyedHasher
[info] - when wrong key length on Hasher#doneBigInt
[info] - when wrong key length on Hasher#doneHex
[info] RFC4648Test:
[info] - base16 works on test vector
[info] - base32 works on test vector
[info] - base32_hex works on test vector
[info] - base64 works on test vector
[info] - base64_url works on test vector
[info] Run completed in 1 second, 595 milliseconds.
[info] Total number of tests run: 16
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 16, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 21 s, completed Oct 8, 2020 8:21:43 PM
➜  blake3 git:(master) env SCALANATIVE_VERSION=0.4.0-SNAPSHOT sbt ++2.12.12 blake3Native/test
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_192)
[info] loading global plugins from /Users/catap/.sbt/1.0/plugins
[info] loading settings for project blake3-build from plugins.sbt ...
[info] loading project definition from /Users/catap/Documents/OpenSource/blake3/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] loading settings for project blake3 from build.sbt ...
[info] set current project to blake3 (in build file:/Users/catap/Documents/OpenSource/blake3/)
[info] Setting Scala version to 2.12.12 on 4 projects.
[info] Excluded 1 projects, run ++ 2.12.12 -v for more details.
[info] Reapplying settings...
[info] set current project to blake3 (in build file:/Users/catap/Documents/OpenSource/blake3/)
[info] Compiling 8 Scala sources to /Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/classes ...
[info] Compiling 3 Scala sources to /Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/test-classes ...
[error] java.lang.AssertionError: assertion failed: Can't read binary-incompatible version of NIR from 'file:/Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/test-classes/TestMain$.nir' (expected compat=5, got 4; expected revision=8, got 6).
[error] 	at scala.Predef$.assert(Predef.scala:223)
[error] 	at scala.scalanative.nir.Prelude$.readFrom(Prelude.scala:25)
[error] 	at scala.scalanative.nir.serialization.BinaryDeserializer.<init>(BinaryDeserializer.scala:23)
[error] 	at scala.scalanative.nir.serialization.package$.$anonfun$deserializeBinary$1(package.scala:27)
[error] 	at scala.scalanative.nir.serialization.package$.withBigEndian(package.scala:18)
[error] 	at scala.scalanative.nir.serialization.package$.deserializeBinary(package.scala:27)
[error] 	at scala.scalanative.linker.ClassPath$Impl.$anonfun$load$2(ClassPath.scala:58)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at scala.scalanative.linker.ClassPath$Impl.$anonfun$load$1(ClassPath.scala:56)
[error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[error] 	at scala.scalanative.linker.ClassPath$Impl.load(ClassPath.scala:56)
[error] 	at scala.scalanative.linker.ClassLoader$FromDisk$$anonfun$load$1.applyOrElse(ClassLoader.scala:35)
[error] 	at scala.scalanative.linker.ClassLoader$FromDisk$$anonfun$load$1.applyOrElse(ClassLoader.scala:33)
[error] 	at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:148)
[error] 	at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:135)
[error] 	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
[error] 	at scala.scalanative.linker.ClassLoader$FromDisk.load(ClassLoader.scala:33)
[error] 	at scala.scalanative.linker.Reach.lookup(Reach.scala:76)
[error] 	at scala.scalanative.linker.Reach.reachDefn(Reach.scala:99)
[error] 	at scala.scalanative.linker.Reach.reachGlobalNow(Reach.scala:179)
[error] 	at scala.scalanative.linker.Reach.reachEntry(Reach.scala:140)
[error] 	at scala.scalanative.linker.Reach.reachEntry(Reach.scala:137)
[error] 	at scala.scalanative.linker.Reach.$anonfun$new$1(Reach.scala:22)
[error] 	at scala.scalanative.linker.Reach.$anonfun$new$1$adapted(Reach.scala:22)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.scalanative.linker.Reach.<init>(Reach.scala:22)
[error] 	at scala.scalanative.linker.Reach$.apply(Reach.scala:729)
[error] 	at scala.scalanative.linker.Link$.$anonfun$apply$1(Link.scala:12)
[error] 	at scala.scalanative.util.Scope$.apply(Scope.scala:30)
[error] 	at scala.scalanative.linker.Link$.apply(Link.scala:11)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error] 	at scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:57)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:54)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:136)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:213)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$6(ScalaNativePluginInternal.scala:136)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (blake3Native / Test / nativeLink) java.lang.AssertionError: assertion failed: Can't read binary-incompatible version of NIR from 'file:/Users/catap/Documents/OpenSource/blake3/native/target/scala-2.11/test-classes/TestMain$.nir' (expected compat=5, got 4; expected revision=8, got 6).
[error] Total time: 8 s, completed Oct 8, 2020 8:23:34 PM
➜  blake3 git:(master)
```

I was definitely wrong and it doesn't read `lowered.hnir`. Anyway, it tries to read `nir` from `2.11` when I'm asking to build `2.12`.

I feel that it is wrong behaviour.

**Comment by ekrich** [comment]
@catap I am not sure what this is doing but `env SCALANATIVE_VERSION=0.4.0-M2` is not correct. 

The current HEAD version is `0.4.0-SNAPSHOT`. The `nir` and code should go in `target/scala-2.11` and `target/scala-2.12` and should not conflict with each other. The `nir` from `0.4.0-M2` and `0.4.0-SNAPSHOT` that has `2.12` support is not compatible.

If you run `+sandbox/run` it should compile and run both versions.

**Comment by catap** [comment]
@ekrich I'm doing this outside of scala-native repository and `SCALANATIVE_VERSION` is using to setup a correct version of `sbt-scala-native`.

I expect that `sbt ++2.12.12 [something]` won't use NIR or any file from  `target/scala-2.11` and uses only `target/scala-2.12`. Am I wrong?

**Comment by ekrich** [comment]
You would need to build and `+publishLocal` and then use `0.4.0-SNAPSHOT` to use `2.12` at all.

**Comment by catap** [comment]
@ekrich you're right, the issue was in my code.
