### ISSUE TITLE
org.scalactic.anyvals.NonZeroFloat cannot be cast to java.lang.Float on 2.12

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1950]
As part of https://github.com/scalatest/scalatest/pull/1902 was discovered that scalatests' tests doesn't pass on scala-native-2.12.

How to reproduce:
 - go to master of SN and run `sbt +publishLocal`
 - after that you need scalatests from this PR: https://github.com/scalatest/scalatest/pull/1902

As soon as you got it just run:
```
sbt ++2.11.12 scalatestTestNative/test
```

and everything is fine. But when you run
```
sbt ++2.12.12 scalatestTestNative/test
```
some tests are failed with error like:
```
[info]   - returns the default implicit generator that produces arbitrary NonZeroFloats *** FAILED *** (18 milliseconds)
[info]     java.lang.ClassCastException: org.scalactic.anyvals.NonZeroFloat cannot be cast to java.lang.Float
[info]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
[info]     at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
[info]     at scala.runtime.BoxesRunTime$.unboxToFloat(Unknown Source)
[info]     at org.scalatest.prop.CommonGenerators$$Lambda$29.apply(Unknown Source)
[info]     at scala.collection.immutable.List.map(Unknown Source)
[info]     at org.scalatest.prop.Generator$$anon$1.initEdges(Unknown Source)
[info]     at org.scalatest.prop.CommonGeneratorsSpec.$anonfun$new$950(Unknown Source)
[info]     at org.scalatest.prop.CommonGeneratorsSpec$$Lambda$837.apply(Unknown Source)
```

**Comment by LeeTibbert** [comment]
@catap  Thank you for reporting this.    The first step in getting this resolved is replicating
the report. That is not to say that you are not seeing what you report, just establishing a 
baseline, so the Big Dogs can take over and work efficiently.

Because, as we have discussed, we both would like to see ScalaTest running on 0.next
as soon as feasible, let me see if I can help define the problem.

Using scastie, the web console, both scala 2.12 and 2.13  gives me the data below.
The declaration of NonZeroFloat is from ScalaTest sources, with the body omitted.
Close enough, I think, for this rapid debugging.
```
final class NonZeroFloat  (val value: Float) extends AnyVal {}
val nf1 = new NonZeroFloat(2.5F)
val sn1 = nf1.asInstanceOf[Float]
java.lang.ClassCastException: Playground$NonZeroFloat cannot be cast to java.lang.Float
	at scala.runtime.BoxesRunTime.unboxToFloat(BoxesRunTime.java:111)
```

I am not sure if Scastie is JVM or Scala.Js so I tried with sbt console, which I know to be JVM.
Scala 2.12 on java 8 gives:
```
info] Starting scala interpreter...
Welcome to Scala 2.12.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_265).
Type in expressions for evaluation. Or try :help.

scala> final class NonZeroFloat  (val value: Float) extends AnyVal {}
defined class NonZeroFloat

scala> val nf1 = new NonZeroFloat(2.5F)
nf1: NonZeroFloat = NonZeroFloat@40200000

scala> val sn1 = nf1.asInstanceOf[Float]
java.lang.ClassCastException: NonZeroFloat cannot be cast to java.lang.Float
  at scala.runtime.BoxesRunTime.unboxToFloat(BoxesRunTime.java:111)
  ... 36 elided
```
Scala 2.11.12 JVM gives similar results:
```
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_265).
Type in expressions for evaluation. Or try :help.

scala> final class NonZeroFloat  (val value: Float) extends AnyVal {}
defined class NonZeroFloat

scala> val nf1 = new NonZeroFloat(2.5F)
nf1: NonZeroFloat = NonZeroFloat@40200000

scala> val sn1 = nf1.asInstanceOf[Float]
java.lang.ClassCastException: NonZeroFloat cannot be cast to java.lang.Float
  at scala.runtime.BoxesRunTime.unboxToFloat(BoxesRunTime.java:109)
  ... 40 elided
```
Can you replicate these results? 

I do not dig deep enough to see if scalastic (?) is using asInstanceOf[Float] or doing
the cast another way. I also saw the scary word "macro".  Hey, Halloween is coming, 
maybe "macro" is good for a fright!

Now, I did not try this on Scala Native  2.11-SNAPSHOT.   I can do that if you want.
If it works, it is surely a bug.  Perhaps some ScalaTest tests are running on ScalaNative when
they should be JVM only?  A shot in the dark.

Am I missing something here?  

If I am not off-base and if you can replicate my results, I think the next step is diving into the
Scalactic/ScalaTest code and seeing how they do the cast. Devil is in the details.

**Comment by LeeTibbert** [comment]
Later:  I looked around in NonZeroFloat and NonZeroFloat.toFloat uses entirely reasonable code.  I am not being coy in my wording,m I do not want to  post too much ScalaTest code here, without permission.

So, after a rest, and pecking away at the j.u.HashMap PR that I am working on, I will take a look at the ScalaTest Issue there
and see if I can trace a log file to understand their usage.  One hand washes the other.

**Comment by catap** [comment]
@LeeTibbert I'm using master

Let me quote some test session that I performed on my scalatests branch and SN's c19906cb9:
```
➜  scalatest git:(scala-native-2.12) ✗ sbt ++2.11.12 "project scalatestNative" scalatestTestNative/test
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 11.0.8)
[info] loading global plugins from /Users/catap/.sbt/1.0/plugins
[info] loading settings for project scalatest-build from plugins.sbt,build.sbt ...
[info] loading project definition from /Users/catap/Documents/OpenSource/scalatest/project
[info] loading settings for project root from build.sbt ...
[info] resolving key references (88917 settings) ...
[info] set current project to root (in build file:/Users/catap/Documents/OpenSource/scalatest/)
[info] Setting Scala version to 2.11.12 on 122 projects.
[info] Excluded 3 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] set current project to root (in build file:/Users/catap/Documents/OpenSource/scalatest/)
[info] set current project to scalatestNative (in build file:/Users/catap/Documents/OpenSource/scalatest/)
....
[info] ScalaTest
[info] Run completed in 1 minute, 13 seconds.
[info] Total number of tests run: 7533
[info] Suites: completed 212, aborted 0
[info] Tests: succeeded 7533, failed 0, canceled 2, ignored 11, pending 2
[info] All tests passed.
[info] Passed: Total 7533, Failed 0, Errors 0, Passed 7533, Ignored 11, Canceled 2, Pending 2
[success] Total time: 252 s (04:12), completed 15 Oct 2020, 00:34:49
➜  scalatest git:(scala-native-2.12) ✗ sbt ++2.12.12 "project scalatestNative" scalatestTestNative/test
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 11.0.8)
[info] loading global plugins from /Users/catap/.sbt/1.0/plugins
[info] loading settings for project scalatest-build from plugins.sbt,build.sbt ...
[info] loading project definition from /Users/catap/Documents/OpenSource/scalatest/project
[info] loading settings for project root from build.sbt ...
[info] resolving key references (88917 settings) ...
[info] set current project to root (in build file:/Users/catap/Documents/OpenSource/scalatest/)
[info] Setting Scala version to 2.12.12 on 125 projects.
[info] Reapplying settings...
[info] set current project to root (in build file:/Users/catap/Documents/OpenSource/scalatest/)
[info] set current project to scalatestNative (in build file:/Users/catap/Documents/OpenSource/scalatest/)
....
[info] ScalaTest
[info] Run completed in 1 minute, 7 seconds.
[info] Total number of tests run: 7533
[info] Suites: completed 212, aborted 0
[info] Tests: succeeded 7294, failed 239, canceled 2, ignored 11, pending 2
[info] *** 239 TESTS FAILED ***
[error] Failed: Total 7533, Failed 239, Errors 0, Passed 7294, Ignored 11, Canceled 2, Pending 2
[error] Failed tests:
[error] 	org.scalatest.enablers.PropCheckerAssertingAsyncSpec
[error] 	org.scalatest.prop.ConfigurationSpec
[error] 	org.scalatest.prop.SizeParamSpec
[error] 	org.scalatest.prop.GeneratorSpec
[error] 	org.scalatest.prop.CommonGeneratorsSpec
[error] 	org.scalatest.enablers.PropCheckerAssertingSpec
[error] 	org.scalatest.prop.ClassificationSpec
[error] 	org.scalatest.prop.OrgScalaTestPropSpec
[error] (scalatestTestNative / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 222 s (03:42), completed 15 Oct 2020, 00:39:07
```

It looks a bug, isn't it?

**Comment by LeeTibbert** [comment]
Hey 239 failures out of 7533 tests is only a little over three percent.  Tiny, you call that a bug ;-)

The log file helps, thank you.  Sure looks like a bug, just a question of where, keeping in mind that end
users do not especially care where.   Good that you caught this.

I will take a run, probably tomorrow (Thurs) when I am fresh, at replicating your steps; probably starting with
JDK 8 and working my way up.

**Comment by cheeseng** [comment]
@catap @LeeTibbert When I last checked, both 2.11.12 and 2.12.12 had the same problem when built with 0.4.0-SNAPSHOT that I published locally (using latest master).  Please note that the problem did not happen when built with 0.4.0-M2, and all scalatest tests passed (We reached 0!).  There are failing tests under scalactic tests, but I think they are separate problem.

**Comment by WojciechMazur** [comment]
I think I've found easy reproducible example: 
```
    final class NonZeroFloat(val value: Float) extends AnyVal
    val z = List(new NonZeroFloat(1.0f)).map(_.value)
    println(z)
```
Getting into solving this one

**Comment by sjrd** [comment]
The problem is probably in `genFunction` around https://github.com/scala-native/scala-native/blob/27917353756ac3d91906df713e0606d0d7a9e4e0/nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenExpr.scala#L700
