### ISSUE TITLE
Tests do not compile with releaseFull mode

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#1976]
When trying to run tests with mode `releaseFull` build fails in Interflow when merging two States.
Problem occurred in build with commit sha `c375b432fe8e600f7ad3a201f6c516892e7b681b` for Scala 2.12

Top of stack trace:
```
java.util.NoSuchElementException: key not found: 110001
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
	at scala.scalanative.interflow.State.$anonfun$inherit$1(State.scala:136)
	at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:23)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.scalanative.interflow.State.inherit(State.scala:135)
	at scala.scalanative.interflow.Inline.$anonfun$inline$1(Inline.scala:204)
	at scala.scalanative.interflow.Log.in(Log.scala:15)
	at scala.scalanative.interflow.Log.in$(Log.scala:8)
	at scala.scalanative.interflow.Interflow.in(Interflow.scala:10)
	at scala.scalanative.interflow.Inline.inline(Inline.scala:134)
	at scala.scalanative.interflow.Inline.inline$(Inline.scala:131)
	at scala.scalanative.interflow.Interflow.inline(Interflow.scala:10)
	at scala.scalanative.interflow.Eval.nonIntrinsic$1(Eval.scala:144)
	at scala.scalanative.interflow.Eval.eval(Eval.scala:158)
	at scala.scalanative.interflow.Eval.eval$(Eval.scala:102)
	at scala.scalanative.interflow.Interflow.eval(Interflow.scala:10)
	at scala.scalanative.interflow.Eval.run(Eval.scala:29)
	at scala.scalanative.interflow.Eval.run$(Eval.scala:11)
	at scala.scalanative.interflow.Interflow.run(Interflow.scala:10)
	at scala.scalanative.interflow.MergeProcessor.visit(MergeProcessor.scala:365)
	at scala.scalanative.interflow.MergeProcessor.advance(MergeProcessor.scala:382)
	at scala.scalanative.interflow.Opt.process(Opt.scala:120)
	at scala.scalanative.interflow.Opt.process$(Opt.scala:107)
	at scala.scalanative.interflow.Interflow.process(Interflow.scala:10)
```

**Comment by LeeTibbert** [comment]
The base note is progress.  ReleaseFull used to either blow up for lack of memory or go into an infinite loop.
Looks like it is responding well to the love it has been shown recently.

Cold comfort, agreed.

**Comment by WojciechMazur** [comment]
@LeeTibbert I've not seen any infinite loops when working on the fix however waiting for results takes a lot, ~51m in unit tests, lack of output from this task, my look like an infinite loop. However, if you have some code example that may cause such loops I'd be happy to investigate it.
