### ISSUE TITLE
nativeLink is flaky with (error: java.nio.file.ClosedFileSystemException)

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2024]
Let's set the scene:

Build: https://travis-ci.com/github/keynmol/repro-scala-native-1
Minimal(?) repro: https://github.com/keynmol/repro-scala-native-1

Both my machine and the travis I used are debian-based.

Worst thing is, sometimes it succeeds (at different rates):

```
// run nativeLink 20 times
➜  scala-native-closed-filesystem git:(master) ✗ repeat 20 sbtn ';clean;nativeLink' >> output
➜  scala-native-closed-filesystem git:(master) ✗ cat output | ack 'ClosedFileSystemException|success'
[success] Total time: 5 s, completed Nov 19, 2020 6:57:56 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 4 s, completed Nov 19, 2020 6:58:26 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
```

Error:

```
[error] java.nio.file.ClosedFileSystemException
[error]         at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1103)
[error]         at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:324)
[error]         at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
[error]         at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
```

<details><summary>Full stacktrace</summary>

```
➜  scala-native-closed-filesystem git:(master) ✗ sbtn 'last app / Compile / nativeLink'              
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> last app / Compile / nativeLink
[error] java.nio.file.ClosedFileSystemException
[error]         at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1103)
[error]         at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:324)
[error]         at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
[error]         at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
[error]         at java.nio.file.Files.readAttributes(Files.java:1737)
[error]         at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
[error]         at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[error]         at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
[error]         at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
[error]         at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
[error]         at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
[error]         at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
[error]         at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
[error]         at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:170)
[error]         at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
[error]         at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[error]         at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
[error]         at scala.collection.Iterator.toStream(Iterator.scala:1417)
[error]         at scala.collection.Iterator.toStream$(Iterator.scala:1416)
[error]         at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
[error]         at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1417)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.immutable.Stream.$anonfun$append$1(Stream.scala:255)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1260)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.generic.Growable.loop$1(Growable.scala:57)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error]         at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:583)
[error]         at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:533)
[error]         at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:354)
[error]         at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:352)
[error]         at scala.collection.AbstractTraversable.toMap(Traversable.scala:108)
[error]         at scala.scalanative.linker.ClassPath$Impl.<init>(ClassPath.scala:39)
[error]         at scala.scalanative.linker.ClassPath$.apply(ClassPath.scala:28)
[error]         at scala.scalanative.linker.ClassLoader$.$anonfun$fromDisk$1(ClassLoader.scala:17)
[error]         at scala.collection.immutable.List.map(List.scala:297)
[error]         at scala.scalanative.linker.ClassLoader$.fromDisk(ClassLoader.scala:16)
[error]         at scala.scalanative.linker.Link$.$anonfun$apply$1(Link.scala:12)
[error]         at scala.scalanative.util.Scope$.apply(Scope.scala:30)
[error]         at scala.scalanative.linker.Link$.apply(Link.scala:11)
[error]         at scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
[error]         at scala.scalanative.build.Logger.time(Logger.scala:32)
[error]         at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error]         at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error]         at scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:34)
[error]         at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:55)
[error]         at scala.scalanative.build.Logger.time(Logger.scala:32)
[error]         at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error]         at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error]         at scala.scalanative.build.Build$.build(Build.scala:53)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$11(ScalaNativePluginInternal.scala:145)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:220)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:145)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[info] last app / Compile / nativeLink completed
```
</details>

**Comment by LeeTibbert** [comment]
@keynmol Sorry that you are experiencing a problem. Thank you for this issue and 
carefully presented backing information.

This Issue is the continuation of a gitter conversation that, I feared, was exceeding
the "My Eyes Glaze Over" limit for other readers.

For those following along, the SBT version is 1.4.3. The problem was originally
experienced with SN 0.3.9 but reproduces, by report, with the 0.4.0-M2 in the reproducing
repository. From the 0.4.0-M2, I infer the scala version to be 2.11.12.

The log file from the last successful build of the sbt-matrix (sp?) project used sbt 2.12.?.

When I try to reproduce, probably the first thing I will do is drop back to sbt 1.4.2.

**Comment by keynmol** [comment]
I checked with SBT 1.4.2 - seems to be the same:

```
➜  scala-native-closed-filesystem git:(master) ✗ sbtn sbtVersion                                           
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> sbtVersion
[info] core / sbtVersion
[info]  1.4.2
[info] app / sbtVersion
[info]  1.4.2
[info] sbtVersion
[info]  1.4.2
[info] sbtVersion completed
[success] Total time: 0 s, completed Nov 19, 2020 7:51:46 PM
➜  scala-native-closed-filesystem git:(master) ✗ repeat 20 sbtn ';clean;nativeLink' >> output_1.4.2
➜  scala-native-closed-filesystem git:(master) ✗ cat output_1.4.2 | ack 'ClosedFileSystemException|success'
[success] Total time: 5 s, completed Nov 19, 2020 7:52:42 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 5 s, completed Nov 19, 2020 7:52:50 PM
[success] Total time: 5 s, completed Nov 19, 2020 7:52:55 PM
[success] Total time: 5 s, completed Nov 19, 2020 7:53:00 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 5 s, completed Nov 19, 2020 7:53:12 PM
[success] Total time: 5 s, completed Nov 19, 2020 7:53:17 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 5 s, completed Nov 19, 2020 7:53:25 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 5 s, completed Nov 19, 2020 7:53:32 PM
[success] Total time: 4 s, completed Nov 19, 2020 7:53:37 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 4 s, completed Nov 19, 2020 7:53:43 PM
[success] Total time: 4 s, completed Nov 19, 2020 7:53:48 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 4 s, completed Nov 19, 2020 7:53:55 PM
[success] Total time: 4 s, completed Nov 19, 2020 7:53:59 PM
```

Re: Scala version - I thought there's no 0.4.0-M2 for 2.12? 

The successful build of projectmatrix also uses 2.11.12: https://travis-ci.org/github/sbt/sbt-projectmatrix/builds/720520608#L830

The flakiness I see might suggest that it's just fluke that those builds worked before..

**Comment by LeeTibbert** [comment]
Scala 2.12/2.13 support requires a recent 0.4.0-SNAPSHOT, sorry if I mislead.

**Comment by LeeTibbert** [comment]
@keynmol  The Issue gets to be more fun.  How I love intermittents!

I copied over a .zip of the reproducer you kindly supplied.
I then cleaned my environment (~/.ivy2/local, ~/.cache/coursier/v1),
expanded the zip, and ran the project.  I could not replicate.
My first attempt was using Java 11. My second, after a round of
cleaning, was with Java 8.  The silly thing insisted on succeeding.

Given your report that this was intermittent, not deterministic,
I then did 5 or 6 runs of Java 8 and each was a success.

My inability to replicate does not mean that you do not have a problem,
just that I have not been cleaver enough to replicate.

I think the next step, after a rest, is to copy down the sbt-matrix
repository and see if I can replicate.

I __think__ that the zip failure comes from something in the code
trying to open a .jar file.  Either the file is not on the path, or is in 
a projectRoot/lib directory or the number of allowable open files
on the system has been exceeded or it is just out to bring misery
to our lives.

**Comment by keynmol** [comment]
> I think the next step, after a rest, is to copy down the sbt-matrix
> repository and see if I can replicate.

I should've clarified (my fault) - the failed build I've linked is for the actual reproducing repository: https://travis-ci.com/github/keynmol/repro-scala-native-1 without any projectmatrix, and it still fails with the same thing. Is this crazy? :D

Which makes it, I think, not a projectmatrix issue - the repo in question doesn't use any of it. Which makes it even more bizarre.

When I switched to sbt 1.4.2 my firs builds reported several successes in a row and then it all came crashing down.

**Comment by keynmol** [comment]
I also squinted at Java versions, but the Travis worker is on 

```
openjdk version "1.8.0_252"

OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)

OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

and my local machine is 

```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
```

Next step might be trying to build a docker image that reproduces this?.. I'm out of ideas

**Comment by LeeTibbert** [comment]
> Next step might be trying to build a docker image that reproduces this?.. I'm out of ideas  

A docker image which reporduces the problem sounds like a good next step, if/when you 
get a chance.  That might get us beyond "It fails there; it works here".

Another idea is that there is supposed to be a linux utility or such which reports
file opens & closes in a process.  I forget its name but seem to remember
having used it for debugging.  That might show us what file the  app is
trying to open.

I think there is another utility that reports how many open files a process has.
I think that SN keep 300 or so open for dependencies and just the sheer joy
of it.   Might be worthwhile to see if the process is approaching or surpassing
1024. Slow closes, etc. 

I'll study the failing log file, especially from your repo directory & Travis CI
tomorrow or so...

**Comment by ekrich** [comment]
What happens if you don't use the experimental thin `sbt` client?

**Comment by keynmol** [comment]
@ekrich so I tested that with SBT 1.3.8, it doesn't support thin client so I just did 

```
$ repeat 20 sbt ';clean;nativeLink' >> output_1.3.8
```

And there was more noise because of SBT startup, but same results:

```
➜  scala-native-closed-filesystem git:(master) ✗ cat output_1.3.8 | ack 'ClosedFileSystemException|success'
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 1 s, completed 19-Nov-2020 19:16:09
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 1 s, completed 19-Nov-2020 19:16:11
[success] Total time: 0 s, completed 19-Nov-2020 19:16:12
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:16:31
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:16:32
[success] Total time: 0 s, completed 19-Nov-2020 19:16:33
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:16:47
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:16:47
[success] Total time: 0 s, completed 19-Nov-2020 19:16:48
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:01
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:01
[success] Total time: 0 s, completed 19-Nov-2020 19:17:02
[success] Total time: 9 s, completed 19-Nov-2020 19:17:11
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:16
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:16
[success] Total time: 0 s, completed 19-Nov-2020 19:17:17
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:29
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:30
[success] Total time: 0 s, completed 19-Nov-2020 19:17:31
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:43
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:43
[success] Total time: 0 s, completed 19-Nov-2020 19:17:44
[error] java.nio.file.ClosedFileSystemException
[error] (core / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:56
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:17:56
[success] Total time: 0 s, completed 19-Nov-2020 19:17:57
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:18:09
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:18:09
[success] Total time: 0 s, completed 19-Nov-2020 19:18:10
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:18:22
[success] Generated .bloop/scala-native-closed-filesystem-build.json
[success] Total time: 0 s, completed 19-Nov-2020 19:18:22
[success] Total time: 0 s, completed 19-Nov-2020 19:18:23
[error] java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Generated .bloop/scala-native-closed-filesystem-build-build.json

...
```

**Comment by keynmol** [comment]
I'll try to do good on my promise and setup the docker image - gladly all the dependencies are pulled from a script hosted by the scala-native's repo itself: https://github.com/scala-native/scala-native/blob/master/scripts/travis_setup.sh

So it should be easy to just copypaste :)

**Comment by keynmol** [comment]
Right @ekrich and @LeeTibbert if you fancy proving that I'm not going mad, I've built a docker image and pushed it on docker hub.

To reproduce:

```bash
# code
git clone https://github.com/keynmol/repro-scala-native-1.git
cd repro-scala-native-1

# Run in a docker container
docker run -v $(pwd):/src -it keynmol/scala-native-repro-nio bash -c "sbt ';clean;nativeLink' && sbt ';clean;nativeLink' && sbt ';clean;nativeLink'"
```

(running sbt 3 times for good measure)

And the dockerfile almost mirrors the travis_setup script from scala native, with the exception of clang version - but I could still reproduce it locally even on that.

https://github.com/keynmol/repro-scala-native-1/blob/master/Dockerfile

**Comment by ekrich** [comment]
I think this is a sbt `1.4.3` problem. They just upgraded - no problems before.
```
[error] stack trace is suppressed; run last compat211Native / Test / nativeLink for the full output
[error] (compat211Native / Test / nativeLink) java.nio.file.ClosedFileSystemException
[error] Total time: 135 s (02:15), completed Nov 20, 2020 6:28:25 PM
sbt:scala-collection-compat> last compat211Native / Test / nativeLink
[error] java.nio.file.ClosedFileSystemException
[error] 	at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1084)
[error] 	at com.sun.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:633)
[error] 	at com.sun.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:739)
[error] 	at com.sun.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:255)
[error] 	at java.nio.file.Files.newByteChannel(Files.java:361)
[error] 	at java.nio.file.Files.newByteChannel(Files.java:407)
```

**Comment by LeeTibbert** [comment]
@ekrich Ah!  That is where I saw it!  Thank you!  I had been racking my brain...
I had done an experimental Sbt 1.4.3 build as part of my usual PR to upgrade
when sbt upgrades. A poor person's scala-steward (a task for another day).
I seem to remember getting the error above and backing off.

**Comment by keynmol** [comment]
Don't know folks, I've dropped SBT to 1.3.13 on my reproduction repo and [same thing happened](https://travis-ci.com/github/keynmol/repro-scala-native-1/builds/204777294)

I'd like to keep this open in case someone else hits this same problem, or if someone has an epiphany

**Comment by LeeTibbert** [comment]
@keynmol   Are you still seeing this problem with Sbt 1.4.4?   I have been running with that in
private builds for several days now and have not seen this (where I had before on sbt 1.4.3).
That is just one data point.

**Comment by keynmol** [comment]
Yep, I'm seeing this with 1.4.4, 1.4.2 and 1.3.13, so does Travis.

I think @WojciechMazur proved that it's an actual problem with multiple modules all of which link. If that's the case, I'll try to publish SN locally and see if it helps

**Comment by WojciechMazur** [comment]
@keynmol  I've tested it on your repo project. I've tried to build it 5 times in a row, and get no exception.

**Comment by keynmol** [comment]
I can confirm as well that you nailed it :+1: I've modified repro to pick up the version and published your branch locally

```
➜  scala-native-closed-filesystem git:(master) ✗ SCALA_NATIVE_VERSION=0.4.0-M2 sbt ';clean;nativeLink' | tail -n5
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] Total time: 7 s, completed 28-Nov-2020 18:19:29

➜  scala-native-closed-filesystem git:(master) ✗ SCALA_NATIVE_VERSION=0.4.0-SNAPSHOT sbt ';clean;nativeLink' | tail -n5
[info] Total (7908 ms)
[info] Compiling to native code (2376 ms)
[info] Linking native code (immix gc, none lto) (116 ms)
[info] Total (8569 ms)
[success] Total time: 12 s, completed 28-Nov-2020 18:19:54
```

**Comment by armanbilge** [comment]
I am continuing to see this flake fairly regularly :(

https://github.com/typelevel/fs2/actions/runs/3119666907/jobs/5059771326#step:10:83

```
[info] Starting process '/home/runner/work/fs2/fs2/io/native/target/scala-2.12/fs2-io-test-out' on port '37861'.
[error] java.nio.file.ClosedFileSystemException
[error] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1628)
[error] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:971)
[error] 	at jdk.zipfs/jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:864)
[error] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:238)
[error] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
[error] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
[error] 	at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
[error] 	at scala.scalanative.io.VirtualDirectory$NioDirectory.read(VirtualDirectory.scala:87)
[error] 	at scala.scalanative.io.VirtualDirectory$NioDirectory.read$(VirtualDirectory.scala:86)
[error] 	at scala.scalanative.io.VirtualDirectory$JarDirectory.read(VirtualDirectory.scala:152)
[error] 	at scala.scalanative.linker.ClassPath$Impl.$anonfun$load$2(ClassPath.scala:59)
```

**Comment by armanbilge** [comment]
So across an entire org of projects cross-compiling for Scala Native, only FS2 shows that problem. The only thing unique about the FS2 build is that it uses the embedded resources functionality. So I wonder if that is related.

**Comment by armanbilge** [comment]
Update on this: after disabling embedded resources in the FS2 build in https://github.com/typelevel/fs2/pull/3056 the problem has gone away. So seems like it's related to that.

**Comment by rolang** [comment]
Hi, I encountered the same issue recently. It kept failing in GitHub actions CI like in this [job run](https://github.com/rolang/dumbo/actions/runs/6989297519/job/19017700040) most of the time, using sbt `1.9.7` + scala native `0.4.16`.

I was not able to reproduce it locally. So I tried to reproduce the GitHub Actions environment using docker image builds from [catthehacker/docker_images](https://github.com/catthehacker/docker_images). Ended up with building an image from that as it had no `clang` installed: 
```
FROM ghcr.io/catthehacker/ubuntu:java-tools-22.04
RUN sudo apt-get update && sudo apt-get install clang libutf8proc-dev -y
```
but it worked fine. 


So after that I decided to try to add `clang` to the installation list like that even though it was already installed and since then the issue did not appear again :+1: :heavy_check_mark: .
![image](https://github.com/scala-native/scala-native/assets/739026/dd9c7592-e33b-4a13-a0eb-a58cf312e454)

I guess something must be different with `clang` installation, but didn't investigate further.
Tried to run `clang --version` before and after clang installation, but the output was the same: `Ubuntu clang version 14.0.0-1ubuntu1.1` ([logs](https://github.com/rolang/dumbo/actions/runs/6994294147/job/19027881735)).

**Comment by JD557** [comment]
Looking at https://github.com/scala-native/scala-native/blob/f4b9078c6c96dade366518f037d8f47048d2a4f3/util/src/main/scala/scala/scalanative/io/VirtualDirectory.scala, I see quite a bit of `try {...} finally {file.close()}` in there, which might be swallowing exceptions.

Maybe it would be a good idea to replace those with a `try {...} catch {logException()} finally {file.close()}`?

**Comment by JD557** [comment]
I'm seeing this issue pretty consistently with the update to SBT 1.10.0 when embedding resources, so I think the shared scope from https://github.com/scala-native/scala-native/pull/2039 is not being used correctly.

**Comment by JD557** [comment]
One possible workaround is to set `Global / concurrentRestrictions += Tags.limit(NativeTags.Link, 1)`

For some reason, I couldn't get it to work with `Tags.Test`, I think the tests till run in parallel, but I didn't look into it much further, as the goal is to remove the concurrency from the linking step, anyway.
