### ISSUE TITLE
Bug? Expected ClassCastException, got none.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2055]
The WIP port of CollectionsOnCheckedCollectionTest.scala has revealed what I believe to be
either a bug or a quirk of Scala Native.  This may be related to but probably differs 
from  Issue #1694, which reports similar strangeness with ArrayStoreExceptions.

I am currently using `@Ignore` of two instances of this test so that I can make
progress. That, however, is not a good medium or long term solution.

Is this a bug or did I mess something up in the port? 

Should I create a self contained program so that devos can run the
case in a 'normal' Scala Native environment? 

My thanks for any recommendations.

// From Scala.js
`CollectionsTestMainBase` is extended. It contains a number of declarations
but the ones pertinent to this Issue are:

```
 class A extends jl.Comparable[A] {
    def compareTo(o: A): Int = this.##.compareTo(o.##)
  }

  class B extends A

  class C extends B

```
The failing Test in  CollectionsOnCollectionTest is:
```
 @Test def testCheckedCollectionBadInputs(): Unit = {
    assumeTrue("Assumed compliant asInstanceOf", hasCompliantAsInstanceOfs)

/*                                                                              
    expectThrows(classOf[ClassCastException], superColl().add(new A))           
 */
    expectThrows(classOf[ClassCastException],
        superColl().addAll(TrivialImmutableCollection(new A)))
  }

  protected def superColl(): ju.Collection[A] =
    factory.empty[B].asInstanceOf[ju.Collection[A]]
```

The reported error is:
```
[error] Test org.scalanative.testsuite.javalib.util.CollectionsOnCheckedCollectionArrayListTest.testCheckedCollectionBadInputs failed: java.lang.AssertionError: expected ClassCastException to be thrown, but nothing was thrown, took 0.025796455 sec
[error]     at java.lang.AssertionError.this(Unknown Source)
[error]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
[error]     at scala.scalanative.junit.utils.AssertThrows$.expectThrowsBackport(Unknown Source)
```

**Comment by sjrd** [comment]
That's probably because `j.l.Class.cast` is not implemented correctly:
https://github.com/scala-native/scala-native/blob/87ec924349742b2145a7c49eafa090504dde78f2/nativelib/src/main/scala/java/lang/Class.scala#L27

**Comment by LeeTibbert** [comment]
sjrd  Thank you for the information. That it is indeed a bug.

Looks like the effort to port the Scala.js testing environment is discovering
bugs.

The corresponding Scala.js code looks like it dives into Node.js to
do the actual checking. (js.native).

The Scala [Reflection Overview Docs](
https://docs.scala-lang.org/overviews/reflection/overview.html) gives a code
snippet:
```
scala> import scala.reflect.runtime.{universe => ru}
import scala.reflect.runtime.{universe=>ru}

scala> def m[T: ru.TypeTag, S: ru.TypeTag](x: T, y: S): Boolean = {
    |   val leftTag = ru.typeTag[T]
    |   val rightTag = ru.typeTag[S]
    |   leftTag.tpe <:< rightTag.tpe
    | }
m: [T, S](x: T, y: S)(implicit evidence$1: scala.reflect.runtime.universe.TypeTag[T], implicit evidence$2: scala.reflect.runtime.universe.TypeTag[S])Boolean

scala> m(d, c)
res9: Boolean = true
```

I have not tried it out in a sandbox yet.  Might that be a good place for me to start a fix?
On a quick search of the Scala Native code base I did not see anything ready made.

**Comment by sjrd** [comment]
No, we don't have `TypeTag`s in Scala Native. They require reflection. Even if we had them, this is inside a JDK API so we can't ask for them.

You just want `j.l.Class.isInstance`.

**Comment by LeeTibbert** [comment]
Based on the information kindly provided above, I spent a day chasing this.
Nothing is simple.

Short story:  I believe a good path is to let WIP PR #2054 flow though the 
                    process of review, promotion to full PR, and acceptance 
                    containing the `@Ignore`ed test and a reference to this 
                    Issue.   

                    After that happens I/we can focus on this point Issue with
                    greater clarity.

Long Story:
  Agreed that the code in j.l.Class.cast referenced above looks suspicious.

   I set out to establish a baseline Test in j.l.ClassTest which exhibited the problem before
   I touched j.l.Class. Given that,  I could do one of the Koch tests to see if my intervention
   fixed the problem.

   I could not replicate the problem in that simpler environment.  ClassCastException
   was thrown in the places where it should be and not thrown where it should not.
   From rapid reading, I suspect that some processing is happening in the compiler,
   not j.l.Class#cast.  In fact, I suspect that j.l.Class#cast is never being called at all,
   but that might be my debugging printfs disappearing someplace.

   The classes I used where simple classes. I later hypothesized that I might
   get different results with Arrays.  I tried to re-establish my build environment
   for CollectionsOnCheckedCollectionTest to see if only the Array cases exhibited
   the lack of ClassCastException, but the file dependencies became more complicated
   than the time allowed.  

   I think the Ignored test is telling us something and should be investigated.  Based
   on my results today, I believe that will take less time & effort after the 
   CollectionsOnCheckedCollectionTest code merges.
