### ISSUE TITLE
Error:scalac: Error: native.this.FunctionPtr.fromFunction1 (conversion from function/method)

### ISSUE THREAD

**Issue by Sciss** [scala-native/scala-native#208]
Conversion from scala-functions or methods (via eta-expansion) to `FunctionPtrN` seems to be broken. A pattern match error in the compiler is produced. The stack trace below is from compiling this project: https://github.com/Sciss/scala-native-test/tree/scala-native-issue-208

The lines in question are:

```
def jack_shutdown(arg: Ptr[_]): Unit = exit(1)
```

And the call that causes the crash:

```
jack_on_shutdown(client, jack_shutdown _, DUMMY)
```

```
Error:scalac: Error: native.this.FunctionPtr.fromFunction1({
  {
    (new <$anon: Function1>(): Function1)
  }
}) (of class scala.reflect.internal.Trees$ApplyImplicitView)
scala.MatchError: native.this.FunctionPtr.fromFunction1({
  {
    (new <$anon: Function1>(): Function1)
  }
}) (of class scala.reflect.internal.Trees$ApplyImplicitView)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genFunPtrOp(NirCodeGen.scala:1314)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genPrimitiveOp(NirCodeGen.scala:923)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genApply(NirCodeGen.scala:874)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genExpr$1.apply(NirCodeGen.scala:505)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genExpr$1.apply(NirCodeGen.scala:463)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.notMergeableGuard(NirCodeGen.scala:417)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genExpr(NirCodeGen.scala:462)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genMethodArgs$2.apply(NirCodeGen.scala:1685)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genMethodArgs$2.apply(NirCodeGen.scala:1678)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genMethodArgs(NirCodeGen.scala:1678)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genMethodCall(NirCodeGen.scala:1642)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genMethodCall(NirCodeGen.scala:1630)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genApply(NirCodeGen.scala:882)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genExpr$1.apply(NirCodeGen.scala:505)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genExpr$1.apply(NirCodeGen.scala:463)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.notMergeableGuard(NirCodeGen.scala:417)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genExpr(NirCodeGen.scala:462)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$20.apply(NirCodeGen.scala:735)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$20.apply(NirCodeGen.scala:735)
    at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:154)
    at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:153)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at scala.scalanative.nir.Focus$.sequenced(Focus.scala:153)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genBlock(NirCodeGen.scala:735)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genExpr$1.apply(NirCodeGen.scala:549)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genExpr$1.apply(NirCodeGen.scala:463)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.notMergeableGuard(NirCodeGen.scala:417)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genExpr(NirCodeGen.scala:462)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$12.apply(NirCodeGen.scala:453)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$12.apply(NirCodeGen.scala:453)
    at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:40)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genNormalMethodBody(NirCodeGen.scala:452)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genMethod$1.apply(NirCodeGen.scala:279)
    at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:40)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genMethod(NirCodeGen.scala:254)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:241)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:239)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genMethods(NirCodeGen.scala:239)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genNormalClass(NirCodeGen.scala:183)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:151)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:149)
    at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:40)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.genClass(NirCodeGen.scala:149)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:128)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:124)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.apply(NirCodeGen.scala:124)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
    at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
    at scala.scalanative.nscplugin.NirCodeGen$SaltyCodePhase.run(NirCodeGen.scala:102)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:115)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:94)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:29)
    at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:26)
    at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:67)
    at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:24)
    at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

**Comment by densh** [comment]
Fixed in #470
