### ISSUE TITLE
Three  test-tools failures using SN 2.13.4 release-fast lto=thin on macOS CI.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2212]
I report these in case I get interrupted before I am able to run them to ground.

Three test failures were observed on GitHub macOS 10.15 when compiling `test-tools` with
 `release-fast` and `lto=thin`.  They do not appear with `release-fast` and `lto=none`

I have had the time yet to check if corresponding failures occur on Linux. 
The stock CI build does not exercise "lto=thin" (See issue #1960).

```
 Failed: Total 4166, Failed 10, Errors 0, Passed 4100, Skipped 56
Error:  Failed tests:
Error:  	java.lang.StackTraceElementTest
Error:  	java.lang.ExceptionTest
Error:  	java.lang.ThrowablesTest
Error:  (tests / Test / test) sbt.TestsFailedException: Tests unsuccessful
Error:  Total time: 300 s (05:00), completed Mar 19, 2021 10:22:28 PM
Error: Process completed with exit code 1.
```  

There is a sporting chance these are caused by the previous "warning" (see Issues #2210,
#2211).  
```
[warn] Found 7930 errors on @"M34scala.scalanative.nio.fs.UnixPath$D10normalizedL33scala.scalanative.nio.fs.UnixPathL16java.lang.StringEO" :
[warn]   0000  didopt def 
```

**Comment by ncordon** [comment]
I haven't forgotten about this. I have spent about a week debugging this. All the failures are generated by the `Throwable` stacktrace not being populated (and the tests expecting to find it populated). I've come with a minimal example for the sandbox:

```scala
object Test {
  def main(args: Array[String]): Unit = {
    val exception = new Exception
    exception.printStackTrace()
  }
}
```

with `set every nativeLTO:= "none"; set every nativeMode := "debug"` we get:

```java
java.lang.Exception
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at Test$.main(Unknown Source)
	at <none>.main(Unknown Source)
```


with `set every nativeLTO:= "thin"; set every nativeMode := "release-fast"` we get (be sure to clean and reload or exit `sbt` for reproducing with the new params):

```java
java.lang.Exception
	<no stack trace available>
```

The problem is also there with any combination of LTO `thin / full`, mode `release-fast, release-full` , Scala 2.12 or 2.13.

I've boiled it down to the [inlining](https://github.com/scala-native/scala-native/blob/d01ede7b7e98066a9eb61da7915cff0854c06aaf/tools/src/main/scala/scala/scalanative/interflow/Inline.scala#L62) in the interflow. If we don't inline anything, the stack ends up populated correctly.

At first I thought it was something we were inlining we shouldn't, and adding @noinlline to [this](https://github.com/scala-native/scala-native/blob/a3b9afdb7382d9b41b7147f1579bdf79ad0a195e/nativelib/src/main/scala/scala/scalanative/unsigned/UInt.scala#L306) implicit def, the stack trace gets populated for LTO = thin and mode = release-fast. But still does not work for LTO = full and mode = release-fast, so it must be something other than that. Cause inlining that def should not have any magic effect to be honest.

Any other pointers to keep debugging this? I've tried to compare the disassemble of two binaries that produce populated and empty stack traces respectively, but it's way difficult to find anything obvious there.

Maybe the answer is as simple as: we are inlining certain things, so the stack is expected to not unwind completely or not unwind at all?

**Comment by ncordon** [comment]
List of the tests failing:
```
[error] Test java.lang.ExceptionTest.printStackTrace failed: java.lang.AssertionError: null, took 0.000 sec
[error] Test java.lang.ThrowablesTest.setStackTraceStackTraceWriteToReturnedStack failed: java.lang.ArrayIndexOutOfBoundsException: 0, took 0.000 sec
[error] Test java.lang.ThrowablesTest.printStackTracePrintStream failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[error] Test java.lang.ThrowablesTest.throwable failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[error] Test java.lang.ThrowablesTest.throwableCause failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[error] Test java.lang.ThrowablesTest.throwableMessage failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[error] Test java.lang.ThrowablesTest.throwableMessageCauseFalseFalse failed: java.lang.AssertionError: Expected trace to contain '    	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[error] Test java.lang.StackTraceElementTest.isNativeMethod failed: java.util.NoSuchElementException: head of empty array, took 0.000 sec
[error] Test java.lang.StackTraceElementTest.getMethodName failed: java.util.NoSuchElementException: head of empty array, took 0.000 sec
[error] Test java.lang.StackTraceElementTest.getClassName failed: java.util.NoSuchElementException: head of empty array, took 0.000 sec
```

**Comment by LeeTibbert** [comment]
Nick,   Thank you for your time on this, must be frustrating 

I am  essentially offline for at least the next  two weeks.   You have done a
 good job of isolating the issue. 

 As folks know, stack traces tend to be highly sensitive to Operating System. 
Scala Native uses a (~~mongrel~) version of `libunwind`.   Assumptions
which were valid on Linux may not hold. We may need to put in some
OS specific stuff (perhaps as simple as a few `@noinline` (I think that
annotation exists).

Libunwind, and various variants are a nightmare.     When I return
I hope to build on you effort by looking at the SN  usage of libunwind,\
keeping in mind the `inline` you isolated.

I remember the pain, but not the details, of SN's libunwind usage and
I think it has changed a bit since I was last there.

My recommendation is to put this one on the back burner for a while.

Something that is do-able without major frustration (run for the Malvern
Hills when someone says something like that !) and which would
add information to the base report is to try a run with `release-full` and
`lto-thin`.    I would expect it to fail in the same, or quite similar, way, 
but one never knows.

**Comment by LeeTibbert** [comment]
Updating:   Current CI does not test the triple of this Issue: (macOS, release-fast, lto=thin)
                  A hand test will need to be done to acertain if this Issue is still relevant.
                  I suspect it it.

                  I have to run some PR candidates on macOS in the near future to convince
                  myself I did not break anything.  Perhaps I can figure out the current
                  way of specifying "release-fast" & "lto=thin".  A good excuse to bring
                  my skills into the present.

**Comment by LeeTibbert** [comment]
This is probably still at an active issue. At lest to the point of trying LTO on macOS to see
if the presenting problem still exists.

Scala Native CI __does_not__ test with LTO, which adds to me suspicion that this is still 
active.

I believe that SN CI runs on Intel hardware, real or emulated.  Apple M{1,2} silicon has
become available since the base note and seems to always reveal "quirks".

I will try to remember to do a LTO with release-fast when I am testing on
of my PRs on Apple silicon.    Seeing if the base problem still exists
is a step on the road towards fixing it.

**Comment by LeeTibbert** [comment]
Closing to reduce inactive backlog.  There has been a lot of improvement on macOS.
I think lto is currently disabled there because it has issues with "release-fast".  
Hope I am not spreading out-of-date falsehoods here.  As always, check current conditions.
