### ISSUE TITLE
Native link Hello world fails [Windows]

### ISSUE THREAD

**Issue by sigmasoldi3r** [scala-native/scala-native#2330]
The project is created with the command `sbt new scala-native/scala-native.g8`, and without touching anything else.

After the initial setup, I've tried with JDK 8 and JDK 11 with no success. `sbt run` will yield:

```
[error] Caused by: java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 16
[error] ^scala-native\(.+)(\.c|\.cpp|\.S)$
[error]                 ^
```

Here's the full trace:

```
[info] welcome to sbt 1.4.6 (ojdkbuild Java 1.8.0_282)
[info] loading global plugins from C:\Users\my_home_dir\.sbt\1.0\plugins
[info] loading settings for project scala-native-seed-project-build from plugins.sbt ...
[info] loading project definition from C:\Users\my_home_dir\Desktop\test\scala-native-seed-project\project
[info] loading settings for project scala-native-seed-project from build.sbt ...
[info] set current project to scala-native-seed-project (in build file:/C:/Users/my_home_dir/Desktop/test/scala-native-seed-project/)
[error] java.lang.ExceptionInInitializerError
[error]         at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:55)
[error]         at scala.scalanative.build.Logger.time(Logger.scala:35)
[error]         at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error]         at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error]         at scala.scalanative.build.Build$.build(Build.scala:54)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$7(ScalaNativePluginInternal.scala:128)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:207)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$4(ScalaNativePluginInternal.scala:128)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 16
[error] ^scala-native\(.+)(\.c|\.cpp|\.S)$
[error]                 ^
[error]         at java.util.regex.Pattern.error(Pattern.java:1969)
[error]         at java.util.regex.Pattern.compile(Pattern.java:1706)
[error]         at java.util.regex.Pattern.<init>(Pattern.java:1352)
[error]         at java.util.regex.Pattern.compile(Pattern.java:1028)
[error]         at scala.scalanative.build.NativeLib$.<init>(NativeLib.scala:168)
[error]         at scala.scalanative.build.NativeLib$.<clinit>(NativeLib.scala)
[error]         at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:55)
[error]         at scala.scalanative.build.Logger.time(Logger.scala:35)
[error]         at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error]         at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error]         at scala.scalanative.build.Build$.build(Build.scala:54)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$7(ScalaNativePluginInternal.scala:128)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:207)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$4(ScalaNativePluginInternal.scala:128)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / nativeLink) java.lang.ExceptionInInitializerError
[error] Total time: 1 s, completed 06-jul-2021 15:04:48
````

## Edit

Note: I'm using GNU family compilers though Msys2 to make things more compatible with the whole process of building, I don't know if that affects somehow, but it seems more like a compatibility problem with SBT or JRE.

I am lost atm.

## Edit 2

Runing `sbt compile` succeeds, but `sbt nativeLink` will yield the same error.

**Comment by sigmasoldi3r** [comment]
I've just noticed that the regular expression:

```regex
^scala-native\(.+)(\.c|\.cpp|\.S)$
```

Is indeed wrong, it should be:

```regex
^scala-native(.+)(\.c|\.cpp|\.S)$
```

Or

```regex
^scala-native\((.+)(\.c|\.cpp|\.S)$
```

(Or even `^scala-native\(.+\)(\.c|\.cpp|\.S)$`)

Depending on what is looking for, the problem is that I don't know where those sources are. In my Ubuntu machine did compile the last time I checked, tho (Shouldn't it fail for every system?).

**Comment by WojciechMazur** [comment]
Scala Native in version 0.4.0 does not support Windows yet, we're currently working on allowing that, minimal support would be available in the next release. 
The reported issue was already located and fixed in #2189.

**Comment by sigmasoldi3r** [comment]
Glad to hear! I'm very hyped about that next release!

Another question that arises in my mind is: Is it possible to cross-compile SN projects?

**Comment by WojciechMazur** [comment]
@sigmasoldi3r You compile for other target by setting up LLVM target triple, here's short description in the docs: https://scala-native.readthedocs.io/en/latest/user/sbt.html#cross-compilation-using-target-triple 
Also you might find some other information in the PR that have added this feature https://github.com/scala-native/scala-native/pull/2033
