### ISSUE TITLE
Cross compilation fails

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2340]
Environment:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

When I run `sbt +sbt +publishLocal` on 7deeb464e495e991fd5c9551591e9108e78d2414 as local root I have a errors:
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/catap/src/scala-native/"), "sbtScalaNative"):
[error]    org.scala-native:test-runner _2.12, _2.11
[error]    org.scala-native:nir _2.12, _2.11
[error]    org.scala-native:tools _2.12, _2.11
[error]    org.scala-native:util _2.12, _2.11
...
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-native:test-runner, org.scala-native:nir, org.scala-native:tools, org.scala-native:util
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$70(Defaults.scala:3003)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (sbtScalaNative / update) Conflicting cross-version suffixes in: org.scala-native:test-runner, org.scala-native:nir, org.scala-native:tools, org.scala-native:util
```

Playing with bisect shown that an issues started since d01ede7b7e98066a9eb61da7915cff0854c06aaf

**Comment by sjrd** [comment]
You can't use `+` this way in this project, because some projects are restricted to 2.12. You have to follow what the [release script](https://github.com/scala-native/scala-native/blob/master/scripts/release) instead.

**Comment by catap** [comment]
@sjrd before this commit `+` works :)

**Comment by avdv** [comment]
FYI, note that the `release` script is missing `windowslib/publishSigned` since commit 0c3ffdfd0821f08cb4b02b6a0d3ff8e5c6518526.
