### ISSUE TITLE
Jetty server is not part of the libs?

### ISSUE THREAD

**Issue by Maurycy-Sokolowski** [scala-native/scala-native#2352]
```[error] * M31org.eclipse.jetty.server.ServerRiE
[error]   - from M36......$D4mainLAL16java.lang.String_uEO
[error] * M37org.scalatra.servlet.ScalatraListenerRE
[error]   - from M36.......$D4mainLAL16java.lang.String_uEO
[error] * M38org.eclipse.jetty.webapp.WebAppContextRE
[error]   - from M36.....$D4mainLAL16java.lang.String_uEO
[error] * T23java.util.EventListener
[error]   - from M36....$D4mainLAL16java.lang.String_uEO
[error] * T31org.eclipse.jetty.server.Server
[error] java.util.NoSuchElementException: key not found: Top(org.eclipse.jetty.server.Server)
[error] 	at scala.collection.MapLike.default(MapLike.scala:236)
[error] 	at scala.collection.MapLike.default$(MapLike.scala:235)
[error] 	at scala.collection.AbstractMap.default(Map.scala:65)
[error] 	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$logLinked$2(ScalaNative.scala:44)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$logLinked$2$adapted(ScalaNative.scala:41)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.scalanative.build.ScalaNative$.showLinkingErrors$1(ScalaNative.scala:41)
[error] 	at scala.scalanative.build.ScalaNative$.logLinked(ScalaNative.scala:64)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:61)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:84)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:54)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$7(ScalaNativePluginInternal.scala:128)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:207)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$4(ScalaNativePluginInternal.scala:128)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (Compile / nativeLink) java.util.NoSuchElementException: key not found: Top(org.eclipse.jetty.server.Server)
[error] Total time: 12 s, completed Aug 21, 2021, 11:26:41 PM```

Got this error when compilling a scalatra/athmosphere project with embedded Jetty. I understand not all is supported but it would be nice.

**Comment by WojciechMazur** [comment]
Jetty is written in Java, currentlly it is only possible to use Scala Native with Scala sources or dependencies compiled with Scala Native. SN is using NIR files created by one of last scalac compiler phases. Since they're missing compilation failed as you could have seen in the logs.
In order to work with Jetty you would either need to reimplement it using Scala, or allow to create NIR from Java sources / bytecode

**Comment by Maurycy-Sokolowski** [comment]
How do to the later? I see a few examples of bare bones servers but it's hard to sacrifice all this nice abstraction and constructs through the DSL in Scalatra.
So far I only see the Play server as an alternative:

[https://www.playframework.com/documentation/2.8.x/ScalaEmbeddingPlayAkkaHttp](url)

**Comment by Maurycy-Sokolowski** [comment]
I was able to implement my own from scratch. I guess this is the solution needed. At least I have control over every single thing and like the minimalism.

**Comment by ekrich** [comment]
@Maurycy-Sokolowski You could try this - https://github.com/lolgab/snunit

**Comment by Maurycy-Sokolowski** [comment]
Checked it out but was getting a INIT error that no one had a clue how to resolve from the forums and a very complex configuration so just built my own server from scratch using uv... simpler and less of a leaky abstraction.

**Comment by ekrich** [comment]
ok, sure. The "Modern Systems Programming with Scala Native" book has lots of tips and examples too.

**Comment by ekrich** [comment]
@Maurycy-Sokolowski You can file an issue with `snunit` if you like but I think this can be closed too.
