### ISSUE TITLE
UdpSocketTest sometimes fails on Windows

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2398]
It's possible to observe that a single UdpSocketTests when run on Windows may sometimes fail in the CI, however, it's quite a rare behaviour (less than 1/200 runs)

```
[error] Test java.net.UdpSocketTest.sendtoRecvfrom failed: java.lang.AssertionError: recvfrom_1 length expected:<118> but was:<4294967295>, took 0.002 sec
[error]     at java.lang.StackTrace$.currentStackTrace(Unknown Source)
[error]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
[error]     ...
```

**Comment by WojciechMazur** [comment]
As comments in the test state, there is a chance of a race condition. We should check it out. The result of `recvfrom` is not checked, in case if it is equal to `SOCKET_ERROR` (-1?) more information get be retrieved from GetLastError() on Windows
