### ISSUE TITLE
Unit tests fail on MacOs when running with LTO

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2401]
When testing the possibility of adding MacOS tests to the CI I've found out 3 tests suites constantly falling:
```
[error] Failed tests:
[error] 	javalib.lang.StackTraceElementTest
[error] 	java.lang.ThrowablesTest
[error] 	javalib.lang.ExceptionTest
```
The problem appeared in each Scala version, when compiling in `release-fast` mode for both LTO settings `thin` and `full`. What's surprising, tests were working correctly when using LTO with disabled optimizations

More details about failed tests from logs:
StackTraceElementTests: probably no debug symbols are available 
```
[info] Test javalib.lang.StackTraceElementTest.isNativeMethod started
[error] Test javalib.lang.StackTraceElementTest.isNativeMethod failed: java.util.NoSuchElementException: head of empty array, took 0.000 sec
[info] Test javalib.lang.StackTraceElementTest.getMethodName started
[error] Test javalib.lang.StackTraceElementTest.getMethodName failed: java.util.NoSuchElementException: head of empty array, took 0.000 sec
[info] Test javalib.lang.StackTraceElementTest.getClassName started
[error] Test javalib.lang.StackTraceElementTest.getClassName failed: java.util.NoSuchElementException: head of empty array, took 0.000 sec
```

```
[info] Test java.lang.ThrowablesTest.testToString started
[info] Test java.lang.ThrowablesTest.setStackTraceStackTraceWriteToReturnedStack started
[error] Test java.lang.ThrowablesTest.setStackTraceStackTraceWriteToReturnedStack failed: java.lang.ArrayIndexOutOfBoundsException: 0, took 0.000 sec
[info] Test java.lang.ThrowablesTest.setStackTraceStackTraceWritableFalse started
[info] Test java.lang.ThrowablesTest.setStackTraceStackTraceWritableTrue started
[info] Test java.lang.ThrowablesTest.setStackTraceStackTraceInvalidArguments started
[info] Test java.lang.ThrowablesTest.printStackTracePrintStream started
[error] Test java.lang.ThrowablesTest.printStackTracePrintStream failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[info] Test java.lang.ThrowablesTest.initCauseCause started
[info] Test java.lang.ThrowablesTest.initCauseCauseCasesWhichThrowAnException started
[info] Test java.lang.ThrowablesTest.addSuppressedExceptionEnabledEqualsFalse started
[info] Test java.lang.ThrowablesTest.addSuppressedExceptionEnabledEqualsTrue started
[info] Test java.lang.ThrowablesTest.addSuppressedExceptionInvalidArguments started
[info] Test java.lang.ThrowablesTest.throwable started
[error] Test java.lang.ThrowablesTest.throwable failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[info] Test java.lang.ThrowablesTest.throwableCause started
[error] Test java.lang.ThrowablesTest.throwableCause failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[info] Test java.lang.ThrowablesTest.throwableMessage started
[error] Test java.lang.ThrowablesTest.throwableMessage failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
[info] Test java.lang.ThrowablesTest.throwableMessageCauseFalseFalse started
[error] Test java.lang.ThrowablesTest.throwableMessageCauseFalseFalse failed: java.lang.AssertionError: Expected trace to contain '	at <none>.main(Unknown Source)' and it did not., took 0.000 sec
```

```
[info] Test javalib.lang.ExceptionTest.printStackTraceNoStackTraceAvailable started
[info] Test javalib.lang.ExceptionTest.printStackTrace started
[error] Test javalib.lang.ExceptionTest.printStackTrace failed: java.lang.AssertionError: null, took 0.000 sec
```

**Comment by ekrich** [comment]
About here I starting getting some ideas about what may be wrong. https://github.com/scala-native/scala-native/issues/1918#issuecomment-849262580
