### ISSUE TITLE
Linking error: "Main method not defined in entries"

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2478]
SN: <= 0.4.2
Scala: 2.13.7

When linking an example (not properly minimised, but looks familiar to other issue fixed beefore):

```
[error] java.lang.AssertionError: assertion failed: Main method not defined in entries
[error] 	at scala.Predef$.assert(Predef.scala:223)
[error] 	at scala.scalanative.linker.Reach.result(Reach.scala:54)
[error] 	at scala.scalanative.linker.Reach$.apply(Reach.scala:878)
[error] 	at scala.scalanative.linker.Link$.apply(Link.scala:21)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$optimize$1(ScalaNative.scala:82)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:88)
[error] 	at scala.scalanative.build.ScalaNative$.optimize(ScalaNative.scala:78)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:72)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:35)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger$$anon$3.time(Logger.scala:88)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:55)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$7(ScalaNativePluginInternal.scala:135)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:272)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.buildNew$1(ScalaNativePluginInternal.scala:135)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$9(ScalaNativePluginInternal.scala:163)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
```

**build.sbt**
```scala
❯ cat build.sbt
scalaVersion := "2.13.6"

// Set to false or remove if you want to show stubs as linking errors
nativeLinkStubs := true

libraryDependencies += "com.monovore" %%% "decline" % "2.2.0"

enablePlugins(ScalaNativePlugin)
```

**src/main/scala/Main.scala**
```scala
import cats.implicits._
import com.monovore.decline._

object HelloWorld extends CommandApp(
  name = "hello-world",
  header = "Says hello!",
  main = {
    val userOpt =
      Opts.option[String]("target", help = "Person to greet.").withDefault("world")

    val quietOpt = Opts.flag("quiet", help = "Whether to be quiet.").orFalse

    (userOpt, quietOpt).mapN { (user, quiet) =>
      if (quiet) println("...")
      else println(s"Hello $user!")
    }
  }
)
```

**Comment by keynmol** [comment]
Can confirm it's fixed in the latest 0.4.3-SNAPSHOT :) Thanks for the super-fast turnaround Wojciech!
