### ISSUE TITLE
[Scala 3] ClassCastException

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#2520]
### `Main.scala`

```scala
package example

case class Kleisli[F[_], A, B](run: A => F[B])

object Kleisli {
  type KleisliOpt[A, B] = Kleisli[Option, A, B]

  implicit def instance: Strong[KleisliOpt] = new Strong[KleisliOpt] {
    override def first[A, B, C](f: KleisliOpt[A, B]): KleisliOpt[(A, C), (B, C)] =
      Kleisli[Option, (A, C), (B, C)] {
        case (a1, a2) => f.run(a1).map(_ -> a2)
      }
  }
}

trait Strong[F[_, _]] {
  def first[A, B, C](fa: F[A, B]): F[(A, C), (B, C)]

  trait Law {
    def test[A, B, C, D](f: C => D)(implicit PF: Strong[Function1]) = {
      val x: ((C, B)) => (D, B) = PF.first[C, D, B](f)
    }
  }

  def law: Law = new Law{}
}

object Main {
  import Kleisli.KleisliOpt

  implicit def instance: Strong[Function1] = new Strong[Function1] {
    override def first[A, B, C](f: A => B): Function1[(A, C), (B, C)] = {
      case (a1, a2) => (f(a1), a2)
    }
  }

  def main(args: Array[String]): Unit = {
    implicitly[Strong[KleisliOpt]].law.test[Int, Int, Int, Int](x => x)
  }

}
```

### `build.sbt`

```scala
scalaVersion := "3.1.0"

enablePlugins(ScalaNativePlugin)
```

### `project/build.properties`

```properties
sbt.version=1.6.1
```

### `project/plugins.sbt`

```scala
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.3-RC1")
```

### `sbt run`

```
java.lang.ClassCastException: example.Main$$$Lambda$1 cannot be cast to example.Kleisli
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
	at example.Kleisli$$anon$1.first(Unknown Source)
	at example.Strong$Law.test(Unknown Source)
	at example.Main$.main(Unknown Source)
	at example.Main.main(Unknown Source)
	at <none>.main(Unknown Source)
```

### Note
- https://github.com/scalaz/scalaz/blob/ba20abb337ff85fbcca024f231fe6aeca419af57/core/src/main/scala/scalaz/Strong.scala#L44-L60

**Comment by WojciechMazur** [comment]
Thank you for this report. It looks like this bug was already fixed. I was able to reproduce it with 0.4.3-RC1, but the problem no longer exists in the main branch.
