### ISSUE TITLE
doc building failed for scala-2.13.8

### ISSUE THREAD

**Issue by rssh** [scala-native/scala-native#2538]
command:
```
sbt ++2.13.8 tools2_13/doc
```

result:
```
 scala-native % sbt ++2.13.8 tools2_13/doc 
[info] welcome to sbt 1.6.1 (Homebrew Java 17)
[info] loading global plugins from /Users/rssh/.sbt/1.0/plugins
[info] loading settings for project scala-native-build from build.sbt ...
[info] loading project definition from /Users/rssh/packages/scala-native/scala-native/project
[info] loading settings for project scala-native from build.sbt ...
[info] resolving key references (108218 settings) ...
[info] Detected JDK version 17
[info] set current project to scala-native (in build file:/Users/rssh/packages/scala-native/scala-native/)
[info] Setting Scala version to 2.13.8 on 33 projects.
[info] Excluded 97 projects, run ++ 2.13.8 -v for more details.
[info] Reapplying settings...
[info] Detected JDK version 17
[info] set current project to scala-native (in build file:/Users/rssh/packages/scala-native/scala-native/)
[info] Main Scala API documentation to /Users/rssh/packages/scala-native/scala-native/tools/.2.13/target/scala-2.13/api...
[error] /Users/rssh/packages/scala-native/scala-native/tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:74:29: fruitless type test: a value of type scala.scalanative.build.Mode cannot also be a scala.scalanative.build.Mode.Release
[error]         case (_: build.Mode.Release, build.LTO.None) => single()
[error]                             ^
[error] /Users/rssh/packages/scala-native/scala-native/tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:75:29: fruitless type test: a value of type scala.scalanative.build.Mode cannot also be a scala.scalanative.build.Mode.Release
[error]         case (_: build.Mode.Release, _)              => separate()
[error]                             ^
[error] two errors found
[error] Scaladoc generation failed
[error] 	at xsbt.Runner.run(ScaladocBridge.scala:50)
[error] 	at xsbt.ScaladocBridge.run(ScaladocBridge.scala:21)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:154)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2159)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (tools2_13 / Compile / doc) Scaladoc generation failed
[error] Total time: 6 s, completed 22 Jan 2022, 09:04:35

```

**Comment by WojciechMazur** [comment]
Thank you for your report!

This seems to be an issue with the usage of JDK 17, on JDK 8 (which is used for releases) there are no such problems. This looks more like an issue JDK vs Scala issue, since `build.Mode.Release` is a subclass of `build.Mode` (unless for some reason it decided to compare subclass with companion object of Mode) 

I think we should prepare a reproducer and report an issue in Scala itself

**Comment by rssh** [comment]
It's reproduced with JDK08
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home
sbt ++2.13.8 tools2_13/doc
```

result:
```
[info] welcome to sbt 1.6.1 (Oracle Corporation Java 1.8.0_261)
[info] loading global plugins from /Users/rssh/.sbt/1.0/plugins
[info] loading settings for project scala-native-build from build.sbt ...
[info] loading project definition from /Users/rssh/packages/scala-native/scala-native/project
[info] loading settings for project scala-native from build.sbt ...
[info] resolving key references (108218 settings) ...
[info] Detected JDK version 8
[info] set current project to scala-native (in build file:/Users/rssh/packages/scala-native/scala-native/)
[info] Setting Scala version to 2.13.8 on 33 projects.
[info] Excluded 97 projects, run ++ 2.13.8 -v for more details.
[info] Reapplying settings...
[info] Detected JDK version 8
[info] set current project to scala-native (in build file:/Users/rssh/packages/scala-native/scala-native/)
[info] Main Scala API documentation to /Users/rssh/packages/scala-native/scala-native/tools/.2.13/target/scala-2.13/api...
[error] /Users/rssh/packages/scala-native/scala-native/tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:74:29: fruitless type test: a value of type scala.scalanative.build.Mode cannot also be a scala.scalanative.build.Mode.Release
[error]         case (_: build.Mode.Release, build.LTO.None) => single()
[error]                             ^
[error] /Users/rssh/packages/scala-native/scala-native/tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:75:29: fruitless type test: a value of type scala.scalanative.build.Mode cannot also be a scala.scalanative.build.Mode.Release
[error]         case (_: build.Mode.Release, _)              => separate()
[error]                             ^
[error] two errors found
[error] Scaladoc generation failed
[error] 	at xsbt.Runner.run(ScaladocBridge.scala:50)
[error] 	at xsbt.ScaladocBridge.run(ScaladocBridge.scala:21)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:154)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2159)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

```

**Comment by WojciechMazur** [comment]
I have never seen this error when building locally (on Linux), but I've observed this issue for the first time in the CI for Scala 3 scripted tests on macOS  https://github.com/scala-native/scala-native/runs/5084095930?check_suite_focus=true#step:4:91
