### ISSUE TITLE
[0.4.3]  key not found: scala.scalanative.linker.Class@3e0bf784

### ISSUE THREAD

**Issue by rcano** [scala-native/scala-native#2545]
Since updating to 0.4.3, when running nativeLink, I get:

```
[info] Linking (1376 ms)
[info] Discovered 1170 classes and 8054 methods
[info] Optimizing (release-fast mode) (4134 ms)
[error] java.util.NoSuchElementException: key not found: scala.scalanative.linker.Class@4a4b0d55
[error]         at scala.collection.MapLike.default(MapLike.scala:236)
[error]         at scala.collection.MapLike.default$(MapLike.scala:235)
[error]         at scala.collection.AbstractMap.default(Map.scala:65)
[error]         at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
[error]         at scala.scalanative.codegen.Lower$Impl.genVal(Lower.scala:192)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$genCallOp$1(Lower.scala:492)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at scala.scalanative.codegen.Lower$Impl.genCallOp(Lower.scala:492)
[error]         at scala.scalanative.codegen.Lower$Impl.genOp(Lower.scala:362)
[error]         at scala.scalanative.codegen.Lower$Impl.genLet(Lower.scala:322)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$3(Lower.scala:132)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:43)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$2(Lower.scala:132)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$2$adapted(Lower.scala:127)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at scala.scalanative.codegen.Lower$Impl.onInsts(Lower.scala:127)
[error]         at scala.scalanative.nir.Transform.onDefn(Transform.scala:18)
[error]         at scala.scalanative.nir.Transform.onDefn$(Transform.scala:8)
[error]         at scala.scalanative.codegen.Lower$Impl.super$onDefn(Lower.scala:84)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefn$1(Lower.scala:84)
[error]         at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:43)
[error]         at scala.scalanative.codegen.Lower$Impl.onDefn(Lower.scala:84)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefns$1(Lower.scala:72)
[error]         at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error]         at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error]         at scala.scalanative.codegen.Lower$Impl.onDefns(Lower.scala:63)
[error]         at scala.scalanative.codegen.Lower$.apply(Lower.scala:23)
[error]         at scala.scalanative.codegen.CodeGen$.$anonfun$lower$2(CodeGen.scala:35)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
[error]         at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.map2combiner(ParHashMap.scala:80)
[error]         at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error]         at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[error] (Compile / nativeLink) java.util.NoSuchElementException: key not found: scala.scalanative.linker.Class@4a4b0d55
```

I tried rolling back to previous versions and I'm still getting it, I'm not sure what changed on my side even.

**Comment by WojciechMazur** [comment]
Thank you for the report. Is your project publicly available so we can try to reproduce your issue and try to fix it? Is this error also present when trying to compile with debug mode or with `nativeConfig ~= {_.withOptimize(false)}`

Side notes:
It looks like for some reason RuntimeTypeInformation is missing for some classes, probably it is caused by some `classOf[_]`  call, because fails when trying to lower `Val.ClassOf`. Maybe target of `Val.ClassOf` is not reached?

**Comment by rcano** [comment]
Oh, actually nevermind, I had completetly forgotten I was testing the  `@struct` which clearly isn't intended as public api, I forgot to remove the line and then got puzzled when updating to 0.4.3 from the RC, I'll close this one.
