### ISSUE TITLE
[Scala 3] `CFuncPtr` fails to link

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#2550]
Fails with Scala `3.1.1` and Scala Native `0.4.3`. It links with Scala 2

Reproduction:
```scala
import scala.scalanative.unsafe._

object Main {
  type Func = CFuncPtr2[Ptr[Byte], Int, Unit]
  val func: Func = (handle: Ptr[Byte], i: Int) => ()
  def main(args: Array[String]): Unit = {}
}
```

Stacktrace:
```
sbt:scala-native-repro> last Compile/nativeLink
[info] Linking (575 ms)
[info] Discovered 652 classes and 3650 methods
[error] java.util.NoSuchElementException: key not found: Local(2)
[error] 	at scala.collection.MapLike.default(MapLike.scala:236)
[error] 	at scala.collection.MapLike.default$(MapLike.scala:235)
[error] 	at scala.collection.AbstractMap.default(Map.scala:65)
[error] 	at scala.collection.MapLike.apply(MapLike.scala:144)
[error] 	at scala.collection.MapLike.apply$(MapLike.scala:143)
[error] 	at scala.collection.AbstractMap.apply(Map.scala:65)
[error] 	at scala.scalanative.interflow.State.loadLocal(State.scala:119)
[error] 	at scala.scalanative.interflow.Eval.eval(Eval.scala:868)
[error] 	at scala.scalanative.interflow.Eval.eval$(Eval.scala:865)
[error] 	at scala.scalanative.interflow.Interflow.eval(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Eval.eval(Eval.scala:383)
[error] 	at scala.scalanative.interflow.Eval.eval$(Eval.scala:107)
[error] 	at scala.scalanative.interflow.Interflow.eval(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Eval.run(Eval.scala:30)
[error] 	at scala.scalanative.interflow.Eval.run$(Eval.scala:11)
[error] 	at scala.scalanative.interflow.Interflow.run(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.MergeProcessor.visit(MergeProcessor.scala:376)
[error] 	at scala.scalanative.interflow.MergeProcessor.advance(MergeProcessor.scala:393)
[error] 	at scala.scalanative.interflow.Opt.process(Opt.scala:127)
[error] 	at scala.scalanative.interflow.Opt.process$(Opt.scala:111)
[error] 	at scala.scalanative.interflow.Interflow.process(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Inline.$anonfun$inline$1(Inline.scala:151)
[error] 	at scala.scalanative.interflow.Log.in(Log.scala:18)
[error] 	at scala.scalanative.interflow.Log.in$(Log.scala:8)
[error] 	at scala.scalanative.interflow.Interflow.in(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Inline.inline(Inline.scala:139)
[error] 	at scala.scalanative.interflow.Inline.inline$(Inline.scala:134)
[error] 	at scala.scalanative.interflow.Interflow.inline(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Eval.nonIntrinsic$1(Eval.scala:149)
[error] 	at scala.scalanative.interflow.Eval.eval(Eval.scala:163)
[error] 	at scala.scalanative.interflow.Eval.eval$(Eval.scala:107)
[error] 	at scala.scalanative.interflow.Interflow.eval(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Eval.run(Eval.scala:30)
[error] 	at scala.scalanative.interflow.Eval.run$(Eval.scala:11)
[error] 	at scala.scalanative.interflow.Interflow.run(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.MergeProcessor.visit(MergeProcessor.scala:376)
[error] 	at scala.scalanative.interflow.MergeProcessor.advance(MergeProcessor.scala:393)
[error] 	at scala.scalanative.interflow.Opt.process(Opt.scala:127)
[error] 	at scala.scalanative.interflow.Opt.process$(Opt.scala:111)
[error] 	at scala.scalanative.interflow.Interflow.process(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Opt.$anonfun$opt$1(Opt.scala:74)
[error] 	at scala.scalanative.interflow.Log.in(Log.scala:18)
[error] 	at scala.scalanative.interflow.Log.in$(Log.scala:8)
[error] 	at scala.scalanative.interflow.Interflow.in(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Opt.opt(Opt.scala:22)
[error] 	at scala.scalanative.interflow.Opt.opt$(Opt.scala:22)
[error] 	at scala.scalanative.interflow.Interflow.opt(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Visit.visitMethod(Visit.scala:124)
[error] 	at scala.scalanative.interflow.Visit.visitMethod$(Visit.scala:117)
[error] 	at scala.scalanative.interflow.Interflow.visitMethod(Interflow.scala:10)
[error] 	at scala.scalanative.interflow.Visit.visit$1(Visit.scala:97)
[error] 	at scala.scalanative.interflow.Visit.$anonfun$visitLoop$1(Visit.scala:111)
[error] 	at scala.scalanative.interflow.Visit.$anonfun$visitLoop$1$adapted(Visit.scala:111)
[error] 	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:145)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:982)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:979)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[error] (Compile / nativeLink) java.util.NoSuchElementException: key not found: Local(2)
```

Other reproduction without pointers:
```scala
import scala.scalanative.unsafe._

object Main {
  type Func = CFuncPtr3[Int, Int, Int, Unit]
  val func: Func = (a1: Int, a2: Int, a3: Int) => ()
  def main(args: Array[String]): Unit = {}
}
```

**Comment by lolgab** [comment]
There is a workaround for this issue, which is to use the boxed alternative of the primitive types in the function signature:
```scala
import scala.scalanative.unsafe._
object Main {
  type Func = CFuncPtr3[Integer, Integer, Integer, Unit]
  val func: Func = (a1: Integer, a2: Integer, a3: Integer) => ()
  def main(args: Array[String]): Unit = {}
}
```
This code works fine.
