### ISSUE TITLE
`scala.util.SortingTest` fails with LTO thin on Arm64

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2570]
Test `scala.util.SortingTest.testSortConsistency` from Scala partests fails, typically with of the reasons: 
* OutOfBounds (with indexway larger then size of array) exception,
* returning incorrectly sorted array
* segmentation fault

When running with disabled LTO it works correctly. 

Scala version: 2.13.8
Aarch: arm64  + qemu-aarch64-static
LTO: thin
Mode: release-fast
GC: immix/commix  

Stacktrace after failure with array size=1024, variety=2
```
Error:  Test scala.util.SortingTest.testSortConsistency failed: java.lang.ArrayIndexOutOfBoundsException: 28415, took 13.402 sec
Error:      at java.lang.Throwable.fillInStackTrace(Unknown Source)
Error:      at java.lang.RuntimeException.this(Unknown Source)
Error:      at scala.scalanative.runtime.package$.throwOutOfBounds(Unknown Source)
Error:      at scala.util.SortingTest$$Lambda$3.apply(Unknown Source)
Error:      at scala.math.Ordering$$anon$1.compare(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$insertionSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort(Unknown Source)
Error:      at scala.util.Sorting$.scala$util$Sorting$$mergeSort$mIc$sp(Unknown Source)
Error:      at scala.util.Sorting$.stableSort(Unknown Source)
Error:      at scala.util.SortingTest.runOneTest(Unknown Source)
Error:      at scala.util.SortingTest$$Lambda$13.apply(Unknown Source)
Error:      at scala.Function1.apply$mcVI$sp(Unknown Source)
Error:      at scala.util.SortingTest.$anonfun$testSortConsistency$2(Unknown Source)
Error:      at scala.util.SortingTest$$Lambda$14.apply(Unknown Source)
Error:      at scala.collection.immutable.List.foreach(Unknown Source)
Error:      at scala.util.SortingTest$$Lambda$11.apply(Unknown Source)
Error:      at scala.collection.immutable.VectorStatics$.foreachRec(Unknown Source)
Error:      at scala.collection.immutable.Vector.foreach(Unknown Source)
Error:      at scala.util.SortingTest$scalanative$junit$bootstrapper$.invokeTest(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.catchAll(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.$anonfun$executeTestMethod$6(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.handleExpected(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.runTestLifecycle(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.executeTestMethod(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.runTests$1(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.runTestLifecycle(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.executeTests(Unknown Source)
Error:      at scala.scalanative.junit.JUnitTask.execute(Unknown Source)
Error:      at scala.scalanative.testinterface.TestAdapterBridge.$anonfun$executeFun$1(Unknown Source)
Error:      at scala.util.Try$.apply(Unknown Source)
Error:      at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$2.apply(Unknown Source)
Error:      at scala.concurrent.impl.Promise$Transformation.run(Unknown Source)
Error:      at scala.scalanative.runtime.ExecutionContext$.loop(Unknown Source)
Error:      at scala.scalanative.runtime.package$.loop(Unknown Source)
Error:      at scala.scalanative.testinterface.NativeRPC.loop(Unknown Source)
Error:      at scala.scalanative.testinterface.TestMain$.main(Unknown Source)
Error:      at <none>.main(Unknown Source)
Error:      at <none>.(Unknown Source)
Error:      at <none>.__libc_start_main(Unknown Source)
Error:      at <none>._start(Unknown Source)
```

Incorrect result or check
```
[error] Test scala.util.SortingTest.testSortConsistency failed: java.lang.AssertionError: Quicksort should be in reverse order, took 4.295 sec
[error]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
```

**Comment by WojciechMazur** [comment]
Seems like this error can happen also without LTO enabled https://github.com/scala-native/scala-native/runs/5294658202?check_suite_focus=true#step:6:7409 

Commix / ReleaseFast / LTO none
