### ISSUE TITLE
Random Segfaults when running unit tests

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#2597]
When running unit tests with scala native 0.4.4 on scala 3.1.1, I'm getting some segmentation faults on rare occasions:

```
[error] Fatal signal 11 caught
[error]   at scala.scalanative.testinterface.signalhandling.SignalConfig$.asyncSafePrintStackTrace(Unknown Source)
[error]   at <none>._SM70scala.scalanative.testinterface.signalhandling.SignalConfig$$$Lambda$1G17$extern$forwarder(Unknown Source)
[error]   at scala.collection.immutable.List.map(Unknown Source)
```

This is non-deterministic, but it seems to always come from a `List[Int]#map.(_.toChar)`
I tried to reproduce it on 2.13.8, but was unable to, while on 3.1.1 it happened 3 times on 20 runs.

Here's a gist with a bit more information (although I'm not sure if it will be helpful: https://gist.github.com/JD557/6e6029b6ca89c76365a792f41a8d1d6e)

**Comment by LeeTibbert** [comment]
@JD557 Are you still experiencing this problem?  With Scala 3.1.2? 3.1.3?  If yes,
sorry for the time sink. Heisenbugs are very annoying.

On what operating system & hardware architecture were/are you running?

This stuff is supposed to be, in the best case, OS & hardware architecture 
independent.  Sadly, often it it not, especially in the case of intermittent
faults.

**Comment by JD557** [comment]
Just tried running the same problematic commit again.

Reproduced with:
- Scala 2.13.8, 3.1.1 and 3.1.2
- Scala-native 0.4.4
- Windows 10 64-bit (Build 19044.1706)
- Intel i10750H
- 16GB RAM

Now not only did I get segfaults, I also got some really weird `ClassCastExceptions`. Some examples:

`Failure(java.lang.ClassCastException: scala.scalanative.unsigned.UInt cannot be cast to scala.collection.immutable.List)`
`Failure(java.lang.ClassCastException: scala.scalanative.unsigned.ULong cannot be cast to scala.collection.immutable.List)`
`Failure(java.lang.ClassCastException: List(Color(255,255,255), Color(255,255,255),...) cannot be cast to scala.collection.immutable.List`
`Failure(java.lang.ClassCastException: class eu.joaocosta.minart.graphics.image.helpers.State$$$Lambda$1 cannot be cast to scala.collection.immutable.List)`
`ClassCastException: java.lang.Integer cannot be cast to scala.collection.immutable.List`
`ClassCastException: scala.scalanative.unsafe.Ptr cannot be cast to scala.collection.immutable.List`

Going to the next commit (see the PR above) seems to fix those issues.

**Comment by LeeTibbert** [comment]
@JD557  Thank you for the information and, especially, your time generating it.

Windows seems to be the key factor (but it could be any of them, as you knew
before I did.)

Seems like the issue is still relevant but that you have found a way to workaround
the SN defect.

I will try to study the code some day while I am waiting for a PR to finish/pass CI.
I do not have much knowledge of Windows so you are not getting the A team,
sorry.
