### ISSUE TITLE
Regex doesn't support unicode?

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2645]
```scala
//> using scala "3.1.2"
//> using platform "native"

@main def main = new scala.util.matching.Regex("\\u2070")
```

```
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 1
\u2070
 ^
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.regex.Parser$.invalidEscape$1(Unknown Source)
        at scala.scalanative.regex.Parser$.scala$scalanative$regex$Parser$$$parseEscape(Unknown Source)
        at scala.scalanative.regex.Parser.scala$scalanative$regex$Parser$$parseInternal(Unknown Source)
        at scala.scalanative.regex.Parser$.parse(Unknown Source)
        at scala.scalanative.regex.RE2$.compileImpl(Unknown Source)
        at scala.scalanative.regex.Pattern$.compile(Unknown Source)
        at scala.scalanative.regex.Pattern$.compile(Unknown Source)
        at java.util.regex.Pattern$.compile(Unknown Source)
        at java.util.regex.Pattern$.compile(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at test$package$.main(Unknown Source)
        at main.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

**Comment by armanbilge** [comment]
Swapping the `\\u2070` for `⁰` seems to work.

**Comment by LeeTibbert** [comment]
Dang! And the paint on #2640 is not even dry yet...

Seriously, thank you for the Issue & the reproducer.
Sorry you experienced it and it took your time.

Some notes from a rapid look at the issue:

```
// Fails, problem as reported reproduces in my environment
// @main def main = new scala.util.matching.Regex("\\u2070")                    

// Succeeds, note single backslash, yielding the single character superscript you reported as working.
@main def main = new scala.util.matching.Regex("\u2070")

```
from regex PatternTest.scala:
```
 @Ignore("not supported")
  @Test def characterClasses2(): Unit = {
    pass("\\0100", "\u0040") // 100 octal = 40 hex                              
    pass("\\xFF", "\u00FF")
    pass("\\uBEEF", "\uBEEF")
    pass("\\e", "\u001B") // escape                                             
    // control char \cx                                                         
  }

```

I do not remember why the "\\u" is not supported or I never knew or it broke
since I gained my freedom.

Both the "\\u" and  "\u" form work in Scastie, which uses java 17.

Both (at least)  the Java 8 & Java 17 docs clearly say: 
` Thus the strings "\u2014" and "\\u2014", while not equal, compile into the same pattern, which matches the character with hexadecimal value 0x2014. `

So far this looks like a detail of the re2 implementation, specifically the parser.
Any fix would probably be documenting the difference. The
current `javalib.html#regular-expressions-java-util-regex` doc does
not call out this difference.  (IMHO, yes it should work, but failing
that people should be given a sporting chance by having it documented.)

I have at least one PR and one Issue to create before I can spend the
time this Issue requires.

**Comment by ekrich** [comment]
> Any fix would probably be documenting the difference.
Shouldn't we be trying to make our implementation match the JVM?

**Comment by LeeTibbert** [comment]
re: Shouldn't we be trying to make our implementation match the JVM?

Agreed, passionately, as a goal.  Sometimes that is just too difficult.

I have been involved on another PR and have not been able to study
regex parserMumble.scala.  From having been there before and
from the `@Ignore` on the test suite, I suspect that better people
than I have been there before and found it too hard.  

I am neither ruling out nor despairing of a proper fix but
I would not be surprised at all such a fix would be 
more difficult than present time & cunning allow.

I will try to create some time to study the issue after 
I have cleared my backlog. If somebody else gets
to it first, may they have strength.

**Comment by armanbilge** [comment]
FWIW I think there are sufficient workarounds here (replacing `\\` with `\` or just directly using unicode characters) that this isn't high-priority. Just kind of annoying :)

**Comment by ekrich** [comment]
I think if the JVM and Native will support one `\` so that porting can be seamless then I agree.

**Comment by LeeTibbert** [comment]
My understanding of the issue is that JVM supports "\\uNNNN" as well as "\uNNNN".
On a fast read, it looks to me that this is a JVM special case. When I get some
time for this, I will check the rest of the regex universe.  If I had to put my
dollar down, I would say it is a JVM nicety/special_case, but I often
take the wrong side of the bet and end up a dollar short.

So, in the current case, porting a JVM application will not be seamless but
will have an easy workaround.

I myself have messed up the number of required "\" in a regex and still do.
So the JVM practice is a nicety.

To my thinking, the issue is mapping the magnitude of the issue to available
resources.
