### ISSUE TITLE
`ProcessTest` fails on macOS-12

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2769]
10/12 ProcessTests fails due to timeouts when executed on GitHub Actions macOS-12 env. 
https://github.com/scala-native/scala-native/runs/7658264104?check_suite_focus=true

**Comment by ekrich** [comment]
I think this is the same issue I see on M1 which is running 12.5. I started to look at the Process code and concluded that it needed work but didn't have time to look into it. I assumed it was a M1 issue - the signal seems to not be working.

**Comment by LeeTibbert** [comment]
Wojciech, thank you for the Issue and, especially, the log file.  I am going to copy
it below, because I think it will be essential to chasing this.

I believe there are two defects at play here. I believe that `ProcessTest` is
doing __exactly__ what it was designed to do here: yell if there is a problem.
The problem in the base note is, I believe & running from memory, a problem
with Process exit.  I will have to trace, but I believe two of those test
involve explicit signal delivery.

The second defect and one which pops in and out is the "kill signal is
not handled on SN M1".  There is an `AssumptionViolation` in the
SN Repository ProcessTest. I saw nothing in the PR which would
lead me to believe that the ProcessTest in the PR-under-test does
not have that code.  

A big part of a solution here is naming & numbering the beasts.

As a datapoint, given the ProcessTest being reported by the 
Principal & Vice-Principal, I ran Process test on my macOS 12.5 M1.
The `AssumptionViolation`s  triggered, as expected, but not
the mess in the logfile.

Unless someone else reports _this_ failure, we are probably
looking at something in the CI environment.  Oh joy! Meanwhile
saying __soto_voce__ "Thank Fate that is not in my environment!
Don't let that thing come here"

Sorry, ugly logfile extract. Primary data, need to keep it from disappearing
on me.
```
2022-08-03T18:35:04.2449170Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mshellFallback[0m started[0m
2022-08-03T18:35:04.2573050Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mdestroyForcibly[0m started[0m
2022-08-03T18:35:04.2674940Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mdestroyForcibly[0m failed: java.lang.[31mAssertionError[0m: process should have exited but timed out (limit: 502 milliseconds), took 0.589 sec[0m
2022-08-03T18:35:04.2778660Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.2880270Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.2981830Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3083570Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3185790Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3287340Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3387950Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mdestroy[0m started[0m
2022-08-03T18:35:04.3444160Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mdestroy[0m failed: java.lang.[31mAssertionError[0m: process should have exited but timed out (limit: 501 milliseconds), took 0.516 sec[0m
2022-08-03T18:35:04.3447630Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3451000Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3453030Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3454660Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3456350Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3457610Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3459040Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mwaitForWithTimeoutTimesOut[0m started[0m
2022-08-03T18:35:04.3460600Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mwaitForWithTimeoutCompletes[0m started[0m
2022-08-03T18:35:04.3462470Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mwaitForWithTimeoutCompletes[0m failed: java.lang.[31mAssertionError[0m: process should have exited but timed out (limit: 30 seconds), took 30.005 sec[0m
2022-08-03T18:35:04.3464390Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3465770Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3467130Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3469250Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3470820Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3472160Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3473460Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mredirectErrorStream[0m started[0m
2022-08-03T18:35:04.3475040Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mredirectErrorStream[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.134 sec[0m
2022-08-03T18:35:04.3476940Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3478800Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3480200Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3482150Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3483770Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3485540Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3487310Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36moutputStreamReadsFromFile[0m started[0m
2022-08-03T18:35:04.3488830Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31moutputStreamReadsFromFile[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.008 sec[0m
2022-08-03T18:35:04.3490410Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3491850Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3493300Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3494870Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3496350Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3497700Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3499220Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36minputStreamWritesToFile[0m started[0m
2022-08-03T18:35:04.3500800Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31minputStreamWritesToFile[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.080 sec[0m
2022-08-03T18:35:04.3502760Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3504670Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3506240Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3507940Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3509600Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3511210Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3512970Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36minputAndErrorStream[0m started[0m
2022-08-03T18:35:04.3514720Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31minputAndErrorStream[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.069 sec[0m
2022-08-03T18:35:04.3517160Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3519020Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3520700Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3522510Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3524110Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3525700Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3527170Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mpathPrefixOverride[0m started[0m
2022-08-03T18:35:04.3529510Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mpathPrefixOverride[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.139 sec[0m
2022-08-03T18:35:04.3531470Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3533170Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3534800Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3536630Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3538510Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3540020Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3541710Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mpathOverride[0m started[0m
2022-08-03T18:35:04.3543240Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mpathOverride[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.115 sec[0m
2022-08-03T18:35:04.3544990Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3546570Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3548090Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3551270Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3552800Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3554770Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3555720Z [0m[[0m[0minfo[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[36mls[0m started[0m
2022-08-03T18:35:04.3557370Z [0m[[0m[31merror[0m] [0m[0mTest javalib.lang.[33mProcessTest[0m.[31mls[0m failed: java.lang.[31mAssertionError[0m: Process took more than 10 SECONDS to exit., took 10.103 sec[0m
2022-08-03T18:35:04.3558880Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)[0m
2022-08-03T18:35:04.3560290Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)[0m
2022-08-03T18:35:04.3561570Z [0m[[0m[31merror[0m] [0m[0m    at scala.scalanative.unsafe.Zone$.apply(Unknown Source)[0m
2022-08-03T18:35:04.3563020Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.StackTrace$.currentStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3564370Z [0m[[0m[31merror[0m] [0m[0m    at java.lang.Throwable.fillInStackTrace(Unknown Source)[0m
2022-08-03T18:35:04.3565480Z [0m[[0m[31merror[0m] [0m[0m    ...[0m
2022-08-03T18:35:04.3566500Z [0m[[0m[0minfo[0m] [0m[0m[34mTest run finished: [0m[31m10 failed[0m[34m, [0m[34m0 ignored[0m[34m, 12 total, 112.434s[0m[0m
2022-08-03T18:35:04.3782910Z [0m[[0m[31merror[0m] [0m[0mFailed: Total 5641, Failed 10, Errors 0, Passed 5579, Skipped 52[0m
2022-08-03T18:35:04.3803420Z [0m[[0m[31merror[0m] [0m[0mFailed tests:[0m
2022-08-03T18:35:04.3804590Z [0m[[0m[31merror[0m] [0m[0m	javalib.lang.ProcessTest[0m
2022-08-03T18:35:10.1140420Z [0m[[0m[31merror[0m] [0m[0m(tests2_12 / Test / [31mtest[0m) sbt.TestsFailedException: Tests unsuccessful[0m
2022-08-03T18:35:10.1205080Z [0m[[0m[31merror[0m] [0m[0mTotal time: 287 s (04:47), completed Aug 3, 2022 6:35:10 PM[0m
2022-08-03T18:35:15.5121230Z ##[error]Process completed with exit code 1.
```

**Comment by LeeTibbert** [comment]
I just twigged to the fact that the architecture here is probably (emulated) X86. 64 bit? 32 Bit.
I have not been able to find that info in the log file.

Machine architecture should not make a difference, until it does.  

Perhaps I will try on M1 commenting out the two carefully placed
AssumptionViolations and see if I get something that looks similar.

Do we know anybody who has run the test on X64 macOS 12.5 out
in the World?

**Comment by LeeTibbert** [comment]
0.4.x PR submitted and passing all but multiarch.

I will post more details of defects (3 or more) here when it is not 104+° F (about 40°C).
