### ISSUE TITLE
Exception when compiling windows API call

### ISSUE THREAD

**Issue by domaspoliakas** [scala-native/scala-native#2866]
Hello 👋 I'm getting the following error when trying to compile a call to the windows API:

```
PS C:\Users\Domas\Dev\scala-tests> scala-cli run .\inout.scala
Compiling project (Scala 3.2.0, Scala Native)
Compiled project (Scala 3.2.0, Scala Native)
[info] Linking (1480 ms)
[info] Discovered 677 classes and 3694 methods
[info] Optimizing (debug mode) (1037 ms)
[info] Generating intermediate code (1115 ms)
[info] Produced 24 files
[error] C:\Users\Domas\Dev\scala-tests\.scala-build\project_057c9515ac_057c9515ac-ee18800cdb\native\0.ll:1137:21: error: invalid cast opcode for cast from 'i8*' to 'i32'
[error]   %_20010 = bitcast i8* null to i32
[error]                     ^
[error] 1 error generated.
Exception in thread "main" scala.scalanative.build.BuildException: Failed to compile C:\Users\Domas\Dev\scala-tests\.scala-build\project_057c9515ac_057c9515ac-ee18800cdb\native\0.ll
        at scala.scalanative.build.LLVM$.$anonfun$compile$1(LLVM.scala:70)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:66)
        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Error: scala.build.errors.ScalaNativeBuildError: Error compiling with Scala Native
For more details, please see 'C:\Users\Domas\Dev\scala-tests\.scala-build\stacktraces\1664044422-589079807952991940.log'
```

This can be reproduced using the following scala-cli script:

```scala
//> using platform "scala-native"
//> using scala "3.2.0"
//> using nativeVersion "0.4.7"

import scala.scalanative.windows.FileApi
import scala.scalanative.windows.winnt.AccessRights
import scala.scalanative.unsafe.*
import scala.scalanative.windows.FileApiExt

@main def main(): Unit = FileApi.CreateFileA(
                c"CONIN$$",
                AccessRights.FILE_GENERIC_READ,
                FileApiExt.FILE_SHARE_READ,
                null,
                FileApiExt.OPEN_EXISTING,
                null,
                null                    
            )
```

**Comment by domaspoliakas** [comment]
It seems that the issue is that I was passing `null` into a primitive param. I'll keep this open for the time being in case the error can be made a bit better.
