### ISSUE TITLE
Add support for scala.sys.process.Process

### ISSUE THREAD

**Issue by megaannum** [scala-native/scala-native#305]
scala-native-example worked.
Clone example directories, commented out all code replacing main with:

```
  def main(args: Array[String]): Unit = {
    import sys.process._
    println("Hello World")
    val cmd = "ls /etc"
    val files = ( cmd ).!!
    for (file <- files.split('\n')) println(s" file=$file")
}
```

At command line: sbt run
Got:

```
Unresolved dependencies:
  `@scala.sys.process.ProcessImplicits::stringToProcess_class.java.lang.String_class.scala.sys.process.ProcessBuilder`
scala.scalanative.linker.LinkingError
        at scala.scalanative.linker.Linker.linkClosed(Linker.scala:116)
        at scala.scalanative.compiler.Compiler.x$5$lzycompute(Compiler.scala:44)
        at scala.scalanative.compiler.Compiler.x$5(Compiler.scala:40)
        at scala.scalanative.compiler.Compiler.assembly$lzycompute(Compiler.scala:40)
        at scala.scalanative.compiler.Compiler.assembly(Compiler.scala:40)
        at scala.scalanative.compiler.Compiler.apply(Compiler.scala:85)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$compileNir(ScalaNativePluginInternal.scala:25)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$10.apply(ScalaNativePluginInternal.scala:134)
        at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$10.apply(ScalaNativePluginInternal.scala:111)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:nativeLink) scala.scalanative.linker.LinkingError
[error] Total time: 2 s, completed Sep 29, 2016 6:22:17 PM
```

running: scala -cp  target/scala-2.11/classes demo.Main
worked
Thanks.

**Comment by densh** [comment]
We don't support library side of processes yet. `scala -cp` runs JVM-compiled classes, that's why it worked.

**Comment by francoiscabrol** [comment]
is there a way to execute a shell command with scala native?

**Comment by densh** [comment]
@francoiscabrol You can call C's [`system`](http://www.cplusplus.com/reference/cstdlib/system/) directly via an extern object.

**Comment by densh** [comment]
Superseded by #746

**Comment by evan108108** [comment]
@densh I am still new to this project so bear with me. 

Can you give and example of how to  call C's [system](http://www.cplusplus.com/reference/cstdlib/system/) directly using an extern object?

For example what if I wanted to run a local bash script or how about this example from the "system" docs:

```c
std::system("ls -l >test.txt");
```

**Comment by faveoled** [comment]
The status "completed" is wrong. Currently getting a compilation error:
```
[error] missing symbols:
[error] * M16java.lang.ThreadD4joinuEO
[error]   - from M36scala.sys.process.ProcessImpl$Spawn$D5applyL16java.lang.StringzL15scala.Function0L16java.lang.ThreadEO
[error]   - from M26scala.sys.process.Process$D18Spawn$lzycompute$1uEPT26scala.sys.process.Process$
[error]   - from M26scala.sys.process.Process$D5SpawnL36scala.sys.process.ProcessImpl$Spawn$EO
[error]   - from M43scala.sys.process.ProcessBuilderImpl$SimpleD3runL27scala.sys.process.ProcessIOL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD3runzL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD5$bangiEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringL12scala.OptionuEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringuEO
[error]   - from M11app.Ffmpeg$D8runMergeL18java.nio.file.PathL18java.nio.file.PathL18java.nio.file.PathuEO
[error]   - from M9app.Main$D4mainLAL16java.lang.String_uEO
[error]   - from M8app.MainD4mainLAL16java.lang.String_uEo
[error] * M16java.lang.ThreadD5startuEO
[error]   - from M36scala.sys.process.ProcessImpl$Spawn$D5applyL16java.lang.StringzL15scala.Function0L16java.lang.ThreadEO
[error]   - from M26scala.sys.process.Process$D18Spawn$lzycompute$1uEPT26scala.sys.process.Process$
[error]   - from M26scala.sys.process.Process$D5SpawnL36scala.sys.process.ProcessImpl$Spawn$EO
[error]   - from M43scala.sys.process.ProcessBuilderImpl$SimpleD3runL27scala.sys.process.ProcessIOL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD3runzL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD5$bangiEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringL12scala.OptionuEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringuEO
[error]   - from M11app.Ffmpeg$D8runMergeL18java.nio.file.PathL18java.nio.file.PathL18java.nio.file.PathuEO
[error]   - from M9app.Main$D4mainLAL16java.lang.String_uEO
[error]   - from M8app.MainD4mainLAL16java.lang.String_uEo
[error] * M16java.lang.ThreadD9setDaemonzuEO
[error]   - from M36scala.sys.process.ProcessImpl$Spawn$D5applyL16java.lang.StringzL15scala.Function0L16java.lang.ThreadEO
[error]   - from M26scala.sys.process.Process$D18Spawn$lzycompute$1uEPT26scala.sys.process.Process$
[error]   - from M26scala.sys.process.Process$D5SpawnL36scala.sys.process.ProcessImpl$Spawn$EO
[error]   - from M43scala.sys.process.ProcessBuilderImpl$SimpleD3runL27scala.sys.process.ProcessIOL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD3runzL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD5$bangiEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringL12scala.OptionuEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringuEO
[error]   - from M11app.Ffmpeg$D8runMergeL18java.nio.file.PathL18java.nio.file.PathL18java.nio.file.PathuEO
[error]   - from M9app.Main$D4mainLAL16java.lang.String_uEO
[error]   - from M8app.MainD4mainLAL16java.lang.String_uEo
[error] * M16java.lang.ThreadRE
[error]   - from M43scala.sys.process.ProcessImpl$Spawn$$anon$1RL36scala.sys.process.ProcessImpl$Spawn$L15scala.Function0E
[error]   - from M36scala.sys.process.ProcessImpl$Spawn$D5applyL16java.lang.StringzL15scala.Function0L16java.lang.ThreadEO
[error]   - from M26scala.sys.process.Process$D18Spawn$lzycompute$1uEPT26scala.sys.process.Process$
[error]   - from M26scala.sys.process.Process$D5SpawnL36scala.sys.process.ProcessImpl$Spawn$EO
[error]   - from M43scala.sys.process.ProcessBuilderImpl$SimpleD3runL27scala.sys.process.ProcessIOL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD3runzL25scala.sys.process.ProcessEO
[error]   - from M52scala.sys.process.ProcessBuilderImpl$AbstractBuilderD5$bangiEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL24java.lang.ProcessBuilderL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL20scala.collection.SeqL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M33scala.sys.process.ProcessCreationD5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M26scala.sys.process.Process$D5applyL16java.lang.StringL12scala.OptionL30scala.collection.immutable.SeqL32scala.sys.process.ProcessBuilderEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringL12scala.OptionuEO
[error]   - from M8app.Env$D10runProcessL16java.lang.StringuEO
[error]   - from M11app.Ffmpeg$D8runMergeL18java.nio.file.PathL18java.nio.file.PathL18java.nio.file.PathuEO
[error]   - from M9app.Main$D4mainLAL16java.lang.String_uEO
[error]   - from M8app.MainD4mainLAL16java.lang.String_uEo
[error] unable to link
[error] (barNative / Compile / nativeLink) unable to link
```

**Comment by WojciechMazur** [comment]
@faveoled The `scala.sys.process` is backed by system threads which are not supported in 0.4.x versions. However, these should work without any issue in 0.5.0-SNAPSHOT - still under development, but most of the stuff works there. 
For the 0.4.x the workaround it to use `java.lang.Process` or as an alternative a better development experience to use [os-lib`](https://index.scala-lang.org/com-lihaoyi/os-lib) library being a part of scala toolkit - if I remember correctly it does not use threads in the native version.

**Comment by armanbilge** [comment]
@faveoled see also FS2 `Processes` which is supported on Scala Native in addition to JVM and Node.js.

https://fs2.io/#/io?id=processes
