### ISSUE TITLE
ju.stream.toArray appears broken; iterator() OK.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3134]
This is a "forget me not" because I am about 10 recursion levels deep in bugs...  It is also
a "heads up" to others.

For your amusement and enjoyment:

// add to StreamTest.scala
```
  @Test def streamToArray(): Unit = {
    val s = Stream.of(1, 2, 3)
    val	sa = s.toArray()
    assertEquals("Unexpected array size", 3, sa.length)
  }
```
yields 
```
[error] stack trace is suppressed; run last tests3 / Test / nativeLink for the full output
[error] (tests3 / Test / nativeLink) java.nio.file.FileSystemNotFoundException: Provider "https" not installed
[error] Total time: 9 s, completed Feb 3, 2023, 9:05:36 PM
```
Note well that this exception is in the JVM, during the reachability phase. Note also the "https" flaming red indirection.
```
sbt>  last tests3 / Test / nativeLink
[error] java.nio.file.FileSystemNotFoundException: Provider "https" not installed
[error] 	at java.base/java.nio.file.Path.of(Path.java:212)
[error] 	at java.base/java.nio.file.Paths.get(Paths.java:98)
[error] 	at scala.scalanative.linker.Reach.addMissing(Reach.scala:976)
[error] 	at scala.scalanative.linker.Reach.addMissing$1(Reach.scala:175)
[error] 	at scala.scalanative.linker.Reach.$anonfun$processDelayed$3(Reach.scala:183)
[error] 	at scala.scalanative.linker.Reach.$anonfun$processDelayed$3$adapted(Reach.scala:176)
```

I originally encountered this bug with Stream.sorted() and then worked my way down to this 
reproducer. sorted() may be using `toArray()` internally, I did not trace.

Linux, Ubuntu 22.10, Scala Native 0.5.0-SNAPSHOT (dated 2023-02-03), Scala 3.2.2.

I am working on Java 11 additions to SN javalib so I have reproduced in Java 11 (and 18, where I began).

The Test I am working on does not run on Java 8, so I have no data there.  A sandbox
program would supply that missing data.

Stream.iterator() is exercised in `StreamTest.scala` and has been passing CI matrix for ages.

**Comment by LeeTibbert** [comment]
I am closing this because I think recent code changes to reachability have fixed this.
Thank you @WojciechMazur 

Rather than getting an obscure  "https" errror I an now getting a much more informative:
```
Found 1 missing definitions while linking
[error] Not found Member(Top(java.util.stream.Stream),D7toArrayLAL16java.lang.Object_EO)
[error] 	at file:<redacted>/unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/util/stream/StreamTest.scala:99
[error] Undefined definitions found in reachability phase
[error] (tests3 / Test / nativeLink) Undefined definitions found in reachability phase

```

Indeed, given this clue and checking the SN code rather that the Java API description,  Scala Native does
not implement .toArray on Stream.   It also appears to not implement sorted() on Stream which was
my starting point.

**Comment by LeeTibbert** [comment]
On checking, scala.js appears to not implement `java.util.stream`, so I am on my own if I really want various
 Stream methods. Hard to be an adult; hard to manage wants.
