### ISSUE TITLE
`CFuncPtr.fromScalaFunction` should not require `scalanative.unsafe.Tag`

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3220]
Current implementation of this intrinsic functionally is based on `unsafe.Tag` evidence types, however their handling is flaky and can be improved. Instead of current parsing of materialization methods in `NirGenUtil` which is error prone, we might use exact type information about the type of called function. At this point, it was not implemented like that in the first place (maybe Scala 2.11 compact?). However, currently we might use 1 of two available approaches to mitigate this issue. The exact type information would be erased when generating CFuncPtr, but we can use 1 of the workarounds: 
- add special attachment to the tree which would be presevered during the AST transformations, eg. sizeOf intrinsics #3198
- use time travel mechanism on the full tree of the function, similarly as in for resolving varargs parameters #3204 (simpler, but might be fragile for AST transformations in the compiler)

**Comment by tanishiking** [comment]
Hey, @WojciechMazur!
I've been exploring this issue as a good starting point to understand the core of Scala Native. However, I'm having some difficulty grasping the specific details of the problem and the desired outcome, due to my lack of compiler backend knowledge. I have a few questions that I hope you could help clarify:

- How are `unsafe.Tag`s used in Scala Native in general, and for `CFuncPtr.{apply, fromScalaFunction}`?
  - Based on [NirGenExpr#genCFuncFromScalaFunction](https://github.com/scala-native/scala-native/blob/c98eeeba8fa757f204b1730c2a0bca11f9bae4de/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala#L2419), I assumed that generated NIR functions would have type names in [call[$type]](https://scala-native.org/en/stable/contrib/nir.html#call) or somewhere similar, but I couldn't find this in my experiment below.
- When you mentioned that "their handling is flaky", could you provide some more context or examples of this issue?
- Regarding the suggestion to `"add a special attachment to the tree which would be preserved during the AST transformations, e.g., sizeOf intrinsics Intrinsic based sizeOf[T] / alignmentOf[T] resolution #3198",`
  - Do you mean that we should add a special attachment that allows us to retrieve the exact type information at a later stage (`NirGenPhase`), **similar to** how Scala Native handles `sizeOf[T]` and `alignmentOf[T]`?
  - Not attaching information of `sizeOf[T]` or `alignmentOf[T]` for `alloca` in LLVM
- (bit unrelated to the issue itself but) Why do we need to generate `extern forwarder function`?

I appreciate any guidance or clarification you could provide!


<details>
<summary>Experiment with CFuncPtr1.fromScalaFunction</summary>

I did a bit of experiment with the following code and build settings,

```scala
import scala.scalanative.unsafe._

object Main {
  def main(args: Array[String]): Unit =
    def fnDef(str: CString): CInt = 1
    val fnDefPtr1 = CFuncPtr1.fromScalaFunction(fnDef)
    println(fnDefPtr1)
}
```

with

```scala
nativeConfig ~= { c =>
  c.withLTO(LTO.none)
    .withMode(Mode.debug)
    .withGC(GC.immix)
    .withDump(true)
}
```

The related codes in `linked.hnir` are:

This seems a `main` function body.

- Get the pointer to the generated forwarder function
- Allocate memory for `CFuncPtr1`
- Calls the `M34scala.scalanative.unsafe.CFuncPtr1RR_E` (linked implementation of `CFuncPtr1.fromScalaFunction`?)
  - Stores the pointer to the forwarder function to `%7`. (allocated for `CFuncPtr1`)

```scala
def @"M5Main$D4mainLAL16java.lang.String_uEO" : (@"T5Main$", array[@"T16java.lang.String"]) => unit {
%3(%2 : @"T5Main$", %1 : array[@"T16java.lang.String"]):
  ...
  // %6 is a pointer to the "G17$extern$forwarder"
  // The forwarder function goes around and calls fnDef
  %6 = method %4 : !?@"T15Main$$$Lambda$1", "G17$extern$forwarder"

  // Allocate for `CFuncPtr1`
  %7 = classalloc @"T34scala.scalanative.unsafe.CFuncPtr1"

  // Store address of forwarder function(%6) into %7
  %8 = call[(@"T34scala.scalanative.unsafe.CFuncPtr1", ptr) => unit] @"M34scala.scalanative.unsafe.CFuncPtr1RR_E" : ptr(%7 : !?@"T34scala.scalanative.unsafe.CFuncPtr1", %6 : ptr)

  %9 = module @"T13scala.Predef$"
  %10 = call[(@"T13scala.Predef$", @"T16java.lang.Object") => unit] @"M13scala.Predef$D7printlnL16java.lang.ObjectuEO" : ptr(%9 : !?@"T13scala.Predef$", %7 : !?@"T34scala.scalanative.unsafe.CFuncPtr1")
  ret unit
}
```

```scala
// forwarder functions
extern def @"M15Main$$$Lambda$1G17$extern$forwarder" : (ptr) => int {
%2(%1 : ptr):
  %3 = box[@"T28scala.scalanative.unsafe.Ptr"] %1 : ptr
  %4 = module @"T5Main$"
  %5 = call[(@"T5Main$", @"T28scala.scalanative.unsafe.Ptr") => int] @"M5Main$D10$anonfun$1L28scala.scalanative.unsafe.PtriEPT5Main$" : ptr(%4 : !?@"T5Main$", %3 : !@"T28scala.scalanative.unsafe.Ptr")
  ret %5 : int
}

def @"M5Main$D10$anonfun$1L28scala.scalanative.unsafe.PtriEPT5Main$" : (@"T5Main$", @"T28scala.scalanative.unsafe.Ptr") => int {
%3(%2 : @"T5Main$", %1 : @"T28scala.scalanative.unsafe.Ptr"):
  %4 = call[(@"T5Main$", @"T28scala.scalanative.unsafe.Ptr") => int] @"M5Main$D7fnDef$1L28scala.scalanative.unsafe.PtriEPT5Main$" : ptr(%2 : @"T5Main$", %1 : @"T28scala.scalanative.unsafe.Ptr")
  ret %4 : int
}

// looks like endup calling the `fnDef` implementation?
def @"M5Main$D7fnDef$1L28scala.scalanative.unsafe.PtriEPT5Main$" : (@"T5Main$", @"T28scala.scalanative.unsafe.Ptr") => int {
%3(%2 : @"T5Main$", %1 : @"T28scala.scalanative.unsafe.Ptr"):
  ret int 1
}
```

```scala
// Implementation of `fromScalaFunction`?
// Store the pointer of the function received as the 2nd argument at the address received as the 1st argument.
def @"M34scala.scalanative.unsafe.CFuncPtr1RR_E" : (@"T34scala.scalanative.unsafe.CFuncPtr1", ptr) => unit {
%3(%2 : @"T34scala.scalanative.unsafe.CFuncPtr1", %1 : ptr):
  %4 = call[(@"T33scala.scalanative.unsafe.CFuncPtr", ptr) => unit] @"M33scala.scalanative.unsafe.CFuncPtrRR_E" : ptr(%2 : @"T34scala.scalanative.unsafe.CFuncPtr1", %1 : ptr)
  ret unit
}
def @"M33scala.scalanative.unsafe.CFuncPtrRR_E" : (@"T33scala.scalanative.unsafe.CFuncPtr", ptr) => unit {
%3(%2 : @"T33scala.scalanative.unsafe.CFuncPtr", %1 : ptr):
  %4 = fieldstore[ptr] %2 : @"T33scala.scalanative.unsafe.CFuncPtr", @"M33scala.scalanative.unsafe.CFuncPtrF6rawptrPT33scala.scalanative.unsafe.CFuncPtr", %1 : ptr
  %5 = call[(@"T16java.lang.Object") => unit] @"M16java.lang.ObjectRE" : ptr(%2 : @"T33scala.scalanative.unsafe.CFuncPtr")
  ret unit
}
```

</details>

**Comment by tanishiking** [comment]
Thank you for the detailed explanation, @WojciechMazur! That really helps me understand the scala-native internals better.

I have one more clarifying question regarding the intrinsics-based `sizeOf[T]` and `alignmentOf[T`] resolution (https://github.com/scala-native/scala-native/pull/3198). I can see that we restore the exact type information for `sizeOf[T]` and `alignmentOf[T]` as follows:
My question is, why do we convert `sizeOf[T]` into `sizeOf(cls: Class[_])`? Is this because at the `NirGenExpr`, the `TypeApply` won't be available due to type erasure, am I right?

- There are two definitions of `sizeOf`: `sizeOf[T]` and `sizeOf(cls: Class[_])`.
  - https://github.com/scala-native/scala-native/blob/93673adafa2e37c3d10de1c630a8323a47ae3a71/nativelib/src/main/scala/scala/scalanative/runtime/Intrinsics.scala#L175-L181
  - `sizeOf(cls: Class[_])` is a kind of private intrinsic method, and users are expected to use the `sizeOf[T]` method.
- During the `PrepNativeInteropLate` phase (which runs after `Inlining` and `PrepNativeInterop` (right after `PostTyper`))
  - `sizeOf[T]` is transformed into `sizeOf(cls: Class[_])` with `withAttachment(...)`
  - https://github.com/scala-native/scala-native/blob/2b163191ea5438a15f0ed781da72d9b84a98f7a9/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/PrepNativeInteropLate.scala#L56-L65
- In `NirGenExpr`, the attached type information is retrieved.
  - https://github.com/scala-native/scala-native/blob/93673adafa2e37c3d10de1c630a8323a47ae3a71/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala#L2261

**Comment by WojciechMazur** [comment]
> My question is, why do we convert sizeOf[T] into sizeOf(cls: Class[_])? 

`sizeOf[T]` is represented in AST as `TypeApply`, however `sizeOf(cls: Class[_])` is represented as `Apply`. At the type phase we can easily distinguish them. However, at some later phase, probably before erasure, `TypeApply` is transformed into `Apply` and there is high probability that the Attachment would be lost. To mitigate this problem we transform it early ourself and ensure the attachment would not be lost. 
It would be great if we could use just use a single `def sizeOf[T]`, we don't need the runtime value of `Class[_]` anyway,  but if we would use symbol of `sizeOf[T]` in `Apply` instead of `TypeApply` it would not typecheck. At least that what I've observed in the past.

**Comment by tanishiking** [comment]
Thank you very much @WojciechMazur 
I have a bit of progress, it's still WIP, I could retain the exact type information attached to the AST 
at `GenNIrExpr` in Scala3 :tada: https://github.com/tanishiking/scala-native/commit/eb27e0109ff8292fcc67e4c10fae6ae83680275c
Tested on https://github.com/tanishiking/scala-native-sbt

However, whenever I add changes to `nativelib/src/main/scala/scala/scalanative/unsafe/CFuncPtr.scala.gyb` (and generate), I started to get the following error for `scalalib` when I run `++3.2.2 publishLocal`. (while the compiler plugin can be published locally).

Do you have any ideas why this happens / how can I debug this?

```
[error] error: patch failed: scalalib/target/scalaSources/2.13.8/scala/collection/concurrent/TrieMap.scala:23
[error] error: scalalib/target/scalaSources/2.13.8/scala/collection/concurrent/TrieMap.scala: patch does not apply
[error] Cannot apply patch for Some(overrides-2.13/scala/collection/concurrent/TrieMap.
...
[error] stack trace is suppressed; run last scalalib2_13 / Compile / sources for the full output
[error] (scalalib2_13 / Compile / sources) java.lang.Exception: Failed to apply some of scalalib patches, check logs for more information
[error] Total time: 5 s, completed Apr 25, 2023, 7:44:40 PM

sbt:scala-native> last scalalib2_13 / Compile / sources
[error] java.lang.Exception: Failed to apply some of scalalib patches, check logs for more information
[error]         at build.Settings$.$anonfun$commonScalalibSettings$14(Settings.scala:801)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (scalalib2_13 / Compile / sources) java.lang.Exception: Failed to apply some of scalalib patches, check logs for more information
```

**Comment by WojciechMazur** [comment]
We provide a set of overrides for the Scala standard library in the form of patches, this way we're early notified about any changes of the overridden sources. When compiling scalalib we fetch Scala stdlib sources and apply mentioned patches.  However, because of lack of proper tools on Windows we needed to fallback to portable git patches instead of the UNIX ones. These are way more fragile. On Windows we use a fix for used line end encoding, maybe it might be related, but based on the used paths it should be fine https://github.com/scala-native/scala-native/blob/6f95aa7b043145e813785a49c9fccdb4c95eec75/.github/workflows/run-tests-windows.yml#L31-L33 

As a temporary workaround you can open a project in sandboxed and clean env, eg. in gitpod https://gitpod.io/#https://github.com/scala-native/scala-native and try to apply patches there using helper scripts. The script is using ammonite, but it should be easy to convert it to scala-cli (typically in gitpod I use sdkman to install scala-cli/sbt, but it has no ammonite support)
```
amm ./scripts/scalalib-patch-tool.sc recreate <scala-version>
```
You can invoke it for all used Scala versions
```
amm ./scripts/scalalib-patch-tool.sc recreate 2.12.17
amm ./scripts/scalalib-patch-tool.sc recreate 2.13.10
amm ./scripts/scalalib-patch-tool.sc recreate 3.2.2
```
It would download the sources of Scala stdlib and would try to apply patches to it, by creating a `.scala` files in the same directories for all `.scala.patch` files. Scala sources have higher priority then patch files so at this point they can co-exist. 

If it would work in gitpod you can copy  patches `.scala` files to your machine and try to run 
```
amm ./scripts/scalalib-patch-tool.sc recreate <scala-version>
```
It would create a new patch, we could then compare it with a previous diff file, and check what's wrong with it.

Also, I've just seen that you're using Scala 2.13.8, can you try to do the same with 2.13.10? This version should be the default one currently
