### ISSUE TITLE
Allow creating custom `java.nio.ByteBuffer` in userspace

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#3238]
scala-native's `java.nio.ByteBuffer` define some custom constructor that diverge from the ones defined by the JVM
In userspace you see only the constructors in the JVM implementation and, since they are not defined in Scala Native, you have a linking error.

Given this code:
```scala
package java.nio

import scala.scalanative.unsafe._

final class PointerByteBuffer(ptr: Ptr[Byte], length: Int) extends ByteBuffer(0, 0, 0, 0, null, 0) {
  // Members declared in java.nio.Buffer
  def duplicate(): ByteBuffer = ???
  def isDirect(): Boolean = ???
  def isReadOnly(): Boolean = ???
  def slice(): ByteBuffer = ???

  // Members declared in ByteBuffer
  def asCharBuffer(): CharBuffer = ???
  def asDoubleBuffer(): DoubleBuffer = ???
  def asFloatBuffer(): FloatBuffer = ???
  def asIntBuffer(): IntBuffer = ???
  def asLongBuffer(): LongBuffer = ???
  def asReadOnlyBuffer(): ByteBuffer = ???
  def asShortBuffer(): ShortBuffer = ???
  def compact(): ByteBuffer = ???
  def get(): Byte = ???
  def get(x$0: Int): Byte = ???
  def getChar(): Char = ???
  def getChar(x$0: Int): Char = ???
  def getDouble(): Double = ???
  def getDouble(x$0: Int): Double = ???
  def getFloat(): Float = ???
  def getFloat(x$0: Int): Float = ???
  def getInt(): Int = ???
  def getInt(x$0: Int): Int = ???
  def getLong(): Long = ???
  def getLong(x$0: Int): Long = ???
  def getShort(): Short = ???
  def getShort(x$0: Int): Short = ???
  def put(x$0: Byte): ByteBuffer = ???
  def put(x$0: Int, x$1: Byte): ByteBuffer = ???
  def putChar(x$0: Char): ByteBuffer = ???
  def putChar(x$0: Int, x$1: Char): ByteBuffer = ???
  def putDouble(x$0: Double): ByteBuffer = ???
  def putDouble(x$0: Int, x$1: Double): ByteBuffer = ???
  def putFloat(x$0: Float): ByteBuffer = ???
  def putFloat(x$0: Int, x$1: Float): ByteBuffer = ???
  def putInt(x$0: Int): ByteBuffer = ???
  def putInt(x$0: Int, x$1: Int): ByteBuffer = ???
  def putLong(x$0: Long): ByteBuffer = ???
  def putLong(x$0: Int, x$1: Long): ByteBuffer = ???
  def putShort(x$0: Short): ByteBuffer = ???
  def putShort(x$0: Int, x$1: Short): ByteBuffer = ???
  def slice(x$0: Int, x$1: Int): ByteBuffer = ???

  private[nio] def _get(x$0: Int): Byte = ???
  private[nio] def _put(x$0: Int, x$1: Byte): Unit = ???

}
```

The linker errors the following:

```
[error] Found 1 missing definitions while linking
[error] Not found Member(Top(java.nio.ByteBuffer),RiiiiLAb_iE)
[error]         at file:/Users/lorenzo/scala/snunit/snunit/src/java/nio/PointerByteBuffer.scala:5
1 targets failed
snunit[3.2.2].test.nativeLink scala.scalanative.linker.LinkingException: Undefined definitions found in reachability phase
    scala.scalanative.linker.Reach.fail(Reach.scala:995)
    scala.scalanative.linker.Reach.reportMissing(Reach.scala:990)
    scala.scalanative.linker.Reach.result(Reach.scala:52)
    scala.scalanative.linker.Reach$.apply(Reach.scala:1008)
    scala.scalanative.linker.Link$.apply(Link.scala:13)
    scala.scalanative.build.core.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
    scala.scalanative.build.Logger.time(Logger.scala:35)
    scala.scalanative.build.Logger.time$(Logger.scala:32)
    scala.scalanative.build.Logger$$anon$3.time(Logger.scala:88)
    scala.scalanative.build.core.ScalaNative$.link(ScalaNative.scala:34)
    scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:71)
    scala.scalanative.build.Logger.time(Logger.scala:35)
    scala.scalanative.build.Logger.time$(Logger.scala:32)
    scala.scalanative.build.Logger$$anon$3.time(Logger.scala:88)
    scala.scalanative.build.Build$.build(Build.scala:61)
    mill.scalanativelib.worker.ScalaNativeWorkerImpl.nativeLink(ScalaNativeWorkerImpl.scala:98)
    mill.scalanativelib.ScalaNativeModule.$anonfun$nativeLink$2(ScalaNativeModule.scala:223)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
```

# Motivation

I'm trying to optimize the performance of [SNUnit](https://github.com/lolgab/snunit) and I want decode C strings without having to first copy them in an intermediate array. To do that I wanted to create a `PointerByteBuffer` which should wrap a `CString` and an int containing the length.

**Comment by armanbilge** [comment]
See also:
- https://github.com/scala-native/scala-native/issues/2614

I think we should follow Scala.js lead here.

**Comment by armanbilge** [comment]
@lolgab btw, I'm not sure if what you are asking here is possible.

In Scala JVM is it possible to extend `ByteBuffer` and make a custom implementation?

```scala
import java.nio.ByteBuffer

abstract class MyByteBuffer extends ByteBuffer
```

```
-- Error: /workspace/sandbox/test.scala:4:36 ----------------------------------------------------------------------
4 |abstract class MyByteBuffer extends ByteBuffer
  |                                    ^^^^^^^^^^
  |none of the overloaded alternatives named <init> can be accessed as a member of java.nio.ByteBuffer from class MyByteBuffer.
```

**Comment by lolgab** [comment]
> In Scala JVM is it possible to extend `ByteBuffer` and make a custom implementation?

The trick is to put the class in the `java.nio` package. It compiles in both JVM and Native, but in Native it fails to link because of the missing constructors.
In JVM it is blocked at runtime by:
```scala
Exception in thread "main" java.lang.SecurityException: Prohibited package name: java.nio
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:655)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at main$package$.run(main.scala:3)
        at run.main(main.scala:1)
```
but Scala Native doesn't that, I think.

**Comment by armanbilge** [comment]
> The trick is to put the class in the `java.nio` package.

You say trick, I say hack :)

Since this is unsupported on the JVM I don't think we should support it in Scala Native.

What happens in the JVM implementation evolves in a backwards-incompatible way for this usecase? In Scala Native we would have to match that to preserve parity. These are internal implementation details and we should avoid exposing them.

**Comment by lolgab** [comment]
Then I guess we need https://github.com/scala-native/scala-native/issues/2614

**Comment by WojciechMazur** [comment]
We would support that, as it's backed by JDK internal API. Use new `PointerByteBuffer` to wrap `Ptr[Byte]` into `ByteBuffer` added in #3532
