### ISSUE TITLE
sbt `testGrouping` raise `InvalidClassException`

### ISSUE THREAD

**Issue by lafeychine** [scala-native/scala-native#3246]
Using `Test / testGrouping` as described in the [sbt documentation](https://www.scala-sbt.org/1.x/docs/Testing.html#Forking+tests):
```scala
def groupByFirst(tests: Seq[TestDefinition]) =
    tests.groupBy(_.name(0)) map { case (letter, tests) =>
        Tests.Group(letter.toString, tests, Tests.SubProcess(ForkOptions()))
    } toSeq

Test / testGrouping := groupByFirst((Test / definedTests).value)
```

Any attempt by `sbt` to start a process will throw a `java.io.InvalidClassException` with the following trace:
```
[error] sbt.ForkMain$ForkError: java.io.InvalidClassException: sbt.testing.TaskDef; local class incompatible: stream classdesc serialVersionUID = -7417691495999416204, local class serialVersionUID = 2663134200025980977
[error] 	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[error] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2076)
[error] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1925)
[error] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2248)
[error] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1760)
[error] 	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2182)
[error] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1748)
[error] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:538)
[error] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:496)
[error] 	at sbt.ForkMain$Run.runTests(ForkMain.java:306)
[error] 	at sbt.ForkMain$Run.run(ForkMain.java:191)
[error] 	at sbt.ForkMain$Run.access$100(ForkMain.java:186)
[error] 	at sbt.ForkMain.main(ForkMain.java:177)
[error] 	at sbt.ForkMain.main(ForkMain.java:163)
```

This issue can be reproduced using the following simple test file:
```scala
import org.junit.Test
import org.junit.Assert.*

class JUnitTest:
    @Test
    def dummyTrueTest(): Unit =
        assertEquals(1, 1)
```

**Comment by armanbilge** [comment]
Replace
```
Tests.SubProcess(ForkOptions())
```
with
```
Tests.InProcess
```

Maybe a more helpful error message is possible here. Scala Native does not support "forked" tests.
https://github.com/scala-native/scala-native/blob/825f33d8b854512bff058bb81420d471c3304f86/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L206-L210
