### ISSUE TITLE
Pattern matching fails while matching the type of a generic parameter of a case class

### ISSUE THREAD

**Issue by astojanov** [scala-native/scala-native#326]
Consider the following example:

``` scala
import scalanative.native._
import stdio._

object App {

  abstract class A
  case class S [T](a: T) extends A

  def check(a: A) = a match {
    case S(d: Double) => fprintf(stdout, c"We have a double %lf\n", d)
    case S(d: Int)    => fprintf(stdout, c"We have an int: %d\n", a)
    case _            => fprintf(stdout, c"We have an unknown type\n")
  }

  def main(args: Array[String]): Unit = {
    val (dbl, int) = (S(2.3), S(2))
    check(dbl)
    check(int)
  }
}
```

Running `nativeLink` will fail:

```
[trace] Stack trace suppressed: run 'last *:nativeLink' for the full output.
[error] (*:nativeLink) scala.scalanative.util.package$UnsupportedException: Is(I(32),Local(Local(src,43),Ptr)) (class scala.scalanative.nir.Op$Is)
```

... and will produce the stack trace bellow:

```
> last *:nativeLink
scala.scalanative.util.package$UnsupportedException: Is(I(32),Local(Local(src,43),Ptr)) (class scala.scalanative.nir.Op$Is)
    at scala.scalanative.util.package$.unsupported(package.scala:19)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$27.apply(GenTextualLLVM.scala:451)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$27.apply(GenTextualLLVM.scala:403)
    at scala.scalanative.util.Show$$anon$1.apply(Show.scala:67)
    at scala.scalanative.util.Show$.toResult(Show.scala:81)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$showInsts$1.apply(GenTextualLLVM.scala:348)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$showInsts$1.apply(GenTextualLLVM.scala:290)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.scalanative.compiler.codegen.GenTextualLLVM.showInsts(GenTextualLLVM.scala:290)
    at scala.scalanative.compiler.codegen.GenTextualLLVM.showBlock(GenTextualLLVM.scala:147)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$9.apply(GenTextualLLVM.scala:129)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$9.apply(GenTextualLLVM.scala:127)
    at scala.scalanative.compiler.analysis.ControlFlow$Graph.map(ControlFlow.scala:30)
    at scala.scalanative.compiler.codegen.GenTextualLLVM.showFunctionDefn(GenTextualLLVM.scala:127)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$4.apply(GenTextualLLVM.scala:58)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$4.apply(GenTextualLLVM.scala:50)
    at scala.scalanative.util.Show$$anon$1.apply(Show.scala:67)
    at scala.scalanative.util.Show$.toResult(Show.scala:81)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2$$anonfun$apply$1.apply(GenTextualLLVM.scala:47)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2$$anonfun$apply$1.apply(GenTextualLLVM.scala:47)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2.apply(GenTextualLLVM.scala:47)
    at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2.apply(GenTextualLLVM.scala:37)
    at scala.scalanative.util.Show$$anon$1.apply(Show.scala:67)
    at scala.scalanative.compiler.codegen.GenShow.gen(GenShow.scala:7)
    at scala.scalanative.compiler.Compiler$$anonfun$codegen$1.apply(Compiler.scala:55)
    at scala.scalanative.compiler.Compiler$$anonfun$codegen$1.apply(Compiler.scala:55)
    at scala.scalanative.nir.serialization.package$.serializeFile(package.scala:22)
    at scala.scalanative.compiler.Compiler.codegen(Compiler.scala:55)
    at scala.scalanative.compiler.Compiler.apply(Compiler.scala:85)
    at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$compileNir(ScalaNativePluginInternal.scala:42)
    at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$11.apply(ScalaNativePluginInternal.scala:164)
    at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$11.apply(ScalaNativePluginInternal.scala:137)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by densh** [comment]
Thanks a lot for the report @astojanov !
