### ISSUE TITLE
posixlib: ClassCastException occurred in `utsnameOps`

### ISSUE THREAD

**Issue by mox692** [scala-native/scala-native#3263]
Hi team, I recently started using Scala Native and have encountered the following unexpected behavior:

## Env
Scala Native: 0.4.12
Scala: 2.13.10

## Reproducer

```scala
import scala.scalanative.unsafe._
import scala.scalanative.posix.sys.utsname._
import scala.scalanative.posix.sys.uname._

object Test {
  def main(args: Array[String]): Unit = {
    val u: Ptr[utsname] = stackalloc[utsname]()

    if (uname(u) == -1)
      throw new RuntimeException("uname err")

    // this causes error
    println(s"${u.sysname}")
  }
}
```
## Output

```
java.lang.ClassCastException: scala.scalanative.unsafe.CArray cannot be cast to scala.scalanative.unsafe.Ptr
        at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
        at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
        at scala.scalanative.posix.sys.uname$utsnameOps.sysname(Unknown Source)
        at Test$.main(Unknown Source)
        at Test.main(Unknown Source)
        at <none>.main(Unknown Source)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$23(ScalaNativePluginInternal.scala:292)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$21(ScalaNativePluginInternal.scala:292)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$21$adapted(ScalaNativePluginInternal.scala:269)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) Nonzero exit code: 1
```

**Comment by mox692** [comment]
If my understanding is correct, I don't think it's too difficult to fix, so I will create a pull request later.
