### ISSUE TITLE
ZipException when packaging scala-cli code with --native

### ISSUE THREAD

**Issue by kciesielski** [scala-native/scala-native#3363]
Example script:
```scala
//> using toolkit latest

import sttp.client4.*
import sttp.client4.curl.*
import sttp.client4.Response

object sttp4Native extends App:
    val backend = CurlBackend()
    val response: Response[String] = quickRequest
      .get(uri"http://icanhazip.com")
      .send(backend)

    println(response.body)
```

command:
`scala-cli --power package --native sttp.scala -f`

Error:
```
Exception in thread "main" java.util.zip.ZipException: invalid CEN header (bad signature)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1569)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
        at scala.scalanative.io.VirtualDirectory$JarDirectory.liftedTree1$1(VirtualDirectory.scala:160)
        at scala.scalanative.io.VirtualDirectory$JarDirectory.<init>(VirtualDirectory.scala:157)
        at scala.scalanative.io.VirtualDirectory$.jar(VirtualDirectory.scala:57)
        at scala.scalanative.io.VirtualDirectory$.real(VirtualDirectory.scala:65)
        at scala.scalanative.linker.ClassLoader$.$anonfun$fromDisk$1(ClassLoader.scala:19)
        at scala.collection.immutable.List.map(List.scala:293)
        at scala.scalanative.linker.ClassLoader$.fromDisk(ClassLoader.scala:18)
        at scala.scalanative.linker.Link$.apply(Link.scala:13)
        at scala.scalanative.build.core.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
        at scala.scalanative.build.Logger.time(Logger.scala:35)
        at scala.scalanative.build.Logger.time$(Logger.scala:32)
        at scala.scalanative.cli.utils.FilteredLogger.time(FilteredLogger.scala:7)
        at scala.scalanative.build.core.ScalaNative$.link(ScalaNative.scala:34)
        at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:71)
        at scala.scalanative.build.Logger.time(Logger.scala:35)
        at scala.scalanative.build.Logger.time$(Logger.scala:32)
        at scala.scalanative.cli.utils.FilteredLogger.time(FilteredLogger.scala:7)
        at scala.scalanative.build.Build$.build(Build.scala:61)
        at scala.scalanative.cli.ScalaNativeLd$.$anonfun$runLd$3(ScalaNativeLd.scala:73)
        at scala.scalanative.util.Scope$.apply(Scope.scala:32)
        at scala.scalanative.cli.ScalaNativeLd$.runLd(ScalaNativeLd.scala:72)
        at scala.scalanative.cli.ScalaNativeLd$.main(ScalaNativeLd.scala:42)
        at scala.scalanative.cli.ScalaNativeLd.main(ScalaNativeLd.scala)
Error: scala.build.errors.ScalaNativeBuildError: Error compiling with Scala Native
```

The issue seems to happen depending on file content. For example, changing `sttp4Native` main object name  is enough to make the compilation pass and a working binary  gets created. Different random correct changes in the code can affect the outcome. 

Working example:
```scala
//> using toolkit latest

import sttp.client4.*
import sttp.client4.curl.*
import sttp.client4.Response

object sttpClient4NativeWorkingExampleWithLongNameOfTheMainClass extends App:
    val backend = CurlBackend()
    val response: Response[String] = quickRequest
      .get(uri"http://icanhazip.com")
      .send(backend)

    println(response.body)
```

So far I'm noticing this only when using sttp. 

Issue confirmed on MacOS and Linux

**Comment by armanbilge** [comment]
Thanks for reporting! This looks like a scala-cli bug, and I encourage you to open an issue there. Here is a similar issue:
- https://github.com/VirtusLab/scala-cli/issues/2166

**Comment by WojciechMazur** [comment]
I've tried to reproduce it with different JDK versions on MacOS M1, and have not seen these problems. Maybe as pointed by the arman it's an issue with the scala-cli. I was testing it with latest version 1.0.1

**Comment by kciesielski** [comment]
Thanks @WojciechMazur, I'll close the issue here, as I reported it to scala-cli https://github.com/VirtusLab/scala-cli/issues/2258
