### ISSUE TITLE
nativeLink fails with `SCALANATIVE_OPTIMIZE=false` saying "Lowering ClassOf needs nir.Buffer"

### ISSUE THREAD

**Issue by tanishiking** [scala-native/scala-native#3442]
It looks like https://github.com/scala-native/scala-native/pull/3386 introduces a bug when `SCALANATIVE_OPTIMIZE=false` which occurs for `sandbox` project: blocks https://github.com/scala-native/scala-native/issues/3435

https://github.com/scala-native/scala-native/actions/runs/5898012257/job/15999032485

```sh
export SCALANATIVE_OPTIMIZE=false
sbt
sbt> sandbox3 / nativeLink
...
[error] scala.scalanative.util.UnsupportedException: Lowering ClassOf needs nir.Buffer
[error]         at scala.scalanative.util.package$.unsupported(package.scala:18)
[error]         at scala.scalanative.codegen.Lower$Impl.onVal(Lower.scala:250)
[error]         at scala.scalanative.nir.Transform.onOp(Transform.scala:100)
[error]         at scala.scalanative.nir.Transform.onOp$(Transform.scala:58)
[error]         at scala.scalanative.codegen.Lower$Impl.onOp(Lower.scala:17)
[error]         at scala.scalanative.nir.Transform.onInst(Transform.scala:41)
[error]         at scala.scalanative.nir.Transform.onInst$(Transform.scala:32)
[error]         at scala.scalanative.codegen.Lower$Impl.onInst(Lower.scala:244)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$7(Lower.scala:236)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error]         at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at scala.scalanative.codegen.Lower$Impl.onInsts(Lower.scala:236)
[error]         at scala.scalanative.nir.Transform.onDefn(Transform.scala:19)
[error]         at scala.scalanative.nir.Transform.onDefn$(Transform.scala:8)
[error]         at scala.scalanative.codegen.Lower$Impl.super$onDefn(Lower.scala:94)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefn$1(Lower.scala:94)
[error]         at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:44)
[error]         at scala.scalanative.codegen.Lower$Impl.onDefn(Lower.scala:94)
[error]         at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefns$1(Lower.scala:81)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at scala.scalanative.codegen.Lower$Impl.onDefns(Lower.scala:72)
[error]         at scala.scalanative.codegen.Lower$.apply(Lower.scala:15)
[error]         at scala.scalanative.codegen.llvm.CodeGen$.$anonfun$lower$3(CodeGen.scala:51)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[error] (sandbox3 / Compile / nativeLink) scala.scalanative.util.UnsupportedException: Lowering ClassOf needs nir.Buffer
[error] Total time: 115 s (01:55), completed Aug 21, 2023, 4:40:24 PM

```

## bisecting
- `HEAD=f0b390e4`
- `36d32f0` is the last commit that doesn't have this bug.  https://github.com/scala-native/scala-native/actions/runs/5885958382

```sh
❯ git bisect start HEAD 36d32f0
Bisecting: 2 revisions left to test after this (roughly 1 step)
[0a6d1368227b41339fc8cc38f099eab0539c766a] Fix #3431: javalib Matcher.reset(input) now updates underlying cached value (#3432)

❯ cat test.sh
SCALANATIVE_OPTIMIZE=false sbt "reload;clean;sandbox3 / nativeLink"

❯ git bisect run ./test.sh
running  './test.sh'
...

❯ git bisect log
# bad: [f0b390e4dacdefa74c04a8f663f93f6402ae70a5] Fix #3378: javalib {Stream, DoubleStream}#sorted now delays actual sort to a terminal operation (#3434)
# good: [36d32f015d5a024edf307cbd3e68e8ee90753a5d] Fix performance regression in release mode for stackalloc state restore (#3429)
git bisect start 'HEAD' '36d32f0'
# good: [0a6d1368227b41339fc8cc38f099eab0539c766a] Fix #3431: javalib Matcher.reset(input) now updates underlying cached value (#3432)
git bisect good 0a6d1368227b41339fc8cc38f099eab0539c766a
# bad: [24ee38f58138d293e6c2858d591c122559e97a3f] Preserve local variables names in NIR (#3386)
git bisect bad 24ee38f58138d293e6c2858d591c122559e97a3f
# good: [2ae4071060185d1bb2a212dbe2c08cecffe891e6] Fixes #2731: Need better way to detect 32-bit platforms (#3436)
git bisect good 2ae4071060185d1bb2a212dbe2c08cecffe891e6
# first bad commit: [24ee38f58138d293e6c2858d591c122559e97a3f] Preserve local variables names in NIR (#3386)
```

**Comment by tanishiking** [comment]
It looks like we have a diff in `linked.hnir` between `HEAD` (`f0b390e4`) (+) and `36d32f0` (-)

```diff
 %5:
   jump %6
 %6:
-  %12 = module @"T45scala.scalanative.runtime.MemoryLayout$Array$"
-  %13 = call[(@"T45scala.scalanative.runtime.MemoryLayout$Array$") => int] @"M45scala.scalanative.runtime.MemoryLayout$Array$D12ValuesOffsetiEO" : ptr(%12 : !?@"T45scala.scalanative.runtime.MemoryLayout$Array$")
-  %14 = imul[int] int 2, %1 : int
-  %15 = iadd[int] %13 : int, %14 : int
-  %16 = zsizecast[size] %15 : int
-  %17 = module @"T29scala.scalanative.runtime.GC$"
-  %18 = module @"T33scala.scalanative.unsigned.USize$"
-  %19 = call[(@"T33scala.scalanative.unsigned.USize$", size) => @"T32scala.scalanative.unsigned.USize"] @"M33scala.scalanative.unsigned.USize$D7valueOfwL32scala.scalanative.unsigned.USizeEO" : ptr(%18 : !?@"T33scala.scalanative.unsigned.USize$", %16 : size)
-  %20 = unbox[@"T32scala.scalanative.unsigned.USize"] %19 : @"T32scala.scalanative.unsigned.USize"
-  %21 = call[(@"T15java.lang.Class", size) => ptr] @"M29scala.scalanative.runtime.GC$C24scalanative_alloc_atomic" : ptr(classOf[@"T36scala.scalanative.runtime.ShortArray"], %20 : size)
-  %22 = module @"T45scala.scalanative.runtime.MemoryLayout$Array$"
-  %23 = call[(@"T45scala.scalanative.runtime.MemoryLayout$Array$") => int] @"M45scala.scalanative.runtime.MemoryLayout$Array$D12LengthOffsetiEO" : ptr(%22 : !?@"T45scala.scalanative.runtime.MemoryLayout$Array$")
-  %24 = zsizecast[size] %23 : int
-  %25 = elem[byte] %21 : ptr, %24 : size
-  %26 = store[int] %25 : ptr, %1 : int 
-  %27 = module @"T45scala.scalanative.runtime.MemoryLayout$Array$"
-  %28 = call[(@"T45scala.scalanative.runtime.MemoryLayout$Array$") => int] @"M45scala.scalanative.runtime.MemoryLayout$Array$D12StrideOffsetiEO" : ptr(%27 : !?@"T45scala.scalanative.runtime.MemoryLayout$Array$")
-  %29 = zsizecast[size] %28 : int
-  %30 = elem[byte] %21 : ptr, %29 : size
-  %31 = store[int] %30 : ptr, int 2 
-  %32 = bitcast[@"T16java.lang.Object"] %21 : ptr
-  %33 = as[@"T36scala.scalanative.runtime.ShortArray"] %32 : @"T16java.lang.Object"
-  ret %33 : @"T36scala.scalanative.runtime.ShortArray"
+  %12 <arrcls> = copy classOf[@"T36scala.scalanative.runtime.ShortArray"]
+  %13 = module @"T45scala.scalanative.runtime.MemoryLayout$Array$"
+  %14 = call[(@"T45scala.scalanative.runtime.MemoryLayout$Array$") => int] @"M45scala.scalanative.runtime.MemoryLayout$Array$D12ValuesOffsetiEO" : ptr(%13 : !?@"T45scala.scalanative.runtime.MemoryLayout$Array$")
+  %15 = imul[int] int 2, %1 <length> : int
+  %16 = iadd[int] %14 : int, %15 : int
+  %17 <arrsize> = zsizecast[size] %16 : int
+  %18 = module @"T29scala.scalanative.runtime.GC$"
+  %19 = module @"T33scala.scalanative.unsigned.USize$"
+  %20 = call[(@"T33scala.scalanative.unsigned.USize$", size) => @"T32scala.scalanative.unsigned.USize"] @"M33scala.scalanative.unsigned.USize$D7valueOfwL32scala.scalanative.unsigned.USizeEO" : ptr(%19 : !?@"T33scala.scalanative.unsigned.USize$", %17 <arrsize> : size)
+  %21 = unbox[@"T32scala.scalanative.unsigned.USize"] %20 : @"T32scala.scalanative.unsigned.USize"
+  %22 <arr> = call[(@"T15java.lang.Class", size) => ptr] @"M29scala.scalanative.runtime.GC$C24scalanative_alloc_atomic" : ptr(%12 <arrcls> : @"T15java.lang.Class", %21 : size)
+  %23 = module @"T45scala.scalanative.runtime.MemoryLayout$Array$"
+  %24 = call[(@"T45scala.scalanative.runtime.MemoryLayout$Array$") => int] @"M45scala.scalanative.runtime.MemoryLayout$Array$D12LengthOffsetiEO" : ptr(%23 : !?@"T45scala.scalanative.runtime.MemoryLayout$Array$")
+  %25 = zsizecast[size] %24 : int
+  %26 = elem[byte] %22 <arr> : ptr, %25 : size
+  %27 = store[int] %26 : ptr, %1 <length> : int 
+  %28 = module @"T45scala.scalanative.runtime.MemoryLayout$Array$"
+  %29 = call[(@"T45scala.scalanative.runtime.MemoryLayout$Array$") => int] @"M45scala.scalanative.runtime.MemoryLayout$Array$D12StrideOffsetiEO" : ptr(%28 : !?@"T45scala.scalanative.runtime.MemoryLayout$Array$")
+  %30 = zsizecast[size] %29 : int
+  %31 = elem[byte] %22 <arr> : ptr, %30 : size
+  %32 = store[int] %31 : ptr, int 2 
+  %33 = bitcast[@"T16java.lang.Object"] %22 <arr> : ptr
+  %34 = as[@"T36scala.scalanative.runtime.ShortArray"] %33 : @"T16java.lang.Object"
+  ret %34 : @"T36scala.scalanative.runtime.ShortArray"
```

Maybe `%12 <arrcls> = copy classOf[@"T36scala.scalanative.runtime.ShortArray"]` causes a problem?

**Comment by WojciechMazur** [comment]
The fact of emitting `copy classOf` is in my opinion rather a change that discovered bug, rather then introduced it. I think what is missing is the special handling for Op.Copy in `Lower.genOp`, currently it simply passes through. Instead it's value should be adapted using `genVal` which would eventually replace `Val.ClassOf` with the actual class instance.

**Comment by tanishiking** [comment]
Thank you for the pointer, let me check  👀
