### ISSUE TITLE
javalib String.offsetByCodePoints throws if the final character in the string is an unpaired high surrogate

### ISSUE THREAD

**Issue by rayrobdod** [scala-native/scala-native#3470]
javalib `String.offsetByCodePoints` throws if the final character in the string is an unpaired high surrogate and the method processes this final character. 

### Example

```scala
@main def Test = {
  println("\uD800".offsetByCodePoints(0, 1))
}
```

#### Expected (on JVM)

```
1
```

#### Actual

```
java.lang.ArrayIndexOutOfBoundsException: 1
        at java.lang.StackTrace$.currentStackTrace$$anonfun$1(Unknown Source)
        at java.lang.StackTrace$$$Lambda$2.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.runtime.package$.throwOutOfBounds(Unknown Source)
        at java.lang.Character$.offsetByCodePoints(Unknown Source)
        at java.lang.String.offsetByCodePoints(Unknown Source)
        at issue$package$.Test(Unknown Source)
        at Test.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__scrt_common_main_seh:(D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)(Unknown Source)
        at <none>.BaseThreadInitThunk(Unknown Source)
        at <none>.RtlUserThreadStart(Unknown Source)
```

**Comment by tanishiking** [comment]
>  Unpaired surrogates within the text range given by index and codePointOffset count as one code point each.
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#offsetByCodePoints(int,int)

```
❯ cat test.scala
@main def main = {
    println("\uD800".offsetByCodePoints(0, 1))
}

❯ scala-cli test.scala
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
1

❯ scala-cli test.scala --native
Compiling project (Scala 3.3.0, Scala Native)
Compiled project (Scala 3.3.0, Scala Native)
[info] Linking (756 ms)
[info] Discovered 680 classes and 3771 methods
[info] Optimizing (debug mode) (889 ms)
[info] Generating intermediate code (856 ms)
[info] Produced 8 files
[info] Compiling to native code (1649 ms)
[info] Total (4257 ms)
java.lang.ArrayIndexOutOfBoundsException: 1
        at java.lang.StackTrace$.currentStackTrace$$anonfun$1(Unknown Source)
        at java.lang.StackTrace$$$Lambda$2.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.runtime.package$.throwOutOfBounds(Unknown Source)
        at java.lang.Character$.offsetByCodePoints(Unknown Source)
        at java.lang.String.offsetByCodePoints(Unknown Source)
        at test$package$.main(Unknown Source)
        at main.main(Unknown Source)
        at <none>.main(Unknown Source)
```

**Comment by tanishiking** [comment]
It seems like we have an error when the part of string ends with the unpaired surrogate

https://github.com/scala-native/scala-native/blob/3dd595bc1c5315d42178cc4a3f5434563ab32ea8/javalib/src/main/scala/java/lang/Character.scala#L379-L383

```
❯ cat test.scala
// no problem
@main def main = {
    println("\uD800a".offsetByCodePoints(0, 1))
}

❯ scala-cli test.scala --native
1
```

and low-surrogate doesn't have the problem

```
@main def main = {
    println("\uDC00".offsetByCodePoints(0, 1))
}

❯ scala-cli test.scala --native
1
```
