### ISSUE TITLE
RuntimeException: failed tests

### ISSUE THREAD

**Issue by kyouko-taiga** [scala-native/scala-native#3486]
I hit the following error while running the complete test suite:
```
[error] java.lang.RuntimeException: Failed tests:
[error] 	run/build-library-dynamic
[error] 	run/build-library-static
[error] 	run/hello-world
[error] 	run/java-io-file-2
[error] 	run/junit
[error] 	run/native-code-include
[error] 
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.scriptedtest.ScriptedRunner.reportErrors(ScriptedTests.scala:548)
[error] 	at sbt.scriptedtest.ScriptedRunner.runAll(ScriptedTests.scala:551)
[error] 	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:520)
[error] 	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:418)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at sbt.ScriptedRun$RunV1.invoke(ScriptedRun.scala:106)
[error] 	at sbt.ScriptedRun.run(ScriptedRun.scala:35)
[error] 	at sbt.ScriptedRun.run$(ScriptedRun.scala:16)
[error] 	at sbt.ScriptedRun$RunV1.run(ScriptedRun.scala:88)
[error] 	at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3(ScriptedPlugin.scala:189)
[error] 	at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3$adapted(ScriptedPlugin.scala:178)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (sbtScalaNative / scripted) Failed tests:
[error] 	run/build-library-dynamic
[error] 	run/build-library-static
[error] 	run/hello-world
[error] 	run/java-io-file-2
[error] 	run/junit
[error] 	run/native-code-include
[error] Total time: 934 s (15:34), completed 19 Sep 2023, 15:48:21
```

Scala version: 2.12
Scala-native version: 5d28d3eb87046d73b6b9888897d38edbf4b7899b

**Comment by kyouko-taiga** [comment]
> A couple of questions, please. I do not mean to put you through the Inquisition:

Of course. Anything you need.

I'm using Scala 2.12.18, JDK 17, and LLVM 16.0.6. I'm running macOS 13.5.2 on an Apple M2.

Re-running the tests I got a different failure, so you might be onto something with the degrees of inclination of my machine. Unfortunately I have no way to measure them.

More likely I might have misconfigured my system yesterday since I noticed `sbt` wasn't able to locate LLVM when I run `sandbox/run`. I have fixed this problem (`llvm-config` is in my `PATH`) and am now stuck with this error (sorry for the long stack trace, I don't know what's relevant):

```
[error] x scala3/cross-version-compat 
sbt.internal.scripted.TestException: {line -1}  Reload for scripted batch execution failed.
  | => sat sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$5(ScriptedTests.scala:229)
	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$5$adapted(ScriptedTests.scala:223)
	at sbt.scriptedtest.ScriptedTests.$anonfun$commonRunTest$6(ScriptedTests.scala:317)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at sbt.scriptedtest.ScriptedTests.commonRunTest(ScriptedTests.scala:316)
	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$3(ScriptedTests.scala:233)
	at sbt.scriptedtest.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:267)
	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$1(ScriptedTests.scala:237)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:75)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at sbt.scriptedtest.ScriptedTests.runBatchTests$1(ScriptedTests.scala:209)
	at sbt.scriptedtest.ScriptedTests.runBatchedTests(ScriptedTests.scala:253)
	at sbt.scriptedtest.ScriptedTests.$anonfun$batchScriptedRunner$11(ScriptedTests.scala:148)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:490)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:500)
	at sbt.scriptedtest.ScriptedTests.$anonfun$batchScriptedRunner$10(ScriptedTests.scala:148)
	at sbt.scriptedtest.ScriptedRunner.$anonfun$runAll$1(ScriptedTests.scala:551)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at sbt.scriptedtest.ScriptedRunner.runAll(ScriptedTests.scala:551)
	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:520)
	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:418)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.ScriptedRun$RunV1.invoke(ScriptedRun.scala:106)
	at sbt.ScriptedRun.run(ScriptedRun.scala:35)
	at sbt.ScriptedRun.run$(ScriptedRun.scala:16)
	at sbt.ScriptedRun$RunV1.run(ScriptedRun.scala:88)
	at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3(ScriptedPlugin.scala:189)
	at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3$adapted(ScriptedPlugin.scala:178)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
	at sbt.Execute.work(Execute.scala:292)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: sbt.internal.scripted.TestException: {line -1}  Command failed: Remote sbt initialization failed
	at sbt.scriptedtest.BatchScriptRunner.processStatement(BatchScriptRunner.scala:60)
	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$5(ScriptedTests.scala:225)
	... 48 more
[error] stack trace is suppressed; run last sbtScalaNative / scripted for the full output
[error] (sbtScalaNative / scripted) Failed tests:
[error] 	scala3/cross-version-compat
[error] Total time: 372 s (06:12), completed 20 Sep 2023, 17:09:43
```

Right before that I get a `java.lang.ExceptionInInitializerError`:

```
error] java.lang.ExceptionInInitializerError
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:467)
[error] 	at sbt.compiler.Eval$.getModule(Eval.scala:607)
[error] 	at sbt.compiler.EvalDefinitions.values(Eval.scala:58)
[error] 	at sbt.internal.DefinedSbtValues.$anonfun$values$1(LoadedSbtFile.scala:50)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
...
```

Running the tests with Scala 3.3 ends up with the same error as above.

**Comment by LeeTibbert** [comment]
@kyouko-taiga 

Thank you for the configuration information.  I will try to replicate when the day cools down, or tomorrow
morning.

> I'm using Scala 2.12.18, JDK 17, and LLVM 16.0.6. I'm running macOS 13.5.2 on an Apple M2.

All this looks reasonable.   Different errors on different runs/tasks is concerning.

Background:

 I do much of my development work on an Apple M1. I think the macOS is now
something like 13.5.3 or 4.  I do development using a series of JDKS, usually 20 and Scala 3.3.0.
To verify a proposed PR, I fall back to Scala 2.12.18 with (latest) JDK 8.

I think I had a problem with LLVM 16.n and fell back to LLVM 15.latest.  I installed LLVM 17.0.1 on
that machine yesterday, but have not built anything.  Memory seemed to be that I saw a lot
of scary linker(?) missing(?) symbol errors with LLVM 16, so I created an Issue and fell back
to LLVM 15.0 because I could not take the interrupt then.

The thing to know is that LTO with release-fast or release-full is broken on macOS for
a long time now. There are a couple of Issues on that. Not everything can get done at once.

I seem to remember it never getting past link. You are getting an executable, so you appear
to be well past that.

More when I have actual data.

**Comment by ekrich** [comment]
I tried to run `test-all` and it was a disaster too on latest. I will retry on Java 17

MacOS 12.6.7
```
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```
% java --version
openjdk 21 2023-09-19 LTS
OpenJDK Runtime Environment Corretto-21.0.0.35.1 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.0.35.1 (build 21+35-LTS, mixed mode, sharing)
```

**Comment by LeeTibbert** [comment]
Having encountered lots of smoke with Clang 16.0.6 and Java 21-ga, let me/us establish a working macOS baseline
and then ring the changes.

I am using the `sbtScalaNative/scripted` for my first set of attempts.  When working, they take
forever to execute, but I want to start off close to the presenting problem.

##### Environment:

Hardware: macOS M1 
OS:             Ventura - 13.5.2
LLVM:         16.0.6 via brew
JDK:            Various Azul Zulu versions



###### Fails
 sbt "++2.12.18; shell"         
[info] welcome to sbt 1.9.6 (Azul Systems, Inc. Java 1.8.0_382)

Result: 21 or so succeed, then:
```
[info] Running scala3/cross-version-compat
[error] [info] [launcher] getting org.scala-sbt sbt 1.6.2  (this may take some time)...
[error] [info] [launcher] getting Scala 2.12.15 (for sbt)...
[info] [info] welcome to sbt 1.6.2 (Azul Systems, Inc. Java 1.8.0_382)
[info] [info] loading settings for project sbt_1b45bd8-build from scala-native.sbt ...
[info] [info] loading project definition from /private/var/folders/x8/mktm_yyn3rdbkflp56d50w240000gn/T/sbt_1b45bd8/project
[error] java.lang.ExceptionInInitializerError
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
```

**Comment by LeeTibbert** [comment]
Next steps:


1) There may be a couple of types of breakage, but the easily reproducible one appears to 
    be `scala3/cross-version-compat`.  To early to rule out JVM, LLVM, and OS combinations,
    but that scripted test appears to be good starting place.
   
    I believe that I have seen the `cross-version-compat` error on both macOS & Linux.

    The errors look like they are in JVM, not SN, so it would be good to understand what that test is doing.
    Through the smoke, not yet having seen the detailed code, it appears to be switching SBT versions
    to 1.6.mumble.  The sbt 1.9.4 currently being used by SN might not like that.

    * The SBT 1.9.4 being used by SN might need to be upgraded to the current 1.9.6

2) I need to look at what is currently succeeding in CI, both on Linux & macOS.

**Comment by LeeTibbert** [comment]
@kyouko-taiga

I believe the "get you up and running answer" is that one of the tests invoked by
`sbtScalaNative/scripted` is busted, both on macOS & Linux.  It is probably broken
on Windows, but I can not test there.    Yes, we, Scala Native, need to understand and
fix that.

`test-runtime` and `test-tools` worked for me on macOS. I used LLVM 15.0.7 tonight. I think
I have been using 16.0.6 for months in my day to day work there.  `scripted` is a somewhat
strange land.  Did you happen to start there or did you have some intent/need for `scripted`?

You could start getting your feet wet by using Scala 3.3.0, JVM 17.0, & LLVM 15 (I think 16 will work also). I am waiting
for LLVM 17 to show up for macOS, so I do not know if that works.

Running tests such as `tests3/testOnly *.ProcessTest` or `tests3/test` should allow you to work on and test 
individual components whilst we sort out this Issue. 

Normally an anonymous person would hijack the conversation at this point and suggest commenting out
the offending `compat` test for the purposes of individual development.  However, `scripted` is so sensitive
that such an anonymous person cowers in the corner in fear of even thinking of it, much less touching or hacking it.

More as I/we discover it.

**Comment by LeeTibbert** [comment]
Curious,  a macOS `test-scripted` (as opposed to the `sbtScalaNative/scripted` in the base note)
just succeeded:  SN 3.3.0, JVM welcome to sbt 1.9.4 (Azul Systems, Inc. Java 1.8.0_382), clang 15.0.7.

Was that a fluke or configuration luck?  Why did Eric's `test-all` fail?

**Comment by kyouko-taiga** [comment]
> I believe the "get you up and running answer" is that one of the tests invoked by
sbtScalaNative/scripted is busted, both on macOS & Linux.

OK, noted.

> Did you happen to start there or did you have some intent/need for scripted?

I started there. I've been looking for a way to confirm that my setup was properly configured. I'd like to get a sense of the "standard development workflow" before I write any code, so that I can know when I'm breaking something.

> Running tests such as tests3/testOnly *.ProcessTest or tests3/test should allow you to work on and test individual components whilst we sort out this Issue.

Is there a list of that components somewhere that I could read?

> test-runtime and test-tools worked for me on macOS.

I successfully ran `test-runtime` and `test-tools` with LLVM 15.0.7.

`test-runtime` failed with a linker error with Scala 2.2.18/3.3 and LLVM 16.0.6.
```
dyld[4989]: Symbol not found: __ZNSt20bad_array_new_lengthC1Ev
Referenced from: <EB0B1623-0B83-3568-AF21-ADD7429D5232> scala-native/sandbox/.3/target/scala-3.3.0/sandbox-out
  Expected in:     <no uuid> unknown
```
Similar story for `test-tools`.

FWIW, it looks like a C++ symbol to me so I wouldn't be surprised if there's a missing `-lc++` flag somewhere.

`test-all` failed for Scala 2.2.18/3.3. and LLVM 15.0.7 with a null pointer exception:
```
[error] java.lang.NullPointerException: Cannot invoke "scala.tools.nsc.backend.jvm.ClassfileWriters$ClassfileWriter.close()" because the return value of "scala.tools.nsc.backend.jvm.PostProcessor.classfileWriter()" is null
```
IIUC `test-all` is running scripted tests too so a failure is barely really surprising. What's concerning is that it seems to be yet another error so I don't know what to make of these results.

I got the link errors again with LLVM 16.0.6 , which isn't surprising.

All of these tests ran on `v0.4.15`. In summary:

| | `test-runtime` (2.2.18) | `test-runtime` (3.3) | `test-tools` (2.2.18) | `test-tools` (3.3) | `test-all` (2.2.18) | `test-all` (3.3) |
| :-- | :-: | :-: | :-: | :-: | :-: | :-: |
| LLVM 15.0.7 | OK | OK | OK | OK | NullPointerException | NullPointerException |
| LLVM 16.0.6 | link error | link error | link error | link error | link error | link error |

**Comment by LeeTibbert** [comment]
@kyouko-taiga 

Thank you for the information. It is helpful.

Sorry to be short, I only have a few minutes now.  I hope to have more time for this tonight.
To cut down on what is sure to be your frustration, I want to get at least a small reply off to you.
I hope I add more light than frustration.  If something I say does not make sense, just skip/forget it, eh?

re 16.0.6 and, presumably, 17.0.1 "link error":   

I believe that is a, regrettable, "known" error. We do not like such but that one has not yet risen to
the top (bottom??) of the stack. I thought I had created an Issue to track it, but can not find it now.
I was told that it was harmless, but do not quite  believe that. My 16.0.6 runs seem to have been working
even with it present, so I have become "blind" to it.  

re: Null pointer exception

That one is more concerting.  It should be working.  I propose we focus on the `scripted` part
and address that concern in a second (twentieth??) pass.  That is probably at least part of the 
concern I had that we were/are seeing more than one problem.

Thank you for capturing that the failure is in 16.0.6 but not 15.0.7.

re: workflow
 ```I started there. I've been looking for a way to confirm that my setup was properly configured. I'd like to get a sense of the "standard development workflow" before I write any code, so that I can know when I'm breaking something. One way to test everything before pushing changes is typically part of that workflow.
```
I understand and applaud  the approach.  At the start of working on each PR, I myself try to do a "baseline" run
to see if I can get a clean SN build, try to replicate the problem, then write one or more Tests to capture the replication.
Then I do a private trial fix and run the Test(s) again. Problem should not appear, everything else should work, and there should be no new problems ;-)    

re: No LTO & release-fast or release-full on macOS

I have probably mentioned it two or three times already, but in case I have not.  The huge "known" pothole in SN
on macOS is that long term optimization (LTO) is hard broken when using release-fast & kin.


re: test-all

I will have to see its component actions these days to understand what it is doing these days and
why at least one of its components is failing NPE.

re: project list.

I think that sbt has a "sbt> project" or "sbt> projects" command which gives the highest level, such as "javalib", "clib",
"nativelib" and such.  Under some/most there are hidden ".3"  and/or ".2mumble" directories.  So, to test
using Scala 3 (but not yet 3.3.1) one would use "sbt> tests3/testOnly *.ProjectTest" or "sbt> tests3/test".

I never use it and it has changed a lot since the last time I have, so I do not know what the toplevel "sbt> test"
does.  One can watch the output to tell what Scala version, etc, is in use. (probably have to look at directory names.)

Some time using a "ls -l -a" (ls -ell -ah) will give you an idea of the directory structure.

Yes, someday, the Contributor's Guide should give a description or snapshot picture of the directory organization 
and intent.

Closing:

Thank you for your patience.  

We will get this sorted out and make it less imposing  for the next people wanting to start contributing.

Now that you have shown that SN macOS build seems to be working with LLVM 15.0.7, my suggestion is
that you stay with that version and pick a problem that is interesting to you and walk through the rest
of the PR process.  The idea, for both/all, of us would be to get you/us to early success.

**Comment by LeeTibbert** [comment]
PS:  
I believe, but will check when I can, that "test-all" and friends work (no Scala 3 & JDK 21 yet) on Linux 64 bit builds.

Not much use to people wanting to develop on macOS, but gives baseline conditions and/or existence proofs.

**Comment by kyouko-taiga** [comment]
Thank you for your answers.

> Sorry to be short, I only have a few minutes now. I hope to have more time for this tonight.

No worries. Your answers were anything but "short". I really appreciate your help on this issue.

> Now that you have shown that SN macOS build seems to be working with LLVM 15.0.7, my suggestion is
that you stay with that version and pick a problem that is interesting to you and walk through the rest
of the PR process.

I still don't have a way to run "all" tests to make sure my environment is properly configured, but I guess I can start from where I'm at and report when things go wrong(er).

I strongly believe that it would be very valuable to make sure we have a way to bring a fresh machine to a point where it can run a complete test suite (for some definition of "complete") with a single command. I'm sure we'll get there eventually ;)

> I believe, but will check when I can, that "test-all" and friends work (no Scala 3 & JDK 21 yet) on Linux 64 bit builds.

Okay, I will try to setup a VM to see if I can manage to run everything smoothly at least once. I'll report here if I don't.

**Comment by ekrich** [comment]
I usually run `sandbox2_13/run` to check the distro. This is the newest version that doesn't require extra compiling like for Scala 3. `tests2_13/test` would be second if working on this part of the distro.

**Comment by LeeTibbert** [comment]
> Okay, I will try to setup a VM to see if I can manage to run everything smoothly at least once. I'll report here if I don't.

Sounds like a plan.

>  still don't have a way to run "all" tests to make sure my environment is properly configured, 
Agreed, wholeheartedly (as one who brings up machines on different osen, such as FreeBSD).
I think that is/was at least one intent of "test-all". Unfortunatly, we are running into bugs/unforseen_changes
in the "proof" code.

For reference:
`project/Commands.scala`
```
  lazy val testAll = Command.command("test-all") {
    "test-tools" ::
      "test-mima" ::
      "test-runtime" ::
      "test-scripted" ::
      "publish-local-dev" :: _
  }
```
Ideally and as a goal the full "test-all" should succeed in your environment.

A minimal command line verification of your environment would be "sbt> test-tools", "sbt> test-runtime", 
"sbt> test-scripted".    That would skip any bugs in the other two, CI will pick those up in its precisely controlled
(some will detect irony here) environment.

**Comment by ekrich** [comment]
I reran `test-all` with Java 17 and got this.
```
[error] (sbtScalaNative / scripted) Failed tests:
[error] 	run/build-library-dynamic
[error] 	run/build-library-static
[error] 	run/execution-context
[error] 	run/java-io-file-output-stream
[error] 	run/java-net-server-socket
[error] 	run/java-net-socket
[error] 	run/junit
[error] 	run/link-order
[error] 	run/link-stubs
```

**Comment by LeeTibbert** [comment]
re: `test-all`  scala 2.12.18, JDK 8, LLVM 15.0.7

result:  failure
 I think in a "publish" phase. Earlier "test-tools", "test-runtime", and "test-scripted" all suceeded.
```
 Expected ';'
[error] ++Used command needs explicit full Scala version as an argument publishLocal
[error]    
```

We should probably look at which test phase builds the docs.  That phase introduces a requirement
that the developer's machine have a working, recent Sphinx installed.  I am not sure if the Contributor's
Guide specifies that.

I saw and briefly read PR #3496, which moves the discussion along.  I have (more than) run out of time 
now. When I can, I think I will post there a suggestion for a two (or more) phase stepped approach:
First a rough smoke test, such as Eric suggested, then building & reading docs, then working towards `test-all`
in a baseline SN, JVM, lowest configuration, then `test-all` in a highest version configuration.

Thoughts for me to puzzle & refine as I deal with Real Life.

**Comment by LeeTibbert** [comment]
PR #3498 attempts to take a slice off the top of this Issue.  `test-all` calls `publish-local-dev`. One of the
failures in this Issue was in the latter command.

`test-all` now works for me on macOS Ventura (13.latest) and Ubuntu 23.04, using LLVM/clang 15.

Next sprint, I want to try LLVM/clang 16.0.6.  `tests3/test` has been working for me for ages, so I need
to figure out if `test-all` or other are failing.

When brew has LLVM@17, I would like to try that also.

###### Bookkeeping
The "known" issues that we can factor out:
1) "harmless" missing symbols with LLVM 16.n
2) The attractive nuisance of LTO & release=fast not working.
     I would really like to wall that combination off on macOS but am trying to keep from
     getting distracted and wasting a week or more.

**Comment by LeeTibbert** [comment]
@kyouko-taiga  It will be interesting to see what happens on your systems once PR #3498 gets merged.

The `publish-local-dev` command inside `test-all`  builds documentation. Do you have Sphinx set up
on your system?  I no longer remember if the Contributor's Guide describes how to set it up or if any
such description is current/working.  I believe there is a script in `scripts` which attempted to setup 
Sphinx for the doc build if it was not present.  First and each time I tried that, it failed.

I still need to try the exact `sbtScalaNative/scripted` of the base note.  That should work and not
set off any dependency for Sphinx. I should probably try using LLVM 15 before I upgrade.

From looking at the code in `Commands.scala`, it looks like the command intended to be used by
a SN developer is `test-scripted`.  It looks like `test-scripted` does some setup and provides some args to the internal `sbtScalanative/scripted`.   The issue here might be to make it harder for a human to get to the `sbtScalanative/scripted` command.  More as I discover it.

```
// Commands.scala

     setScriptedLaunchOpts ::
        s"sbtScalaNative/scripted ${scalaVersionTests} run/*" ::
        state
```

**Comment by LeeTibbert** [comment]
I've done some more exploration of  the `sbtScalanative/scripted` from the base note. I think the answer
is a cleaned up version of something like:
 
`sbtScalanative/scripted` command is not intended to be used directly. The command intended for 
general use is `test-scripted`.   If one does use  `sbScalanative/scripted`, the proper arguments 
must be supplied. 

At this point, I think we can not wall it off entirely.
I will have to think through a rest period, or many, if there is some way we can make that command
harder to find/fall_into.    Sometimes my backbrain is far more clever than my forebrain, inspiration may
come.

Folks,  Thoughts here?


I think my next sprint should start with LLVM 16.0.6 (or 17).  So far JDK zulu 21 has not caused problems.

**Comment by LeeTibbert** [comment]
I am working my  way through the macOS configuration matrix.  Sure are a **lot** of cells! I should have
paid better attention in Combinatorics class.

Recall: the various `test-foo` commands set Scala to 2.12.18.

Using brew LLVM 16.0.6, Java 8 `test-scripted` seems to work. I have to try `test-tools` and `test-runtime`.

Using Java 21, `test-scripted` fails. It looks like an sbt Java failure, not directly an SN failure. I may try sbt 1.9.6
to see if that helps.


I am not sure if I am still seeing the link missing symbol errors that I was seeing with LLVM 16.n at one point.
My eyes are pretty blurry at this point.

**Comment by kyouko-taiga** [comment]
> Do you have Sphinx set up on your system?

I don't but I can make that happen.

I don't remember reading about Sphinx in the contributors' guide but I'll try to figure out my way and report back if I'm stuck.

> I will have to think through a rest period, or many, if there is some way we can make that command
harder to find/fall_into. Sometimes my backbrain is far more clever than my forebrain, inspiration may
come.
>
> Folks, Thoughts here?

You mean `sbtScalanative/scripted`?

I only found it because it was mentioned in the contributors' guide. If that gets replaced by `test-scripted` then new comers like me are unlikely to try `sbtScalanative/scripted` until they get more acquainted with the project.

**Comment by LeeTibbert** [comment]
@kyouko-taiga   I am deep into debugging, sorry.  I will answer your helpful 2023-09-22 post above after I surface

@ekrich You may be interested in this. 

### BEWARE

The failure in `test-scripted` that a number of us have been seeing, across architectures, when using
JVM (above?  equalTo) Java 17 appears to be a year+ old bug in the sbt version (1.5.8) being used (at least with 
Scala 2.12.18) by scripted: (see)[https://github.com/sbt/sbt/issues/6925]. The recommended/only solution 
is to upgrade the sbt version used to at least 1.6.0.

I am off to figure out where scripted is setting its sbt version and the interaction/requirements of 
the Scala version (2.12.18 at one pole, 3.3.0 at the other).

I want to get this info posted to this discussion in the hope of saving other people time & aggravation,
especially the latter. 

```
The [info] Running 21 / 21 (100.00%) scripted tests with RunFromSourceMain
[info] Running run/C_argc_argv-to-java_args
[error] [info] [launcher] getting org.scala-sbt sbt 1.5.8  (this may take some time)...
[error] [info] [launcher] getting Scala 2.12.14 (for sbt)...
[error] java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
[error] 	at sbt.xMain.run(Main.scala:46)
```

**Comment by LeeTibbert** [comment]
A quick update.  

LLVM 17.0.1 and JVM 21 appear to be innocent on Scala 2.12.18 on macOS (and IIRC, Linux).  With
sufficient hackery to address an SBT bug and Scala Native's usage of "known buggy" sbt versions,
`test-scripted` joins `test-tools` and `test-runtime` in working just fine. (I do not remember if I ran
`test-all`, but given those three work and the recent merge of my/our PR, I expect that to work.)

I did not do a detailed search of the log files, but from a visual "Poke me in the eye" review, it appears
that the "ignore me" missing symbol link errors no longer occur with LLVM 16.0.6 and 17.0.1. Not
proof, but hope of proof.

The tests could not be run on Scala 3.n because that does not yet support Java 21.  I thought I had
used Scala 3.3.0 with Java 20 (well, a very early 21-ea). In a future activity cycle I may try that.

Also in a future engineering cycle I need to convert the hackery which got sbt working here
to Software Engineering and a PR.  Memento Mori.

**Comment by LeeTibbert** [comment]
@kyouko-taiga 

Whilst chasing sbt version settings, I came across `${projectRoot}/.github/workflows/build-docs.yml`.
It uses python pip to install sphinx and recommon mark and gives versions.

Not the most elegant intro and can only be read, not executed, but might give you a starting point.
(final step of `test-all` builds at least Scala docs, if not SN docs. I think, but do not know, that you
might need it.  You certainly need it to document changes in almost any PR).

Hope this helps.  Progress comes dearly.
