### ISSUE TITLE
ClassCastException: scala.scalanative.runtime.IntArray cannot be cast to scala.scalanative.runtime.ObjectArray

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#3504]
### `Main.scala`

```scala
object Main {
  def main(args: Array[String]): Unit = {
    val xs: Array[Int] = (0 to 300).toArray
    xs.sortBy(i => -i)
  }
}
```

### `build.sbt`

```scala
scalaVersion := "3.3.1"

enablePlugins(ScalaNativePlugin)
```

### `project/build.properties`

```properties
sbt.version = 1.9.6
```

### `project/plugins.sbt`

```scala
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.15")
```

### sbt run

```
java.lang.ClassCastException: scala.scalanative.runtime.IntArray cannot be cast to scala.scalanative.runtime.ObjectArray
	at java.lang.StackTrace$.currentStackTrace$$anonfun$1(Unknown Source)
	at java.lang.StackTrace$$$Lambda$2.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
	at scala.Array$.copyAs(Unknown Source)
	at scala.collection.ArrayOps$.boxed$1(Unknown Source)
	at scala.collection.ArrayOps$.sorted$extension(Unknown Source)
	at scala.collection.ArrayOps$.sortBy$extension(Unknown Source)
	at Main$.main(Unknown Source)
	at Main.main(Unknown Source)
	at <none>.main(Unknown Source)
```

**Comment by xuwei-k** [comment]
note:

- https://github.com/scala/scala/blob/e67d287447c09720468f8bebcb0302bd92d75f43/src/library/scala/collection/ArrayOps.scala#L590C35-L590C54
- https://github.com/scala/scala/blob/e67d287447c09720468f8bebcb0302bd92d75f43/src/library/scala/collection/ArrayOps.scala#L177

**Comment by WojciechMazur** [comment]
The issue is here mostly due to the fact that we don't correctly map the Scala/JVM typesystem. The code `classOf[Any].isAssignableFrom(classOf[Int])` on Native yield true, but it should result in false. We can quick fix it, but it would be suboptimal right now. I'm working on some better alternative, propbably involving more impactfull changes to areas how Class info are generated.

**Comment by xuwei-k** [comment]
another `Array.copyAs` bug example

https://github.com/scala/scala/blob/e67d287447c09720468f8bebcb0302bd92d75f43/src/library/scala/collection/ArrayOps.scala#L1134-L1135


```scala
object Main {
  def main(args: Array[String]): Unit = {
    Array(1).appended("a")
  }
}
```

```
java.lang.ClassCastException: scala.scalanative.runtime.IntArray cannot be cast to scala.scalanative.runtime.ObjectArray
	at java.lang.StackTrace$.currentStackTrace$$anonfun$1(Unknown Source)
	at java.lang.StackTrace$$$Lambda$2.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
	at scala.Array$.copyAs(Unknown Source)
	at scala.collection.ArrayOps$.appended$extension(Unknown Source)
	at Main$.main(Unknown Source)
	at Main.main(Unknown Source)
```
