### ISSUE TITLE
Loading module in multithreading mode should be more aware when init fails

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3591]
Let's take a look at following code, where we create n threads which shall reference the object module. The 1st thread to access the module would try to initialise it (calculcate `val init` in our case). All the other threads would wait until the object would be initialized

```scala
object Deadlocking {
  val init = {
    println(s"start init by ${Thread.currentThread()}")
    Thread.sleep(1000)
    throw new RuntimeException()
    println("init done")
    42
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    List.tabulate(8) { n =>
        val t = new Thread(() => {
          println(s"start thread $n")
          println(s"thread $n, result=${Deadlocking.init}")
          println(s"thread done $n")
        })
        t.setName(s"thread-$n")
        t
      }
      .tapEach(_.start())
      .foreach(_.join())
  }
}
```

On the JVM when the initialisation would fail, every thread waiting for the `Deadlocking` would fail with an exception: 
```
start thread 0
start thread 1
start thread 2
start thread 3
start thread 4
start thread 5
start init by Thread[thread-0,5,main]
start thread 6
start thread 7
Exception in thread "thread-0" Exception in thread "thread-4" Exception in thread "thread-2" java.lang.ExceptionInInitializerError
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
Exception in thread "thread-5" java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
Exception in thread "thread-6" java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
Exception in thread "thread-7" java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
Exception in thread "thread-1" java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
Exception in thread "thread-3" java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
java.lang.NoClassDefFoundError: Could not initialize class Deadlocking$
        at Test$.$anonfun$1(Test.scala:21)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "thread-0"]
        at Deadlocking$.<clinit>(Test.scala:7)
        ... 2 more
```

However, on the Scala Native if the initialization fails, all the other threads assume that initialization was finished successfully, and would try to get an module instance, which would lead to segmentation fault. 
```
start thread 1
start init by Thread[3,thread-1,5,main]
start thread 0
start thread 3
start thread 4
start thread 5
start thread 7
start thread 2
start thread 6
Exception in thread "thread-1"java.lang.RuntimeException
        at Deadlocking$.<init>(Test.scala:2)
        at <none>.__scalanative_loadModule(/Users/wmazur/projects/scala-native/sandbox/.2.13/target/scala-2.13/native/dependencies/nativelib_native0.5.0-SNAPSHOT_2.13-0.5.0-SNAPSHOT-0/scala-native/module_load.c:91)
        at <none>._SM12Deadlocking$G4load(Test.scala:2)
        at Test$.$anonfun$main$2(Test.scala:20)
        at Test$$$Lambda$4.run(Test.scala:20)
        at java.lang.Thread.run(Thread.scala:245)
        at scala.scalanative.runtime.NativeThread$.threadEntryPoint(NativeThread.scala:126)
        at scala.scalanative.runtime.NativeThread$.$anonfun$threadRoutine$1(NativeThread.scala:119)
        at <none>._SM49scala.scalanative.runtime.NativeThread$$$Lambda$1G17$extern$forwarder(NativeThread.scala:118)
        at <none>.ProxyThreadStartRoutine(/Users/wmazur/projects/scala-native/sandbox/.2.13/target/scala-2.13/native/dependencies/nativelib_native0.5.0-SNAPSHOT_2.13-0.5.0-SNAPSHOT-0/scala-native/gc/immix/ImmixGC.c:105)
        at <none>._pthread_start(Unknown Source)
[error] java.lang.RuntimeException: Nonzero exit code: 139
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$18(ScalaNativePluginInternal.scala:276)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$16(ScalaNativePluginInternal.scala:276)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$16$adapted(ScalaNativePluginInternal.scala:253)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

We should propagate information about failed initialization using exceptions, instead of allowing for segmentation fault.

**Comment by tanishiking** [comment]
@WojciechMazur Thanks for the reproducible examples!

It seems there are two parts to the fix (1) catch an uncaught exception thrown during module initialisation and re-throw it wrapped by `ExceptionInInitializerError` so we can tell it's thrown during module initialisation. (2) Notify other threads that the module initialisation has failed.

While I haven't delved into (2), I have a brain dump/question regarding (1)

- We can catch an uncaught exception thrown during module initialisation. probably here? https://github.com/scala-native/scala-native/blob/644fbd5bb9d40329cf6587bb782dec9dd49aeeaa/nativelib/src/main/resources/scala-native/module_load.c#L101
  - We can catch an uncaught exception thrown in a thread here https://github.com/scala-native/scala-native/blob/644fbd5bb9d40329cf6587bb782dec9dd49aeeaa/nativelib/src/main/scala/scala/scalanative/runtime/NativeThread.scala#L133-L141
  - We need to know that **exception is thrown during module initialisation**.
  - The idea is to catch an exception during module initialisation and re-throw it wrapped by `ExceptionInInitializerError'.
  - **(Question)** However, where should we catch and re-throw the exception during module initialisation?  What I know is:
    - The `load` method like `<none>._SM12Deadlocking$G4load` is generated in https://github.com/scala-native/scala-native/blob/644fbd5bb9d40329cf6587bb782dec9dd49aeeaa/tools/src/main/scala/scala/scalanative/codegen/Generate.scala#L429-L455 
    - but I have no idea who calls this `load` method 🤔 once I know who calls it, maybe we can wrap it with try-catch and re-throw an exception wrapped with `ExceptionInInitializerError`.

**Comment by WojciechMazur** [comment]
The easiest way to catch the exception from the module constructor would be probably to introduce try-catch block in `__scalanative_loadModule`, but it would mean we'd need to convert this code to C++. We should be able to catch here the `scalanative::ExceptionWrapper` (defined in eh.cpp) and extract the underlying pointer to Scala Native exception. At this point we potentially can store the cought exception in the `slot` dedicated for given module. 
Now if the slot would contain null (`if (module == NULL)`), we would now the object was not initialized
When it would contain expected value (`classOf[T]`, `if (*module == classInfo)) then we would be able to just return the initialized instance, otherwise we would now that initialization failed and the slot contains exceptions. 

We potentially can provide a CFuncPtr to the native code which would be used to wrap the exception thrown by the `ctor` 
into the `ExceptionInInitializerError`, which later can be thrown using the `scalanative_throw`

If we'd like to catch the exception in the `NativeThread.uncoughtExceptionHandler` we would need to make sure that `InitializationContext ctx = {}` defined in `__scalanative_loadModule` would survive the thread unwind. Probably it would be better to handle it earlier.  

> but I have no idea who calls this load method 

The call to load is generated by lowering `Op.Module` which is a high-level operation using the synthetic code created in `Generate`. If we'd guard each call to `<module>G4load` with try-catch block (unwinding at the NIR level) we'd probably generate much more code, and the binary size would increase lineary to number of defined modules and their references. 

Becouse of that, I think that it would be to catch exception as early as possibly in the  `__scalanative_loadModule` by wrapping the `ctor` into try-catch block as desribed before and adjusting the waitForInitialization logic
