### ISSUE TITLE
Object monitors differ in `enter` semenatics from the JVM

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3594]
Some of failing CI tests, are caused by failing `scala.collection.convert.MapWrapperTest` which spins 2 threads performing concurrent access to hash map. One of them sets default string, other one modifies it (doubles).  
It can minimized to the following snippet: 
```scala
import scala.util.chaining._
object Test {
  @volatile var lokiCounter = 0
  @volatile var mainCounter = 0
  @volatile var string = "Value"
  def main(args: Array[String]): Unit = {
    val limit = 100 // retries until trigger

    class Loki extends Runnable {
      @volatile var done = false
      def run(): Unit = {
        while (!done) {
          Test.synchronized {
            // println(Thread.currentThread())
            string = "Value"
            lokiCounter += 1
          }
        }
      }
    }
    val loki = new Loki
    val runner = new Thread(loki).tap(_.start)
    for (i <- 1 to limit) {
      Test.synchronized {
        // println(Thread.currentThread())
        string = string + string
        mainCounter += 1
      }
    }
    loki.done = true
    runner.join()
    println(lokiCounter -> mainCounter)
  }
}

If we'd run it on the JVM we'd see that `Loki` thread enters synchronized scopes multiple order more times. The subsequent access to the critical section by the main thread might lead to exception when string length would overflow Int.MaxValue but it's a rather spurious event.
```scala
while [[ true ]]; do scala-cli run sandbox/src/main/scala/Test.scala;  done
(6324426,100)
(6669529,100)
(8578085,100)
(6206552,100)
(6431689,100)
(7002807,100)
(4992639,100)
(6865195,100)
(7104803,100)
(7901863,100)
Exception in thread "main" java.lang.OutOfMemoryError: Overflow: String length out of range
        at java.base/java.lang.StringConcatHelper.checkOverflow(StringConcatHelper.java:57)
        at java.base/java.lang.StringConcatHelper.mix(StringConcatHelper.java:138)
        at java.base/java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:420)
        at Test$.main$$anonfun$1(Test.scala:26)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.scala:18)
        at scala.collection.immutable.Range.foreach(Range.scala:190)
        at Test$.main(Test.scala:29)
        at Test.main(Test.scala)
````

When executing using native the `Loki` thread is not entering critical section that often: 
```scala
while [[ true ]]; do ./sandbox/.2.13/target/scala-2.13/sandbox; done
(26158,100)
(192873,100)
(450,100)
(190361,100)
Exception in thread "main"java.lang.NegativeArraySizeException
        at scala.scalanative.runtime.CharArray$.alloc(Arrays.scala:264)
        at java.lang.String.concat(String.scala:225)
        at Test$.$anonfun$main$2(Test.scala:24)
        at Test$$$Lambda$2.apply(Test.scala:24)
        at scala.Function1.apply$mcVI$sp(Function1.scala:72)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:185)
        at Test$.main(Test.scala:7)
        at Test.main(Test.scala:7)
        at <none>.main(unknown:2)
```

There are 2 main areas which might lead to this behaviour: 
 1. `BasicMonitor` aka ThinLocks (https://dl.acm.org/doi/10.1145/277652.277734) when Locking with Contention - Thread A waitsactively (spin lock) for Thread B to exit critical section and then promotes thin lock to fat lock. Seems like current backoff with sleeping between 1000ns-0.125ms leads to multiple missed oportunities to inflate monitor. Thread B is not able to inflate monitor as there is no way to pass information about waiting threads (only active owner of thin object monitor can modify it's state). Eliminating backoff seems to reduce probability of deadlocking in this phase. 
 2. `ObjectMonitor` aka FatMonitor, probably when deciding which thread should be waked up. It's possible that thread A which exists monitor and wakes up it's successor takes ownership over object monitor too soon, and thus does not allow thread B to enter critical section, which leads to suspending execution of thread B again.

**Comment by WojciechMazur** [comment]
Low number of iterations when entering the monitor might also be coused by allocation a new `ObjectMonitor.WaiterNode` on the Heap (using GC). Alternatively we could try to preserve a pool of `WaiterNode`s or allocated them as a structs to lower the GC contention.
