### ISSUE TITLE
`toolsBenchmarks3 / Jmh / run` crashes

### ISSUE THREAD

**Issue by tanishiking** [scala-native/scala-native#3600]
While 2.12 and 2.13 works fine, toolsBenchmark3 seems to fail on `toolsBenchmarks3 / Jmh / run`.

```
[error] java.lang.AbstractMethodError: Receiver class scala.scalanative.codegen.llvm.MetadataCodeGen$Writer$$$Lambda$747/0x00000008012c1328 does not define or inherit an implementation of the resolved method 'abstract void writeMetadata(scala.scalanative.codegen.llvm.Metadata, scala.scalanative.codegen.llvm.MetadataCodeGen$Context)' of interface scala.scalanative.codegen.llvm.MetadataCodeGen$Writer.
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen$Writer.write(MetadataCodeGen.scala:326)
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen$InternedWriter.$anonfun$4(MetadataCodeGen.scala:358)
[error]         at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen$InternedWriter.intern(MetadataCodeGen.scala:361)
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen.dbg$$anonfun$1(MetadataCodeGen.scala:34)
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen.dbg$$anonfun$adapted$1(MetadataCodeGen.scala:34)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen.dbg(MetadataCodeGen.scala:34)
[error]         at scala.scalanative.codegen.llvm.MetadataCodeGen.dbg$(MetadataCodeGen.scala:19)
[error]         at scala.scalanative.codegen.llvm.AbstractCodeGen.dbg(AbstractCodeGen.scala:27)
[error]         at scala.scalanative.codegen.llvm.AbstractCodeGen.genDebugMetadata(AbstractCodeGen.scala:84)
[error]         at scala.scalanative.codegen.llvm.AbstractCodeGen.gen$$anonfun$1(AbstractCodeGen.scala:55)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.scalanative.io.VirtualDirectory$NioDirectory.write(VirtualDirectory.scala:105)
[error]         at scala.scalanative.io.VirtualDirectory$NioDirectory.write$(VirtualDirectory.scala:75)
[error]         at scala.scalanative.io.VirtualDirectory$LocalDirectory.write(VirtualDirectory.scala:143)
[error]         at scala.scalanative.codegen.llvm.AbstractCodeGen.gen(AbstractCodeGen.scala:70)
[error]         at scala.scalanative.codegen.llvm.CodeGen$.separate$1$$anonfun$2$$anonfun$1(CodeGen.scala:89)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
[error]         at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by WojciechMazur** [comment]
That might explain some other issue I've seen when trying to link native version of tools. No idea how it is possible though. Maybe a bug in compiler? We should try to minimize it at some point

**Comment by WojciechMazur** [comment]
Probably it might be related to this bug: https://github.com/lampepfl/dotty/issues/15402
