### ISSUE TITLE
Unit test error: java.util.NoSuchElementException: key not found: Local(5)

### ISSUE THREAD

**Issue by mobilemindtec** [scala-native/scala-native#4016]
Hello,

I'm trying run unit tests on ScalaNative, but I'm getting this error with MUnit or JUnit. Any ideia?

```sbt
[[info] Linking (multithreadingEnabled=true, disable if not used) (2568 ms)
[info] Discovered 1488 classes and 9302 methods after classloading
[info] Checking intermediate code (quick) (73 ms)
[info] Optimizing skipped
[info] Generating intermediate code (with debug metadata) (1431 ms)
[info] Total (4496 ms)
[error] stack trace is suppressed; run last Test / nativeLink for the full output
[error] (Test / nativeLink) java.util.NoSuchElementException: key not found: Local(5)
[error] Total time: 66 s (01:06), completed Aug 6, 2024, 10:15:02 PM
sbt:mysql4s> last Test / nativeLink
[debug] Config(
[debug]  - baseDir:          /mnt/data/sources/scala/repos/mysql4s/target/scala-3.5.0-RC6
[debug]  - testConfig:       true
[debug]  - workDir:          /mnt/data/sources/scala/repos/mysql4s/target/scala-3.5.0-RC6/native-test
[debug]  - moduleName:       mysql4s
[debug]  - baseName:         mysql4s
[debug]  - artifactName:     mysql4s-test
[debug]  - artifactPath:     /mnt/data/sources/scala/repos/mysql4s/target/scala-3.5.0-RC6/mysql4s-test
[debug]  - buildPath:        /mnt/data/sources/scala/repos/mysql4s/target/scala-3.5.0-RC6/native-test/scala.scalanative.testinterface.TestMain-test
[debug]  - mainClass:        Some(scala.scalanative.testinterface.TestMain)
[debug]  - classPath:        List(/mnt/data/sources/scala/repos/mysql4s/target/scala-3.5.0-RC6/test-classes
[debug]                      /mnt/data/sources/scala/repos/mysql4s/target/scala-3.5.0-RC6/classes
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.5.0-RC6/scala3-library_3-3.5.0-RC6.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/test-interface_native0.5_3/0.5.4/test-interface_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/scala3lib_native0.5_3/3.5.0-RC6%2B0.5.4/scala3lib_native0.5_3-3.5.0-RC6%2B0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.5_3/0.5.4/nativelib_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/clib_native0.5_3/0.5.4/clib_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/posixlib_native0.5_3/0.5.4/posixlib_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/windowslib_native0.5_3/0.5.4/windowslib_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/javalib_native0.5_3/0.5.4/javalib_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.5_3/0.5.4/auxlib_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/munit_3/1.0.0/munit_3-1.0.0.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.14/scala-library-2.13.14.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/test-interface-sbt-defs_native0.5_3/0.5.4/test-interface-sbt-defs_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/junit-runtime_native0.5_3/0.5.4/junit-runtime_native0.5_3-0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/scalalib_native0.5_2.13/2.13.14%2B0.5.4/scalalib_native0.5_2.13-2.13.14%2B0.5.4.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/junit-interface/1.0.0/junit-interface-1.0.0.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/munit-diff_3/1.0.0/munit-diff_3-1.0.0.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar)
[debug]  - sourcesClasspath: List(/home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.14/scala-library-2.13.14-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.5.0-RC6/scala3-library_3-3.5.0-RC6-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/auxlib_native0.5_3/0.5.4/auxlib_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/clib_native0.5_3/0.5.4/clib_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/javalib_native0.5_3/0.5.4/javalib_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/junit-runtime_native0.5_3/0.5.4/junit-runtime_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/nativelib_native0.5_3/0.5.4/nativelib_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/posixlib_native0.5_3/0.5.4/posixlib_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/scala3lib_native0.5_3/3.5.0-RC6%2B0.5.4/scala3lib_native0.5_3-3.5.0-RC6%2B0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/scalalib_native0.5_2.13/2.13.14%2B0.5.4/scalalib_native0.5_2.13-2.13.14%2B0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/test-interface-sbt-defs_native0.5_3/0.5.4/test-interface-sbt-defs_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/test-interface_native0.5_3/0.5.4/test-interface_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-native/windowslib_native0.5_3/0.5.4/windowslib_native0.5_3-0.5.4-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/junit-interface/1.0.0/junit-interface-1.0.0-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/munit-diff_3/1.0.0/munit-diff_3-1.0.0-sources.jar
[debug]                      /home/ricardo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/munit_3/1.0.0/munit_3-1.0.0-sources.jar)
[debug]  - compilerConfig:   NativeConfig(
[debug]  - baseName:                
[debug]  - clang:                   /usr/bin/clang
[debug]  - clangPP:                 /usr/bin/clang++
[debug]  - linkingOptions:          [-L/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../lib, -lmysqlclient, -lresolv, -lssl, -lcrypto, -ldl, -pthread, -lz, -lzstd, -L/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../lib, -lssl, -lcrypto, -ldl, -pthread, -L/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../lib, -lz, -L/usr/local/lib, -L/usr/lib]
[debug]  - compileOptions:          [-I/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../include/mysql, -I/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../include, -I/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../include, -I/home/ricardo/.cache/sbt-vcpkg/vcpkg-install/x64-linux/lib/pkgconfig/../../include, -I/usr/local/include, -I/usr/include, -Qunused-arguments, -g]
[debug]  - targetTriple:            None
[debug]  - GC:                      immix
[debug]  - LTO:                     none
[debug]  - mode:                    debug
[debug]  - buildTarget              Application
[debug]  - check:                   false
[debug]  - checkFatalWarnings:      false
[debug]  - checkFeatures            true
[debug]  - dump:                    false
[debug]  - sanitizer:               none
[debug]  - linkStubs:               false
[debug]  - optimize                 false
[debug]  - incrementalCompilation:  true
[debug]  - multithreading           None
[debug]  - linktimeProperties:      []
[debug]  - embedResources:          false
[debug]  - resourceIncludePatterns: [**]
[debug]  - resourceExcludePatterns: []
[debug]  - serviceProviders:        []
[debug]  - optimizerConfig:         
[debug]     - maxInlineDepth:    32 functions
[debug]     - smallFunctionSize: 12 instructions
[debug]     - maxCallerSize:     2048 instructions
[debug]     - maxCalleeSize:     256 instructions
[debug] 
[debug]  - semanticsConfig:         SemanticsConfig(
[debug]     - finalFields: Relaxed
[debug]     - strictExternCallSemantics: false
[debug]     )
[debug]  - sourceLevelDebuggingConfig: SourceLevelDebuggingConfig[Enabled]
[debug]     - customSourceRoots:       []
[debug]     - generateFunctionSourcePositions: true
[debug]     - generateLocalVariables:  true
[debug]     )
[debug] )
[debug] )
[info] Linking (multithreadingEnabled=true, disable if not used) (2568 ms)
[info] Discovered 1488 classes and 9302 methods after classloading
[info] Checking intermediate code (quick) (73 ms)
[info] Optimizing skipped
[info] Generating intermediate code (with debug metadata) (1431 ms)
[info] Total (4496 ms)
[error] java.util.NoSuchElementException: key not found: Local(5)
[error] 	at scala.collection.MapLike.default(MapLike.scala:236)
[error] 	at scala.collection.MapLike.default$(MapLike.scala:235)
[error] 	at scala.collection.AbstractMap.default(Map.scala:65)
[error] 	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$3(Lower.scala:265)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$3$adapted(Lower.scala:210)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.scalanative.codegen.Lower$Impl.onInsts(Lower.scala:210)
[error] 	at scala.scalanative.nir.Transform.onDefn(Transform.scala:20)
[error] 	at scala.scalanative.nir.Transform.onDefn$(Transform.scala:10)
[error] 	at scala.scalanative.codegen.Lower$Impl.super$onDefn(Lower.scala:133)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefn$1(Lower.scala:133)
[error] 	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:47)
[error] 	at scala.scalanative.codegen.Lower$Impl.onDefn(Lower.scala:133)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefns$1(Lower.scala:119)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.scalanative.codegen.Lower$Impl.onDefns(Lower.scala:109)
[error] 	at scala.scalanative.codegen.Lower$.apply(Lower.scala:15)
[error] 	at scala.scalanative.codegen.llvm.CodeGen$.$anonfun$lower$3(CodeGen.scala:57)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:42)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1570)
[error] (Test / nativeLink) java.util.NoSuchElementException: key not found: Local(5)

```

My test:

```scala
class MySqlSuite extends munit.FunSuite {

  test("mysql connect") {

    val mysql = new MySql()
    Zone:
      val res = mysql.connect(
        host = MysqlHost("127.0.0.1"),
        user = MysqlUser("test"),
        password = MysqlPassword("test"),
        database = MysqlDatabase("test"),
      )
      assert(res.isSuccess)
  }

}
```

**Comment by LeeTibbert** [comment]
@mobilemindtec 

In the interest of getting you a timely, if not informed, reply, let me respond.

In looking at the log file and reproducer you kindly supplied, I noticed 
that you are using Scala `scala-3.5.0-RC6`.   I suspect that you are 
wailing in the land of "Not-Yet-Soup"; that is, the Scala version
may exist but any required changes for Scala Native are not
in the SN git repository mainline.

Is there some feature of  Scala -RC6 that you _require_?

I use Scala 3.5.0-RC4 in my daily work, which uses JUnit
tests extensively.  Regrettably, all bugs found so far have
been my code. I do not commonly use munit, so I can not speak
to that combination.

I seem to remember having tried a week or so to upgrade to
-RC5 and encountering a problem. Vague memories of it
being similar to the one you report.  I had/have work to get
on with, so I reverted to -RC4 retreated from beyond the bleeding edge.
Met my needs, but perhaps not yours.

What happens if you fall back to -RC4 until SN support is announced.

The way I usually get a sneak peek is to examine the file `project/ScalaVersions.scala`.
There is still a line `1.to(4).map(v => s"3.5.0-RC$v")`.  Here that tells me that
SN mainline only supports up to "3.4.0-RC4".  

I hope this helps.   If your project is still broken on -RC4, please let me/us know.

**Comment by WojciechMazur** [comment]
I think it should be fixed already in https://github.com/scala-native/scala-native/pull/4013 I'm preparing for a release later this  . I'll try to confirm it later

**Comment by mobilemindtec** [comment]
@LeeTibbert  I tested with 3.4.2, 3.5.0-RC2, 3.5.0-RC4 and 3.5.0-RC6. These were the versions of scala that I tested.

**Comment by LeeTibbert** [comment]
> @LeeTibbert I tested with 3.4.2, 3.5.0-RC2, 3.5.0-RC4 and 3.5.0-RC6. These were the versions of scala that I tested.

Did any of them work?   Sounds like a fix is in the pipeline.

**Comment by LeeTibbert** [comment]
For what it is worth, I can confirm that Scala Native runs just fine with
`scala-3.5.0-RC7`.  

I have been using it all morning and the only bugs I encountered were
my own: including a live scorpion running under my keyboard and then
skittering away. Wonder where I will find it this afternoon?

Thank you Wojciech for both Scala 3.5.0-RC7 and the Scala Native fix.

**Comment by WojciechMazur** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/4013
