### ISSUE TITLE
[0.5, javalib] UB when using skipNBytes on GZIPInputStream

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#4072]
see #4071, same reproducer, but replace `skip` with `skipNBytes`. The program links, but there are errors and then UB exception:

```
Linking (multithreadingEnabled=true, disable if not used) (1391 ms)
[info] Discovered 1102 classes and 7585 methods after classloading
[info] Checking intermediate code (quick) (53 ms)
[warn]
Found 6 errors on @"M11ExtractTar$D12readObject$1L19java.io.InputStreamL25scala.util.boundary$LabelL18java.nio.file.PathuEPT11ExtractTar$" :
[warn]     can't call D10skipNBytesjuEO on @"T28java.io.ByteArrayInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T23java.io.FileInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T29java.util.zip.GZIPInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T28java.io.ByteArrayInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T23java.io.FileInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T29java.util.zip.GZIPInputStream"
[warn]
6 errors found
[info] Multithreading was not explicitly enabled - initial class loading has not detected any usage of system threads. Multithreading support will be disabled to improve performance.
[info] Linking (multithreadingEnabled=false) (640 ms)
[info] Discovered 937 classes and 6301 methods after classloading
[warn]
Found 6 errors on @"M11ExtractTar$D12readObject$1L19java.io.InputStreamL25scala.util.boundary$LabelL18java.nio.file.PathuEPT11ExtractTar$" :
[warn]     can't call D10skipNBytesjuEO on @"T28java.io.ByteArrayInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T23java.io.FileInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T29java.util.zip.GZIPInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T28java.io.ByteArrayInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T23java.io.FileInputStream"
[warn]     can't call D10skipNBytesjuEO on @"T29java.util.zip.GZIPInputStream"
[warn]
6 errors found
[info] Checking intermediate code (quick) (26 ms)
[info] Discovered 915 classes and 4999 methods after optimization
[info] Optimizing (debug mode) (1219 ms)
[info] Produced 9 LLVM IR files
[info] Generating intermediate code (2093 ms)
[info] Compiling to native code (1638 ms)
[info] Linking with [pthread, dl, z]
[info] Linking native code (immix gc, none lto) (188 ms)
[info] Postprocessing (0 ms)
[info] Total (6068 ms)
Exception in thread "main"scala.scalanative.runtime.UndefinedBehaviorError
        at scala.scalanative.runtime.package$.throwUndefined(Unknown Source)
        at ExtractTar$.readObject$1(Unknown Source)
        at ExtractTar$.extract(Unknown Source)
        at ExtractTar$package$.hello(Unknown Source)
        at hello.main(Unknown Source)
        at <none>.main(Unknown Source)
```

**Comment by LeeTibbert** [comment]
A shot in the dark, meant to be helpful:

From Google AI summary.
> In Java, the skipNBytes() method is used to skip over a specified number of bytes in an InputStream. It was introduced in Java 9.

Scala Native javalib is based on Java 8. Some post J8 methods have been implemented ad-hoc and can be used
if one compiles using a Java versions which contains them.

A quick series of `grep` comands on `java.io` and `java.util.zip` lead me to believe that `skipNBytes()` has
not been implemented in SN javalib.

`skip(value)` appears for me.
> ZipInputStream.scala:  override def skip(value: Long): Long = {

I am off to check if there is a unit-test for it.

**Comment by LeeTibbert** [comment]
```
unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/util/zip/ZipInputStreamTest.scala

```
exits and has at least a test `` @Test def skipLong(): Unit = {`.  

I do not know if that file and or that test ever get run. I did not try manually.

Looks to me like the `@Before` and `@After` logic is broken: it needs to be
in a static class aka Object.

I may see if I can create some time  to fix that.

**Comment by keynmol** [comment]
> A quick series of grep comands on java.io and java.util.zip lead me to believe that skipNBytes() has
not been implemented in SN javalib.

I see

I half-expected this situation to be a linking error (after all that's what SN does for missing methods), given that it genuinely doesn't exist, but it seems to progress all the way to UB at runtime, which is IMO not a great experience

**Comment by LeeTibbert** [comment]
> I half-expected this situation to be a linking error (after all that's what SN does for missing methods), given that it 
> genuinely doesn't exist, but it seems to progress all the way to UB at runtime, which is IMO not a great experience

I think this is a Jonathan Swiftian "Big_End_of_the_Egg" vs "Small_End_of_the_Egg" preference, with strong
voices in each camp.

I personally prefer "hard stops" on the first error, i.e. fatal warnings.  I know people who insist on seeing all
2048 or more cascade errors, particularly when they are looking at batch log files.

I believe there is a scalac option which can be set in a .sbt. (mumble fatal_warnings or such).
I think the rest of the build will error out early, as desired, if there is a hard scalac error.

I think the rationale for proceeding is that some people may be exercising code paths which do
not touch the unresolved symbol.  I grudgingly admit that this can be useful when porting code.
It can be done incrementally and not everything need work in order for anything to work.


To be fair, the build did give a warning "Found 6 errors on @"M11ExtractTar$D12readObject$1L19java.io.InputStreamL25scala.util.boundary$LabelL18java.nio.file.PathuEPT11ExtractTar$" "

**Comment by LeeTibbert** [comment]
I believe, and hope, this was fixed in PR #4138.  

I am taking the liberty of closing this Issue in order to keep only 
active Issues in the backlog.

If you discover the fix above does not resolve this Issue, my apology, and please reopen.
