### ISSUE TITLE
Build failure on ubuntu 14.04 with sbt-0.13.11 

### ISSUE THREAD

**Issue by langley** [scala-native/scala-native#48]
I'm running ubuntu 14.04, java 
langley@oak:$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
langley@oak:$ scala -version
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
and sbt-0.13.11 

Here's what I see, any ideas?  I tried nuking ~/.ivy2 and ~/.m2 and that had no effect.
langley@oak:$ sbt
[info] Loading project definition from /home/langley/lab/scala-native/project
[info] Updating {file:/home/langley/lab/scala-native/project/}scala-native-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo1.maven.org/maven2/com/geirsson/sbt-scalafmt_2.10_0.13/0.2.3/sbt-scalafmt-0.2.3.jar ...
[info] 	[SUCCESSFUL ] com.geirsson#sbt-scalafmt;0.2.3!sbt-scalafmt.jar (1189ms)
[info] Done updating.
[info] Compiling 61 Scala sources to /home/langley/lab/scala-native/project/target/scala-2.10/sbt-0.13/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 7.381 s
[warn] there were 2 feature warning(s); re-run with -feature for details
[warn] one warning found
java.util.NoSuchElementException: head of empty stream
	at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1028)
	at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1026)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$3.apply(ScalaNativePluginInternal.scala:61)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$3.apply(ScalaNativePluginInternal.scala:61)
	at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.util.NoSuchElementException: head of empty stream
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by metasim** [comment]
[I just found](https://github.com/scala-native/scala-native/issues/46#issuecomment-218632925) that running sbt with Java 7 resolved a different back trace. Might not be the same problem, but did note that you were using Java 8.

**Comment by langley** [comment]
The problem was indicated in the error is at ScalaNativePluginInternal.scala:61
which is 
   

>     nativeClang := file(Process(Seq("which", "clang++")).lines_!.head),

Well, I didn't have anything for which to find. 

When I fixed this by linking my /usr/lib/llvm-3.6/bin/clang++ to /usr/bin/clang++ 

I got to the next error ;^)

**Comment by langley** [comment]
Anyone know how to make sbt "fail gracefully" in the middle of creating projectSettings the way that ScalaNativePluginInternal does? An error message here would be nice ;^) 

By the way, did I say how COOL THIS PROJECT IS!?!

**Comment by sergeyshpadyrev** [comment]
I solved this problem. You need to install llvm with clang first.

**Comment by sergeyshpadyrev** [comment]
I solved this problem. You need to install llvm, clang and gc first.
I did it by <a href="http://www.smartjava.org/content/getting-started-scala-native">this instruction</a>

**Comment by densh** [comment]
Getting things build on Linux a bit complicated at the moment, @andreaTP's `docker/` script is the easiest way to do it semi-automatically right now. We're currently working on making it easier. I've gathered all the common issues people are hitting in https://github.com/scala-native/scala-native/issues/102 , follow that ticket for updates.
