### ISSUE TITLE
Calling function with CVararg

### ISSUE THREAD

**Issue by regb** [scala-native/scala-native#547]
Hello,

While implementing some bindings, I came across a compiler error with the following code:

    object Main {
      import SDL._
      def main(args: Array[String]): Unit = {
        println("Hello Native")
        SDL_SetError(c"hey %s, what's wrong with you?", c"Dude")
        println(fromCString(SDL_GetError()))
      }
  
      //define IMG_SetError SDL_SetError
      def IMG_SetError(fmt: CString, args: CVararg*): CInt = SDL_SetError(fmt, args:_*)
    }

    @extern
    @link("SDL")
    object SDL {
      def SDL_SetError(fmt: CString, args: CVararg*): CInt = extern
      def SDL_GetError(): CString = extern
    }

The issue is related to the definition of SetError, which forwards the CVararg* to the external functions. I was trying to expose the macro defined above. Here is the error I get with `sbt compile`:

`java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethodArgs$3.apply(NirCodeGen.scala:2088)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethodArgs$3.apply(NirCodeGen.scala:2085)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethodArgs(NirCodeGen.scala:2085)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethodCall(NirCodeGen.scala:2015)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethodCall(NirCodeGen.scala:1997)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1041)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:521)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$15.apply(NirCodeGen.scala:468)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$15.apply(NirCodeGen.scala:468)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        ...
`

The stacktrace is longer, I can paste the full if that helps.

**Comment by densh** [comment]
This is another instance of #317

**Comment by densh** [comment]
Fixed in #1426
