### ISSUE TITLE
nativeLink error java.lang.noSuchMethodError: java.nio.file.Files.walk

### ISSUE THREAD

**Issue by anterak13** [scala-native/scala-native#586]
Hi, I created the hello world example from scratch
running sbt 0.13.13 on ubuntu 16.04 with llvm, clang and clang++ 3.8 from deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main,  libgc-dev.so from official repos,

I cannot succeed running the hello world example given on scala-native.org

build.sbt
```
enablePlugins(ScalaNativePlugin)

scalaVersion := "2.11.8"
```
project/plugins.sbt
```
addSbtPlugin("org.scala-native" % "sbt-scala-native"  % "0.1.0")
```

Main.scala
```
package example

object Main {
  def main(args: Array[String]): Unit =
    println("Hello, world!")
}

```

sbt run gives this error trace:

```> run
[info] running
[info] /usr/bin/clang-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/wrap.c
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/wrap.c.o
[info] running
[info] /usr/bin/clang-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/time.c
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/time.c.o
[info] running
[info] /usr/bin/clang-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/gc.c
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/gc.c.o
[info] running
[info] /usr/bin/clang-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/unwind.c
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/unwind.c.o
[info] running
[info] /usr/bin/clang-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/posix.c
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/posix.c.o
[info] running
[info] /usr/bin/clang++-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/eh.cpp
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/eh.cpp.o
[info] running
[info] /usr/bin/clang-3.8
[info] 	-I/usr/local/include
[info] 	-c
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/dyndispatch.c
[info] 	-o
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/dyndispatch.c.o
[info] running
[info] /usr/bin/clang-3.8
[info] 	-S
[info] 	-emit-llvm
[info] 	/home/rdelmas/Projects/scala-native/target/scala-2.11/nativelib/target.c
[trace] Stack trace suppressed: run last *:nativeLink for the full output.
[error] (*:nativeLink) java.lang.NoSuchMethodError: java.nio.file.Files.walk(Ljava/nio/file/Path;I[Ljava/nio/file/FileVisitOption;)Ljava/util/stream/Stream;
[error] Total time: 0 s, completed 22 mars 2017 14:26:08
> last *:nativeLink
java.lang.NoSuchMethodError: java.nio.file.Files.walk(Ljava/nio/file/Path;I[Ljava/nio/file/FileVisitOption;)Ljava/util/stream/Stream;
	at scala.scalanative.io.VirtualDirectory$LocalDirectory.files(VirtualDirectory.scala:134)
	at scala.scalanative.linker.Path$Impl.<init>(Path.scala:30)
	at scala.scalanative.linker.Path$.apply(Path.scala:26)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13$$anonfun$apply$6$$anonfun$apply$7$$anonfun$21.apply(ScalaNativePluginInternal.scala:373)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13$$anonfun$apply$6$$anonfun$apply$7$$anonfun$21.apply(ScalaNativePluginInternal.scala:372)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13$$anonfun$apply$6$$anonfun$apply$7.apply(ScalaNativePluginInternal.scala:372)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13$$anonfun$apply$6$$anonfun$apply$7.apply(ScalaNativePluginInternal.scala:346)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$RichLogger.time(ScalaNativePluginInternal.scala:102)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13$$anonfun$apply$6.apply(ScalaNativePluginInternal.scala:346)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13$$anonfun$apply$6.apply(ScalaNativePluginInternal.scala:343)
	at scala.scalanative.util.Scope$.apply(Scope.scala:30)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13.apply(ScalaNativePluginInternal.scala:343)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$unscopedSettings$13.apply(ScalaNativePluginInternal.scala:343)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:nativeLink) java.lang.NoSuchMethodError: java.nio.file.Files.walk(Ljava/nio/file/Path;I[Ljava/nio/file/FileVisitOption;)Ljava/util/stream/Stream;
```

**Comment by Duhemm** [comment]
Are you using Java 8? This is a requirement to use Scala Native.

**Comment by anterak13** [comment]
thanks I was using java 7_u95 without being aware of it, it works with java 8
