### ISSUE TITLE
CStruct23 and beyond

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#637]
It's not possible to define CStruct larger than 22 field.

I tried to add the following in my project:

```scala
final abstract class CStruct24[F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24]
object CStruct24 {
  implicit def struct3[F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24]: CField3[CStruct24[F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24], F3] = undefined
  implicit def struct4[F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24]: CField4[CStruct24[F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24], F4] = undefined
}
```
I only needed to access field 3 and 4 of a `CStruct24`.

```
[info] Optimizing NIR (912 ms)
scala.scalanative.util.package$UnsupportedException: Ptr.elemty(Vector(Int(3))) (class java.lang.String)
        at scala.scalanative.util.package$.unsupported(package.scala:11)
        at scala.scalanative.nir.Type.elemty(Types.scala:16)
        at scala.scalanative.codegen.CodeGen$Impl.genLet(CodeGen.scala:577)
        at scala.scalanative.codegen.CodeGen$Impl.genInst(CodeGen.scala:437)
        at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genBlock$1.apply(CodeGen.scala:249)
        at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genBlock$1.apply(CodeGen.scala:248)
        at scala.scalanative.util.ShowBuilder$$anonfun$rep$1.apply(Show.scala:21)
        at scala.scalanative.util.ShowBuilder$$anonfun$rep$1.apply(Show.scala:20)
        at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:224)
        at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:130)
        at scala.scalanative.util.ShowBuilder.rep(Show.scala:20)
        at scala.scalanative.codegen.CodeGen$Impl.genBlock(CodeGen.scala:248)
        at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genFunctionDefn$3.apply(CodeGen.scala:233)
        at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genFunctionDefn$3.apply(CodeGen.scala:232)
        at scala.scalanative.optimizer.analysis.ControlFlow$Graph.foreach(ControlFlow.scala:68)
        at scala.scalanative.codegen.CodeGen$Impl.genFunctionDefn(CodeGen.scala:232)
        at scala.scalanative.codegen.CodeGen$Impl.genDefn(CodeGen.scala:167)
        at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genDefns$2.apply(CodeGen.scala:138)
        at scala.scalanative.codegen.CodeGen$Impl$$anonfun$genDefns$2.apply(CodeGen.scala:136)
        at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:224)
        at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:130)
        at scala.scalanative.codegen.CodeGen$Impl.genDefns(CodeGen.scala:136)
        at scala.scalanative.codegen.CodeGen$Impl.gen(CodeGen.scala:84)
        at scala.scalanative.codegen.CodeGen$$anonfun$debug$1$2$$anonfun$apply$1.apply(CodeGen.scala:42)
        at scala.scalanative.codegen.CodeGen$$anonfun$debug$1$2$$anonfun$apply$1.apply(CodeGen.scala:41)
        at scala.scalanative.io.package$.withScratchBuffer(package.scala:14)
        at scala.scalanative.codegen.CodeGen$$anonfun$debug$1$2.apply(CodeGen.scala:41)
        at scala.scalanative.codegen.CodeGen$$anonfun$debug$1$2.apply(CodeGen.scala:36)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.parallel.mutable.ParHashTable$EntryIterator.foreach(ParHashTable.scala:31)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:183)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (*:nativeLink) scala.scalanative.util.package$UnsupportedException: Ptr.elemty(Vector(Int(3))) (class java.lang.String)
```

**Comment by MasseGuillaume** [comment]
The c spec (C99 specs http://c0x.coding-guidelines.com/5.2.4.1.html) set the limit to 1023 (line 297).

**Comment by CremboC** [comment]
Can this not be implemented as an `HList`?

**Comment by densh** [comment]
@CremboC Doing an HList-like structure is a possible fix for this, but it doesn't completely solve the problem of `_N` accessor methods on `Ptr[T]`. Unfortunately there is no easy unobtrusive fix for this.

**Comment by densh** [comment]
@MasseGuillaume Adding your own CStructs is not expected to work. Currently we set the limit to 22, and it stops there.

**Comment by MasseGuillaume** [comment]
@densh 

if we bump this to 1023
https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/native/CStruct.scala.gyb#L6

and CFields and related method would it work?

**Comment by densh** [comment]
No, it wouldn't. It takes 8000 LOC to support 22 fields with current approach, this is not going to scale to 1023.

**Comment by MasseGuillaume** [comment]
I see, we need a CField for each CStruct so its `n * n / 2`.
