### ISSUE TITLE
Link cast to `Nothing`

### ISSUE THREAD

**Issue by LukasKellenberger** [scala-native/scala-native#644]
Casting a value to `Nothing` should fail at runtime.

```scala
object Main {
  def main(args: Array[String]): Unit = 2.asInstanceOf[Nothing]
}
```

Currently it fails during the AsLowering pass.
```
scala.scalanative.util.package$UnsupportedException: can't cast from Class(Top(java.lang.Integer)) to Nothing (class java.lang.String)
	at scala.scalanative.util.package$.unsupported(package.scala:11)
	at scala.scalanative.optimizer.pass.AsLowering.onInst(AsLowering.scala:15)
	at scala.scalanative.optimizer.Pass$$anonfun$onInsts$1.apply(Pass.scala:41)
        ...
```

**Comment by densh** [comment]
Thanks for the bug report!
