### ISSUE TITLE
Add support for java.lang.{Process, ProcessBuilder}

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#746]
Those two should be quite doable on top of our existing I/O layer and would fit in nicely to complete the local I/O story.

**Comment by densh** [comment]
Related: #305

**Comment by hewie** [comment]
I'd like to implement this.

**Comment by densh** [comment]
@hewie Go for it! 👍

**Comment by hwielenberg** [comment]
Can s.o. take a look at 44e53a4fb2568d98daf42e835ca76b4fe01a6a20 .

It only compiles if the code is added after a `nativelib/publishLocal`.

`nativelib/clean`
`nativelib/publishLocal`
Add the code
`nativelib/publishLocal`
Works

`nativelib/clean`
Add the code
`nativelib/publishLocal`
throws the following Exception:
```
java.lang.NullPointerException
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1093)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:568)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$19.apply(NirCodeGen.scala:515)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$19.apply(NirCodeGen.scala:515)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalMethodBody(NirCodeGen.scala:514)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethod$1.apply(NirCodeGen.scala:304)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethod(NirCodeGen.scala:279)
...
```

**Comment by hwielenberg** [comment]
And in which package / submodule should the class NullTerminatedArray exist?

**Comment by densh** [comment]
@hwielenberg Thanks for the report, this does look like a bug, I'll have a look on Thursday!

**Comment by schrepfler** [comment]
This would be a really nice to have.

**Comment by amirsh** [comment]
I also really appreciate if Scala Native supports `Process` and `ProcessBuilder`.

**Comment by ScalaWilliam** [comment]
Very cool.
