### ISSUE TITLE
InputStreamReader/OutputStreamWriter should throw NPE if null is passed to constructor

### ISSUE THREAD

**Issue by matil019** [scala-native/scala-native#818]
Demonstration:

```sandbox/Test.scala
object Test {
  def main(args: Array[String]): Unit = {
    new java.io.InputStreamReader(null)
    // JVM:
    // java.lang.NullPointerException
    // at java.io.Reader.<init>(Reader.java:78)
    // at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
    // ... 32 elided
    println(":(")

    new java.io.OutputStreamWriter(null)
    // JVM:
    // java.lang.NullPointerException
    // at java.io.Writer.<init>(Writer.java:88)
    // at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:109)
    // ... 32 elided
    println(":(")

    // Scala Native so far:
    // :(
    // :(
  }
}
```

As implied by the stacktrace on JVM, the true cause of this problem is lack of support for locking mechanism of `Reader`/`Writer` base classes.

**Comment by densh** [comment]
Thanks for the bug report!
