### ISSUE TITLE
Compiler throws exception when I'm trying to use Scope pattern in nativelib

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#821]
I copied files from Util project to Nativelib to have able to include Scope.
```
final class MyClass(val name:String)(implicit in: Scope) extends Resource {
...
}
```
```
java.lang.NullPointerException
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1029)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:520)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$23.apply(NirCodeGen.scala:740)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$23.apply(NirCodeGen.scala:738)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genTry(NirCodeGen.scala:738)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:513)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:869)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:573)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$79.apply(NirCodeGen.scala:2051)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$79.apply(NirCodeGen.scala:2051)
        at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:91)
        at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:90)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scala.scalanative.nir.Focus$.sequenced(Focus.scala:90)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genSimpleArgsWithPt(NirCodeGen.scala:2051)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genSimpleArgs(NirCodeGen.scala:2048)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApplyLabel(NirCodeGen.scala:1049)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1030)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:520)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:869)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:573)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:869)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:573)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genIf(NirCodeGen.scala:675)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:501)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genLabel$1.apply(NirCodeGen.scala:901)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genLabel$1.apply(NirCodeGen.scala:901)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genLabel(NirCodeGen.scala:900)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMatch$2.apply(NirCodeGen.scala:882)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMatch$2.apply(NirCodeGen.scala:881)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMatch(NirCodeGen.scala:881)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.translateMatch$1(NirCodeGen.scala:854)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:859)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:573)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$15.apply(NirCodeGen.scala:467)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$15.apply(NirCodeGen.scala:467)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalMethodBody(NirCodeGen.scala:466)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethod$1.apply(NirCodeGen.scala:300)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethod(NirCodeGen.scala:275)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:261)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:259)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethods(NirCodeGen.scala:259)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalClass(NirCodeGen.scala:190)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:163)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:161)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genClass(NirCodeGen.scala:161)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:140)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:136)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.apply(NirCodeGen.scala:136)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
        at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.run(NirCodeGen.scala:112)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
        at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
        at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
        at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
        at sbt.inc.Incremental$.compile(Incremental.scala:71)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
        at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:155)
        at sbt.Compiler$.compile(Compiler.scala:141)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:879)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:870)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:868)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by muxanick** [comment]
Found the line in Scope.scala which crashes compiler:
```
private[this] var resources: List[Resource] = Nil
```

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by muxanick** [comment]
I unblocked at the moment, I slightly changed Scope.scala file and it works for me

**Comment by WojciechMazur** [comment]
Outdated, test steps: 
1. Copy util.Scope to scalanative.unsafe
2. Create test class instance in scalanative.unsafe and it's duplicate in sandbox: 
```
final class Scoped(val name: String)(implicit in: Scope) extends Resource {
  override def close(): Unit = println(s"closing $name")
}
```
3. Run in sandbox: 
```
  Scope { implicit scope =>
      val x = new scalanative.unsafe.Scoped("hello")
      scope.acquire(x)
      val y = new Test.Scoped("world")
      scope.acquire(y)
      scope.close()
    }
```

Tested with scala 2.11 and 2.12 with debug and releaseFast mode.
