### ISSUE TITLE
Nondeterministic argonaut test failure in MacOS

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#852]
https://travis-ci.org/xuwei-k/argonaut/jobs/243894862

[full log](https://gist.github.com/xuwei-k/aa823e40826d60906bcd37e33f4ad39c)

https://github.com/xuwei-k/argonaut/commit/2bd9e59cc5678a9756f304bd5141893092164fac

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 398445712
	at java.lang.Throwable.init(Unknown Source)
	at java.lang.Exception.init(Unknown Source)
	at java.lang.RuntimeException.init(Unknown Source)
	at java.lang.RuntimeException.init(Unknown Source)
	at java.lang.IndexOutOfBoundsException.init(Unknown Source)
	at java.lang.StringIndexOutOfBoundsException.init(Unknown Source)
	at java.lang.StringIndexOutOfBoundsException.init(Unknown Source)
	at java.lang.String.substring(Unknown Source)
	at java.lang.String.subSequence(Unknown Source)
	at java.util.regex.Matcher.group(Unknown Source)
	at scala.util.matching.Regex$$anonfun$unapplySeq$1.apply(Unknown Source)
	at scala.util.matching.Regex$$anonfun$unapplySeq$1.apply(Unknown Source)
	at scala.collection.immutable.List.map(Unknown Source)
	at scala.util.matching.Regex.unapplySeq(Unknown Source)
	at argonaut.JsonDecimal.normalized(Unknown Source)
	at argonaut.JsonNumber.equals(Unknown Source)
	at java.lang.Object.scala$underscore$==(Unknown Source)
	at argonaut.JNumber.equals(Unknown Source)
	at java.lang.Object.scala$underscore$==(Unknown Source)
	at scala.collection.GenMapLike$$anonfun$liftedTree1$1$1.apply(Unknown Source)
	at scala.collection.GenMapLike$$anonfun$liftedTree1$1$1.apply(Unknown Source)
	at scala.collection.Iterator$class$.forall(Unknown Source)
	at scala.collection.AbstractIterator.forall(Unknown Source)
	at scala.collection.IterableLike$class$.forall(Unknown Source)
	at scala.collection.AbstractIterable.forall(Unknown Source)
	at scala.collection.GenMapLike$class$.liftedTree1$1(Unknown Source)
	at scala.collection.GenMapLike$class$.equals(Unknown Source)
	at scala.collection.AbstractMap.equals(Unknown Source)
	at java.lang.Object.scala$underscore$==(Unknown Source)
	at argonaut.JsonObjectInstance.equals(Unknown Source)
	at java.lang.Object.scala$underscore$==(Unknown Source)
	at argonaut.JObject.equals(Unknown Source)
	at java.lang.Object.scala$underscore$==(Unknown Source)
	at scala.util.Right.equals(Unknown Source)
	at java.lang.Object.scala$underscore$==(Unknown Source)
	at argonaut.TestMain$$anonfun$main$1.apply(Unknown Source)
	at argonaut.TestMain$$anonfun$main$1.apply(Unknown Source)
	at scala.collection.IndexedSeqOptimized$class$.foreach(Unknown Source)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(Unknown Source)
	at argonaut.TestMain$.main(Unknown Source)
	at <none>.main(Unknown Source)
```

**Comment by xuwei-k** [comment]
Maybe Regex related issue 🤔 

https://github.com/argonaut-io/argonaut/blob/b9dee7de59465f2d2459de7c0279ccdc1caedd10/argonaut/shared/src/main/scala/argonaut/JsonNumber.scala#L201

**Comment by xuwei-k** [comment]
minimal reproduce example

```scala
object Test {
  def main(args: Array[String]): Unit = {
    val JsonNumberRegex = """(-)?((?:[1-9][0-9]*|0))(?:\.([0-9]+))?(?:[eE]([-+]?[0-9]+))?""".r
    val JsonNumberRegex(negative, intStr, decStr, expStr) = "0.000000"
  }
}
```

Is this https://github.com/scala-native/scala-native/pull/740 for something?

**Comment by muxanick** [comment]
Looks very similar to 740

**Comment by muxanick** [comment]
I tested this case, as I said before, re2 returns null if length is zero:
returns 5 groups:
```
group(0) = 0.000000,  length = 8
group(1) = (null), length = 0
group(2) = 0.000000, length = 1
group(3) = 000000, length = 6
group(4) = (null), length = 0
```
So, we can fix it in cpp code or in scala.
@densh My PR is fixing it, what do you think?

**Comment by densh** [comment]
@xuwei-k Thanks for the bug report and minimization!
