### ISSUE TITLE
Unit tests fail due to new test harness in Travis CI

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#863]
This failure was while compiling for Mac.
https://travis-ci.org/scala-native/scala-native/jobs/245773193
```
[info] Compiling 1 Scala source to /Users/travis/build/scala-native/scala-native/unit-tests/target/scala-2.11/test-classes...
[info] Linking (6775 ms)
[info] Discovered 3023 classes and 17652 methods
[info] Optimizing (9606 ms)
[info] Generating intermediate code (2383 ms)
[info] Produced 62 files
[info] Compiling to native code (3555 ms)
[info] Linking native code (663 ms)
[info] Starting process '/Users/travis/build/scala-native/scala-native/unit-tests/target/scala-2.11/tests-out' on port '9736'.
java.lang.Exception: Couldn't communicate with remote runner.
	at scala.scalanative.sbtplugin.testinterface.ComRunner.getSocket(ComRunner.scala:96)
	at scala.scalanative.sbtplugin.testinterface.ComRunner.<init>(ComRunner.scala:44)
	at scala.scalanative.sbtplugin.testinterface.ScalaNativeRunner.createRemoteRunner(ScalaNativeRunner.scala:49)
	at scala.scalanative.sbtplugin.testinterface.ScalaNativeRunner.<init>(ScalaNativeRunner.scala:26)
	at scala.scalanative.sbtplugin.testinterface.ScalaNativeFramework.runner(ScalaNativeFramework.scala:33)
	at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:562)
	at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:556)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$.createTestRunners(Defaults.scala:556)
	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:576)
	at sbt.Defaults$$anonfun$testTasks$7.apply(Defaults.scala:439)
	at sbt.Defaults$$anonfun$testTasks$7.apply(Defaults.scala:439)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (tests/nativetest:executeTests) java.lang.Exception: Couldn't communicate with remote runner.
[error] Total time: 56 s, completed Jun 22, 2017 1:17:06 PM
```

**Comment by densh** [comment]
Thanks for the report!
