### ISSUE TITLE
Getting StringIndexOutOfBoundsException when running benchmarks

### ISSUE THREAD

**Issue by pejovica** [scala-native/scala-native#875]
When running benchmarks I'm getting the following exception:
```scala
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 5
        at java.lang.String.substring(String.java:1963)
        at benchmarks.StatUtils$.format(Formats.scala:190)
        at benchmarks.CompletedRow$.apply(Formats.scala:160)
        at benchmarks.TextFormat$$anonfun$6.apply(Formats.scala:48)
        at benchmarks.TextFormat$$anonfun$6.apply(Formats.scala:46)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:296)
        at benchmarks.TextFormat$.show(Formats.scala:46)
        at benchmarks.Main$.main(Main.scala:17)
        at benchmarks.Main.main(Main.scala)
```
It seems that I'm getting some value without enough decimals for `StatUtils$.format` to work properly.

**Comment by densh** [comment]
@pejovica We're not able to reproduce this issue on either our CI or local development environments, can you provide more info?

**Comment by pejovica** [comment]
Well, all I did was to checkout the repo and run the benchmarks with sbt. So, except that I was using Windows Subsystem for Linux as my dev environment, I'm not sure if I have anything else to add.

It could be that because of WSL I was managing to occasionally  get somewhat "rounder" results, and it seems to me that [`format`](https://github.com/scala-native/scala-native/blob/a15c2b34ccec605f6c5d75c55d376bc7e4435ba4/benchmarks/src/main/scala/benchmarks/Formats.scala#L190) function will throw a `StringIndexOutOfBoundsException` if `n` doesn't have enough decimal digits.

**Comment by pejovica** [comment]
I just realized that this only happens when I run the benchmarks directly from java/scala, that is from a jar built by sbt. So maybe that's why you couldn't reproduce it.
```scala
Welcome to Scala 2.11.11 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_141).
Type in expressions for evaluation. Or try :help.

scala> :require benchmarks_native0.3_2.11-0.1-SNAPSHOT.jar
Added '/home/scala/benchmarks_native0.3_2.11-0.1-SNAPSHOT.jar' to classpath.

scala> import benchmarks.Main
import benchmarks.Main

scala> Main.main(Array("--test"))
java.lang.StringIndexOutOfBoundsException: String index out of range: 5
  at java.lang.String.substring(String.java:1963)
  at benchmarks.StatUtils$.format(Formats.scala:190)
  at benchmarks.CompletedRow$.apply(Formats.scala:160)
  at benchmarks.TextFormat$$anonfun$6.apply(Formats.scala:48)
  at benchmarks.TextFormat$$anonfun$6.apply(Formats.scala:46)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:296)
  at benchmarks.TextFormat$.show(Formats.scala:46)
  at benchmarks.Main$.main(Main.scala:17)
  ... 32 elided
```

**Comment by densh** [comment]
Running benchmarks from java is not officially supported and the issue is not reproducible on native.
