### ISSUE TITLE
Error executing utest tests

### ISSUE THREAD

**Issue by japgolly** [scala-native/scala-native#881]
# Error

Running utest's unit tests, `test:compile` works but when running `test`

1. It spams console looking for clang
2. It fails with linking errors
3. It attempts to run tests despite failure to create an executable.

SBT output:
<details>

```
> sbt
[info] Loading global plugins from /home/golly/.sbt/0.13/plugins
[info] Loading project definition from /home/golly/projects/utest/project
[info] Set current project to root (in build file:/home/golly/projects/utest/)

> project utestNative
[info] Set current project to utest (in build file:/home/golly/projects/utest/)

> clean
[success] Total time: 0 s, completed 29/06/2017 7:45:51 PM

> test:compile
[info] Updating {file:/home/golly/projects/utest/}utestNative...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 19 Scala sources to /home/golly/projects/utest/utest/native/target/scala-2.11/classes...
[warn] there were 26 deprecation warnings; re-run with -deprecation for details
[warn] there were two feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Compiling 15 Scala sources to /home/golly/projects/utest/utest/native/target/scala-2.11/test-classes...
[warn] /home/golly/projects/utest/utest/shared/src/test/scala/test/utest/FrameworkTests.scala:142: a pure expression does nothing in statement position; you may be omitting necessary parentheses
[warn]           12 + 2
[warn]              ^
[warn] there were two feature warnings; re-run with -feature for details
[warn] two warnings found
[success] Total time: 19 s, completed 29/06/2017 7:46:14 PM

> test
which: no clang++40 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++-4.0 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++39 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++-3.9 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++38 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++-3.8 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++37 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang++-3.7 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang40 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang39 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang-3.9 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang38 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang-3.8 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang37 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
which: no clang-3.7 in (/home/golly/Apps/scala-2.12.2/bin:/opt/java/bin:/home/golly/.cabal/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/golly/.rvm/bin:/home/golly/.golly-rc/path:/opt/android-sdk/tools:/home/golly/bin:/home/golly/.gem/ruby/2.2.0/bin:/usr/lib/emscripten:/home/golly/.npm/bin)
[info] Compiling 1 Scala source to /home/golly/projects/utest/utest/native/target/scala-2.11/test-classes...
[info] Linking (2019 ms)
[info] Discovered 1893 classes and 11570 methods
[info] Optimizing (2364 ms)
[info] Generating intermediate code (570 ms)
[info] Produced 58 files
[info] Compiling to native code (1604 ms)
[error] /usr/bin/ld: /home/golly/projects/utest/utest/native/target/scala-2.11/native/lib/platform.c.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
[error] /usr/bin/ld: /home/golly/projects/utest/utest/native/target/scala-2.11/native/lib/safepoint.c.o: relocation R_X86_64_32 against symbol `scalanative_safepoint_trigger' can not be used when making a shared object; recompile with -fPIC
[error] /usr/bin/ld: /home/golly/projects/utest/utest/native/target/scala-2.11/native/lib/unistd.c.o: relocation R_X86_64_PC32 against symbol `symlink@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
[error] /usr/bin/ld: final link failed: Bad value
[error] clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
[info] Linking native code (134 ms)
[info] Starting process '/home/golly/projects/utest/utest/native/target/scala-2.11/utest-out' on port '9826'.
Exception in thread "Thread-292" java.io.IOException: Cannot run program "/home/golly/projects/utest/utest/native/target/scala-2.11/utest-out": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at scala.scalanative.sbtplugin.testinterface.ComRunner$$anon$1.run(ComRunner.scala:35)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
[trace] Stack trace suppressed: run last utestNative/nativetest:executeTests for the full output.
[error] (utestNative/nativetest:executeTests) java.lang.Exception: Couldn't communicate with remote runner.
[error] Total time: 8 s, completed 29/06/2017 7:46:25 PM
> last utestNative/nativetest:executeTests
java.lang.Exception: Couldn't communicate with remote runner.
	at scala.scalanative.sbtplugin.testinterface.ComRunner.getSocket(ComRunner.scala:96)
	at scala.scalanative.sbtplugin.testinterface.ComRunner.<init>(ComRunner.scala:44)
	at scala.scalanative.sbtplugin.testinterface.ScalaNativeRunner.createRemoteRunner(ScalaNativeRunner.scala:49)
	at scala.scalanative.sbtplugin.testinterface.ScalaNativeRunner.<init>(ScalaNativeRunner.scala:26)
	at scala.scalanative.sbtplugin.testinterface.ScalaNativeFramework.runner(ScalaNativeFramework.scala:33)
	at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:562)
	at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:556)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$.createTestRunners(Defaults.scala:556)
	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:576)
	at sbt.Defaults$$anonfun$testTasks$7.apply(Defaults.scala:439)
	at sbt.Defaults$$anonfun$testTasks$7.apply(Defaults.scala:439)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (utestNative/nativetest:executeTests) java.lang.Exception: Couldn't communicate with remote runner.
```

</details>

# Reproduction
1. Check out https://github.com/lihaoyi/utest @ 7dadc7a5a6c34b6a9ef4427244d5605c53357f2e
2. sbt 'project utestNative` clean test

# Env details

I'm running Arch Linux.

```
> uname -a
Linux golly-desktop 4.11.6-3-ARCH #1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux

> java -version     
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

> scala -version
Scala code runner version 2.12.2 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.

> clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

> la /usr/bin/clang*
lrwxrwxrwx 1 root root        9 Jun 24 13:38 /usr/bin/clang -> clang-4.0
lrwxrwxrwx 1 root root        5 Jun 24 13:38 /usr/bin/clang++ -> clang
-rwxr-xr-x 1 root root 28595536 Jun 24 13:39 /usr/bin/clang-4.0
-rwxr-xr-x 1 root root 19927296 Jun 24 13:39 /usr/bin/clang-check
lrwxrwxrwx 1 root root        5 Jun 24 13:38 /usr/bin/clang-cl -> clang
lrwxrwxrwx 1 root root        5 Jun 24 13:38 /usr/bin/clang-cpp -> clang
-rwxr-xr-x 1 root root  1601408 Jun 24 13:39 /usr/bin/clang-format
-rwxr-xr-x 1 root root 17438928 Jun 24 13:39 /usr/bin/clang-import-test
-rwxr-xr-x 1 root root    51824 Jun 24 13:39 /usr/bin/clang-offload-bundler
```

Here is a list of everything installed on my machine, and the versions:
https://github.com/japgolly/.golly-rc/blob/8e6bbad3342891d5d34948a5eccd25d1779c07f1/ref/desktop-arch/installed_packages_and_versions

**Comment by densh** [comment]
@japgolly Thanks for the detailed report! I'll try to reproduce and see what went wrong. It's been a while since I used Arch Linux. 😄

**Comment by japgolly** [comment]
No worries and let me know if there's any more useful info I can provide.

The ld error message says *"recompile with -fPIC"*. Who knows, it might be as simple as that :laughing:
