### ISSUE TITLE
can't perform binary operation between Nothing and Class(Top(java.lang.Object))

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#899]
### project/plugin.sbt

```scala
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.1")
```

### build.sbt

```scala
scalaVersion := "2.11.11"

enablePlugins(ScalaNativePlugin)
```

### src/main/scala/example/Main.scala

```scala
package example

object Main {
  def main(args: Array[String]): Unit = {
    sys.error("err") == true
  }
}
```

`sbt run`

```
[error]   can't perform binary operation between Nothing and Class(Top(java.lang.Object))
[error]      while compiling: /private/tmp/scala-native-nothing/src/main/scala/example/Main.scala
[error]         during phase: nir
[error]      library version: version 2.11.11
[error]     compiler version: version 2.11.11
[error]   reconstructed args: -Xplugin:/Users/kenji/.ivy2/cache/org.scala-native/nscplugin_2.11.11/jars/nscplugin_2.11.11-0.3.1.jar -classpath /private/tmp/scala-native-nothing/target/scala-2.11/classes:/Users/kenji/.ivy2/cache/org.scala-native/nativelib_native0.3_2.11/jars/nativelib_native0.3_2.11-0.3.1.jar:/Users/kenji/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.11.jar:/Users/kenji/.ivy2/cache/org.scala-native/javalib_native0.3_2.11/jars/javalib_native0.3_2.11-0.3.1.jar:/Users/kenji/.ivy2/cache/org.scala-native/scalalib_native0.3_2.11/jars/scalalib_native0.3_2.11-0.3.1.jar -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/kenji/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.11.jar
[error] 
[error]   last tree to typer: type Main
[error]        tree position: line 3 of /private/tmp/scala-native-nothing/src/main/scala/example/Main.scala
[error]             tree tpe: <notype>
[error]               symbol: object Main in package example
[error]    symbol definition: class Main extends Object (a ModuleClassSymbol)
[error]       symbol package: example
[error]        symbol owners: object Main
[error]            call site: object Main in package example in package example
[error] 
[error] == Source file context for tree position ==
[error] 
[error]      0 package example
[error]      1 
[error]      2 object Main {
[error]      3   def main(args: Array[String]): Unit = {
[error]      4     sys.error("err") == true
[error]      5   }
[error]      6 }
scala.reflect.internal.FatalError: 
  can't perform binary operation between Nothing and Class(Top(java.lang.Object))
     while compiling: /private/tmp/scala-native-nothing/src/main/scala/example/Main.scala
        during phase: nir
     library version: version 2.11.11
    compiler version: version 2.11.11
  reconstructed args: -Xplugin:/Users/kenji/.ivy2/cache/org.scala-native/nscplugin_2.11.11/jars/nscplugin_2.11.11-0.3.1.jar -classpath /private/tmp/scala-native-nothing/target/scala-2.11/classes:/Users/kenji/.ivy2/cache/org.scala-native/nativelib_native0.3_2.11/jars/nativelib_native0.3_2.11-0.3.1.jar:/Users/kenji/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.11.jar:/Users/kenji/.ivy2/cache/org.scala-native/javalib_native0.3_2.11/jars/javalib_native0.3_2.11-0.3.1.jar:/Users/kenji/.ivy2/cache/org.scala-native/scalalib_native0.3_2.11/jars/scalalib_native0.3_2.11-0.3.1.jar -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/kenji/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.11.jar

  last tree to typer: type Main
       tree position: line 3 of /private/tmp/scala-native-nothing/src/main/scala/example/Main.scala
            tree tpe: <notype>
              symbol: object Main in package example
   symbol definition: class Main extends Object (a ModuleClassSymbol)
      symbol package: example
       symbol owners: object Main
           call site: object Main in package example in package example

== Source file context for tree position ==

     0 package example
     1 
     2 object Main {
     3   def main(args: Array[String]): Unit = {
     4     sys.error("err") == true
     5   }
     6 }
	at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.binaryOperationType(NirCodeGen.scala:1429)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBinaryOp(NirCodeGen.scala:1251)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genSimpleOp(NirCodeGen.scala:1212)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genPrimitiveOp(NirCodeGen.scala:1144)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1096)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:568)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$35.apply(NirCodeGen.scala:915)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$35.apply(NirCodeGen.scala:915)
	at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:91)
	at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:90)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.scalanative.nir.Focus$.sequenced(Focus.scala:90)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:915)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$19.apply(NirCodeGen.scala:515)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$19.apply(NirCodeGen.scala:515)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalMethodBody(NirCodeGen.scala:514)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethod$1.apply(NirCodeGen.scala:304)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethod(NirCodeGen.scala:279)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:265)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:263)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethods(NirCodeGen.scala:263)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalClass(NirCodeGen.scala:193)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:166)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:164)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genClass(NirCodeGen.scala:164)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:143)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:139)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.apply(NirCodeGen.scala:139)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.run(NirCodeGen.scala:115)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:927)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:918)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:916)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:compileIncremental) scala.reflect.internal.FatalError: 
[error]   can't perform binary operation between Nothing and Class(Top(java.lang.Object))
[error]      while compiling: /private/tmp/scala-native-nothing/src/main/scala/example/Main.scala
[error]         during phase: nir
[error]      library version: version 2.11.11
[error]     compiler version: version 2.11.11
[error]   reconstructed args: -Xplugin:/Users/kenji/.ivy2/cache/org.scala-native/nscplugin_2.11.11/jars/nscplugin_2.11.11-0.3.1.jar -classpath /private/tmp/scala-native-nothing/target/scala-2.11/classes:/Users/kenji/.ivy2/cache/org.scala-native/nativelib_native0.3_2.11/jars/nativelib_native0.3_2.11-0.3.1.jar:/Users/kenji/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.11.jar:/Users/kenji/.ivy2/cache/org.scala-native/javalib_native0.3_2.11/jars/javalib_native0.3_2.11-0.3.1.jar:/Users/kenji/.ivy2/cache/org.scala-native/scalalib_native0.3_2.11/jars/scalalib_native0.3_2.11-0.3.1.jar -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/kenji/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.11.jar
[error] 
[error]   last tree to typer: type Main
[error]        tree position: line 3 of /private/tmp/scala-native-nothing/src/main/scala/example/Main.scala
[error]             tree tpe: <notype>
[error]               symbol: object Main in package example
[error]    symbol definition: class Main extends Object (a ModuleClassSymbol)
[error]       symbol package: example
[error]        symbol owners: object Main
[error]            call site: object Main in package example in package example
[error] 
[error] == Source file context for tree position ==
[error] 
[error]      0 package example
[error]      1 
[error]      2 object Main {
[error]      3   def main(args: Array[String]): Unit = {
[error]      4     sys.error("err") == true
[error]      5   }
[error]      6 }
```

**Comment by densh** [comment]
Thanks for the bug report!
