### ISSUE TITLE
scala.scalanative.util.ScopedVar$Unitialized error

### ISSUE THREAD

**Issue by mxl** [scala-native/scala-native#906]
I'm trying to integrate scala-native and compilation fails with the below error without any helpful message:
```
scala.scalanative.util.ScopedVar$Unitialized
	at scala.scalanative.util.ScopedVar.get(ScopedVar.scala:12)
	at scala.scalanative.util.ScopedVar$.toValue(ScopedVar.scala:37)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:574)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethodCall(NirCodeGen.scala:2094)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1104)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:568)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:536)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$35.apply(NirCodeGen.scala:915)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$35.apply(NirCodeGen.scala:915)
	at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:91)
	at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:90)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.scalanative.nir.Focus$.sequenced(Focus.scala:90)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:915)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$88.apply(NirCodeGen.scala:2135)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$88.apply(NirCodeGen.scala:2135)
	at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:91)
	at scala.scalanative.nir.Focus$$anonfun$sequenced$1.apply(Focus.scala:90)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.scalanative.nir.Focus$.sequenced(Focus.scala:90)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genSimpleArgsWithPt(NirCodeGen.scala:2135)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genSimpleArgs(NirCodeGen.scala:2132)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApplyLabel(NirCodeGen.scala:1113)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genApply(NirCodeGen.scala:1094)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:568)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:917)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:917)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genIf(NirCodeGen.scala:723)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:549)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genIf(NirCodeGen.scala:723)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:549)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:917)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genIf(NirCodeGen.scala:723)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:549)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genLabel(NirCodeGen.scala:945)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMatch$2.apply(NirCodeGen.scala:930)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMatch$2.apply(NirCodeGen.scala:929)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMatch(NirCodeGen.scala:929)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.translateMatch$1(NirCodeGen.scala:902)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:907)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genBlock(NirCodeGen.scala:917)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:621)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genExpr(NirCodeGen.scala:627)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.scala$scalanative$nscplugin$NirCodeGen$NirCodePhase$$genRhs$1(NirCodeGen.scala:958)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genTailRecLabel(NirCodeGen.scala:961)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalMethodBody(NirCodeGen.scala:500)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethod$1.apply(NirCodeGen.scala:304)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethod(NirCodeGen.scala:279)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:265)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genMethods$1.apply(NirCodeGen.scala:263)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genMethods(NirCodeGen.scala:263)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genNormalClass(NirCodeGen.scala:193)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:166)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$genClass$1.apply(NirCodeGen.scala:164)
	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.genClass(NirCodeGen.scala:164)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:143)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase$$anonfun$apply$4.apply(NirCodeGen.scala:139)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.apply(NirCodeGen.scala:139)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
	at scala.scalanative.nscplugin.NirCodeGen$NirCodePhase.run(NirCodeGen.scala:115)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:886)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:877)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:875)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by densh** [comment]
Hi @mxl, can you please provide more info on the code you were trying to compile? Unfortunately it's impossible to reproduce the issue via the stack trace of the crash.

**Comment by mxl** [comment]
@densh I'm trying to add Scala Native support to Quill library. Please look at my [fork scala-native branch](https://github.com/mxl/quill/tree/scala-native). Try to compile it with `sbt compile` and you will get the above error. Also could you add some message to the error to better understand a reason why it's failing.

**Comment by ekrich** [comment]
Hi @mxl, It looks like you are trying to compile your `core` project. Just as a starting point, all the dependencies need to be compiled to Scala Native `0.3.1` in this case. Also, Native dependencies need the `%%%` like the Scala JS ones. We can try and help on the Gitter channel as well. https://gitter.im/scala-native/scala-native

**Comment by mxl** [comment]
@ekrich Thanks! Actually I did not have any hope to successfully compile the project because none of the dependencies (as I remember) support scala-native yet. So the main request here is to provide helpful error message like `Scoped var is uninitialized at the line 123 in SomeModule.scala`.

**Comment by densh** [comment]
@mxl Thanks for the detailed report, this looks like a bug on our side!
