### ISSUE TITLE
[java.util.zip] Intermittent crash in `sbt rebuild`, concurrent access to jar file

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#949]
While `sbt rebuild` command I'm experiencing intermittent crash in java.util.zip, concurrent access to scala-native..jar file.
Seems like two systems CodeGen and Reflection want to write into jar file in same time, so exception arises.

```
[info] Packaging C:\Projects\muxanick\scala-native\test-interface-serialization\target\scala-2.11\test-interface-serialization_native0.4.0-SNAPSHOT_2.11-0.4.0-SNAPSHOT.jar ...
[info]  published scalalib_native0.4.0-SNAPSHOT_2.11 to C:\Users\Mike\.ivy2\local\org.scala-native\scalalib_native0.4.0-SNAPSHOT_2.11\0.4.0-SNAPSHOT\poms\scalalib_native0.4.0-SNAPSHOT_2.11.pom
java.util.concurrent.ExecutionException: java.util.zip.ZipError: jzentry == 0,
 jzfile = 513119776,
 total = 7641,
 name = C:\Users\Mike\.ivy2\local\org.scala-native\scalalib_native0.4.0-SNAPSHOT_2.11\0.4.0-SNAPSHOT\jars\scalalib_native0.4.0-SNAPSHOT_2.11.jar,
 i = 1152,
 message = null
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
        at sbt.Execute.next$1(Execute.scala:85)
        at sbt.Execute.processAll(Execute.scala:88)
        at sbt.Execute.runKeep(Execute.scala:68)
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:359)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:358)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:378)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:69)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:67)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:314)
        at sbt.Aggregation$.timedRun(Aggregation.scala:67)
        at sbt.Aggregation$.runTasks(Aggregation.scala:76)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:37)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:36)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:158)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:157)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:253)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:250)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.runCmd$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:187)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:61)
        at sbt.xMain.run(Main.scala:35)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.util.zip.ZipError: jzentry == 0,
 jzfile = 513119776,
 total = 7641,
 name = C:\Users\Mike\.ivy2\local\org.scala-native\scalalib_native0.4.0-SNAPSHOT_2.11\0.4.0-SNAPSHOT\jars\scalalib_native0.4.0-SNAPSHOT_2.11.jar,
 i = 1152,
 message = null
        at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:520)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:500)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:481)
        at scala.reflect.io.FileZipArchive.x$1$lzycompute(ZipArchive.scala:135)
        at scala.reflect.io.FileZipArchive.x$1(ZipArchive.scala:123)
        at scala.reflect.io.FileZipArchive.root$lzycompute(ZipArchive.scala:123)
        at scala.reflect.io.FileZipArchive.root(ZipArchive.scala:123)
        at scala.reflect.io.FileZipArchive.iterator(ZipArchive.scala:152)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:91)
        at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:277)
        at scala.tools.nsc.util.DirectoryClassPath.x$15$lzycompute(ClassPath.scala:299)
        at scala.tools.nsc.util.DirectoryClassPath.x$15(ClassPath.scala:299)
        at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:299)
        at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:299)
        at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:264)
        at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:358)
        at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:358)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:358)
        at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:353)
        at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply$mcV$sp(SymbolLoaders.scala:269)
        at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply(SymbolLoaders.scala:260)
        at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply(SymbolLoaders.scala:260)
        at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
        at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:260)
        at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
        at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:256)
        at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:73)
        at scala.tools.nsc.Global.rootMirror(Global.scala:71)
        at scala.tools.nsc.Global.rootMirror(Global.scala:39)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
        at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:44)
        at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:112)
        at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:124)
        at xsbt.Runner.run(ScaladocInterface.scala:26)
        at xsbt.ScaladocInterface.run(ScaladocInterface.scala:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:73)
        at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:68)
        at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
        at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
        at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:64)
        at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:56)
        at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:49)
        at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:47)
        at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:84)
        at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:79)
        at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:54)
        at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:39)
        at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:856)
        at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:834)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] java.util.concurrent.ExecutionException: java.util.zip.ZipError: jzentry == 0,
[error]  jzfile = 513119776,
[error]  total = 7641,
[error]  name = C:\Users\Mike\.ivy2\local\org.scala-native\scalalib_native0.4.0-SNAPSHOT_2.11\0.4.0-SNAPSHOT\jars\scalalib_native0.4.0-SNAPSHOT_2.11.jar,
[error]  i = 1152,
[error]  message = null
[error] error while loading <root>, Error accessing C:\Users\Mike\.ivy2\local\org.scala-native\scalalib_native0.4.0-SNAPSHOT_2.11\0.4.0-SNAPSHOT\jars\scalalib_native0.4.0-SNAPSHOT_2.11.jar
```

**Comment by ekrich** [comment]
In case this will help - https://gist.github.com/ekrich/b638ec15606a5ac854ce7c669fb40cac

**Comment by densh** [comment]
Bumped to `0.3.4`.
