### ISSUE TITLE
Code generation crashes when invoking method on unsigned types

### ISSUE THREAD

**Issue by cornerman** [scala-native/scala-native#99]
While experimenting, I came across unsigned integer types (https://github.com/scala-native/scala-native/issues/41 already mentions some usability issues) . For me, the code generation throws a `java.util.NoSuchElementException` exception when invoking any method on an object of type `UByte/UShort/UInt/ULong`.

For example:
```
@extern object O {
  def someUnsigned(): UInt = extern
}
object Main {
  def main(args: Array[String]): Unit = {
    O.someUnsigned().toString // or any other method
    // the same happens for: new Uint(1).toString
  }
}
```

This yields the following stack trace in sbt:

```
> compile
[info] Checking out Scala source version 2.11.8
[success] Total time: 0 s, completed May 18, 2016 12:08:37 AM
> run
[info] Checking out Scala source version 2.11.8
java.util.NoSuchElementException: key not found: Val(scala.scalanative.native.UInt)
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at scala.scalanative.compiler.codegen.GenTextualLLVM.justVal(GenTextualLLVM.scala:162)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$10.apply(GenTextualLLVM.scala:167)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$10.apply(GenTextualLLVM.scala:166)
	at scala.scalanative.util.Show$$anon$1.apply(Show.scala:60)
	at scala.scalanative.util.Show$$anonfun$seqToResult$1.apply(Show.scala:73)
	at scala.scalanative.util.Show$$anonfun$seqToResult$1.apply(Show.scala:73)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scala.scalanative.util.Show$.seqToResult(Show.scala:73)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$showInsts$1.apply(GenTextualLLVM.scala:205)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$showInsts$1.apply(GenTextualLLVM.scala:196)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.scalanative.compiler.codegen.GenTextualLLVM.showInsts(GenTextualLLVM.scala:196)
	at scala.scalanative.compiler.codegen.GenTextualLLVM.showBlock(GenTextualLLVM.scala:102)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$5.apply(GenTextualLLVM.scala:87)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$5.apply(GenTextualLLVM.scala:86)
	at scala.scalanative.compiler.analysis.ControlFlow$Graph.map(ControlFlow.scala:30)
	at scala.scalanative.compiler.codegen.GenTextualLLVM.showFunctionDefn(GenTextualLLVM.scala:86)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$4.apply(GenTextualLLVM.scala:46)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$4.apply(GenTextualLLVM.scala:38)
	at scala.scalanative.util.Show$$anon$1.apply(Show.scala:60)
	at scala.scalanative.util.Show$.toResult(Show.scala:71)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2$$anonfun$apply$1.apply(GenTextualLLVM.scala:35)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2$$anonfun$apply$1.apply(GenTextualLLVM.scala:35)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2.apply(GenTextualLLVM.scala:35)
	at scala.scalanative.compiler.codegen.GenTextualLLVM$$anonfun$2.apply(GenTextualLLVM.scala:25)
	at scala.scalanative.util.Show$$anon$1.apply(Show.scala:60)
	at scala.scalanative.compiler.codegen.GenShow.gen(GenShow.scala:7)
	at scala.scalanative.compiler.Compiler$$anonfun$output$1.apply(Compiler.scala:44)
	at scala.scalanative.compiler.Compiler$$anonfun$output$1.apply(Compiler.scala:44)
	at scala.scalanative.nir.serialization.package$.serializeFile(package.scala:22)
	at scala.scalanative.compiler.Compiler.output(Compiler.scala:44)
	at scala.scalanative.compiler.Compiler.apply(Compiler.scala:67)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.scala$scalanative$sbtplugin$ScalaNativePluginInternal$$compileNir(ScalaNativePluginInternal.scala:24)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$6$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaNativePluginInternal.scala:85)
	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$$anonfun$projectSettings$6$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaNativePluginInternal.scala:67)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

**Comment by densh** [comment]
This looks like a bug, thanks for the report.

**Comment by densh** [comment]
Minimized snippet:

```scala
object Test {
  def uint: UInt = ???
  def main(args: Array[String]): Unit = uint.toString
}
```
